### ISSUE TITLE
First Android app: Android Basics in Compose

### ISSUE THREAD

**Issue by diana7u** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#1]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@diana7u 
Thank you for reaching out to us. Please provide the details of the issue you have.

**Comment by osuleymanova** [comment]
The issue is closed as no further clarification of it was provided.
