### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by ahujarahul** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#100]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2

**In which task and step of the codelab can this issue be found?**
Step 5: Practice: Compose Basics
Then navigate to 'Task Manager' practice screen.
See UI specifications, point 2:
_Set the first Text composable to a 24sp font size, 24dp padding top, and 8dp padding bottom._

**Describe the problem**
The image shown as a sample shows the text "All tasks completed" in **bold**. Making it bold is not mentioned in the step (point 2) which could teach _fontWeight_ parameter of the _Text_ Composable. Also, in the step description, it is written that the font size should be 24sp but in the sample image, it is not.

**Additional information**

The correct image should be something like:
<img width="308" alt="Screen Shot 2022-10-29 at 8 40 28 PM" src="https://user-images.githubusercontent.com/8992535/198857632-3cbf10ae-a960-4b39-92ab-3563f3e7c3b0.png">

**Comment by osuleymanova** [comment]
Hello @ahujarahul,

Thank you for reaching out to us and sharing your concern. The UI specification is updated:

![Screenshot 2023-01-17 at 11 28 04 AM](https://user-images.githubusercontent.com/86437155/213005554-205bff0a-4216-41ff-94f2-11b446b07ee6.png)
