### ISSUE TITLE
Add images: Add layout Modifiers

### ISSUE THREAD

**Issue by kmaslowiec** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#101]
[codelab url](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#8)

**In which task and step of the codelab can this issue be found?**
In step 9 'try this challange'

**Describe the problem**
The code is outdated:
```
Text(
           text = message,
           fontSize = 36.sp,
           modifier = Modifier
               .fillMaxWidth()
               .wrapContentWidth(Alignment.CenterHorizontally)
               .padding(start = 16.dp, top = 16.dp))
```

The function wrapContentWidth no longer alligns the text. The parameter textAllign should be used:
```
Text(
            text = message, fontSize = 36.sp, textAlign = TextAlign.Center,
            modifier = Modifier
                .fillMaxWidth()
                .padding(start = 16.dp, top = 16.dp))
```

**Versions**
_Android Studio version:_ Android Studio Dolphin | 2021.3.1
_API version of the emulator:_ Physical Device Samsung A-53

**Comment by android-dev-lxl** [comment]
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/pull/172

**Comment by osuleymanova** [comment]
Hello @kmaslowiec,

Thank you for reaching out to us. The code in the code snippet was updated:

![Screenshot 2023-04-03 at 3 48 36 PM](https://user-images.githubusercontent.com/86437155/229643474-d628b838-5cb0-4630-bef2-2b7ff004cf45.png)
