### ISSUE TITLE
Before you begin: Android Basics in Compose

### ISSUE THREAD

**Issue by zhongdj** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#102]
**URL of codelab**
https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin

**In which task and step of the codelab can this issue be found?**

In Chinese language version, both 2nd and 3rd tasks

**Describe the problem**
In Chinese language version, while landing into this url, it shows both my 2nd/3rd tasks were finished, but actually there are not, and while click the task buttons will lead to  lead to a wrong url: (https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-before-you-begin#0).

When I try to switch language to English, problem solved.

**Steps to reproduce?**
1. In Chinese language channel, Go to https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin
2. Click on "启动 Codelab" under either 2nd or 3rd task
3. See error... Just another wrong page

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @zhongdj,
The localization issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The links are fixed and ready for your review:

https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2?hl=zh-cn
