### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by kabir-4663** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#103]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#3

**In which task and step of the codelab can this issue be found?**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#3

**Describe the problem**

fun main() {
    val smartTvDevice = SmartDevice()
    smartTvDevice.turnOn()
    smartTvDevice.turnOff()
}
when the properties were called it didnt print the output as expected

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (28)](https://user-images.githubusercontent.com/74677650/201120763-d069acb4-dab1-477e-84fd-c432f67d72d0.png)

**Comment by osuleymanova** [comment]
Hello @kabir-4663,

Thank you for reaching out to us. Following the steps in the codelab, the code and output should look like below:

<img width="624" alt="Screenshot 2023-01-10 at 12 58 37 PM" src="https://user-images.githubusercontent.com/86437155/211663259-a805808d-6d90-4610-b2b9-740f04767136.png">
