### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by josephtheanalyst** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#104]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Name of the video (String)
Name of the channel (String)
Number of views on the video (Int) <----- This one should be Double as a data type, NOT Int, since it has a decimal, yeah? Let me know! Thanks!
Number of likes on the video (Int)
Number of comments on the video (Int)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@josephtheanalyst 
Thank you for reaching out to us.
The reason `Number of views` is an `Int` not `Double` is, it could be stored as an Int of 6900 views, and it will be formatted in the UI as a decimal after using k for thousand. 

Hop that answers your question.
