### ISSUE TITLE
Run your first app: Android Basics in Compose

### ISSUE THREAD

**Issue by k4441** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#105]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @k4441,

Please specify the issue you are facing.

**Comment by android-dev-lxl** [comment]
@k4441 
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
