### ISSUE TITLE
First Android app: Android Basics in Compose - Step 7 does not teach the learner how to import `dp`

### ISSUE THREAD

**Issue by michaelssim** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#11]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app)**

**In which task and step of the codelab can this issue be found?**
Step 7: Adding padding

**Describe the problem**
When adding the new code: `modifier = Modifier.padding(24.dp)`, the codelab should instruct the learner that `dp` must be imported or else the code won't work. This is probably the first time the learner has to import something so it's crucial to teach how to do this.

`import androidx.compose.ui.unit.dp`

**How to improve it**
![image](https://user-images.githubusercontent.com/81500505/169412376-26d0e79c-6439-42b5-bcf2-6e6d59b8f51a.png)

Here's an example:
"Notice that when you add a padding modifier to the text with a size of 24.dp, the `dp` text is red. This is happening because you need to import `dp` first in order for your code to compile. Fixing this error is simple thanks to Android Studio. Simply highlight the text and press Alt+Enter in PC/Linux or Option+Enter in Mac. **Import** should be highlighted by default so just press **Enter**.

![image](https://user-images.githubusercontent.com/81500505/169413022-e007559f-972d-484f-86d2-a6d902a44c65.png)

If you don't do this and try **Build & Refresh**, you will get an "Unresolved reference: dp" error."

![image](https://user-images.githubusercontent.com/81500505/169413183-0b6ed28d-6ce3-4a95-9a6e-7309fd015532.png)

**Comment by michaelssim** [comment]
import `dp` is taught for the first time in Pathway 3, Build a simple app with text composables, Section 7: Change font size: https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**Comment**
As mentioned in the original issue, this should be taught earlier because by the discussion of `dp` happens before the learner reaches Pathway 3. So this is being taught a step late.

**Comment by osuleymanova** [comment]
@michaelssim 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The content of the codelab was updated and published:

<img width="792" alt="Screen Shot 2022-07-25 at 3 22 26 PM" src="https://user-images.githubusercontent.com/86437155/180883793-3b0c7494-8e7e-43ef-8cc1-0b1a32405f34.png">
