### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by rick-engberg** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#110]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#3

**In which task and step of the codelab can this issue be found?**
 The second code snippet in the "**Annotations with parameters**" section is titled "Annotations without parameters" but the @Preview annotation has a parameter:
https://developer.android.com/static/codelabs/basic-android-kotlin-compose-text-composables/img/992de02d7b5dbfda_856.png

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @rick-engberg,

Thank you for reaching out to us. In fact, the description and images correspond to each other:

![Screenshot 2023-01-06 at 4 18 05 PM](https://user-images.githubusercontent.com/86437155/211121409-ae700ef1-924a-4905-8991-0375ead6e708.png)
