### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by bkrauth** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#111]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#1

**In which task and step of the codelab can this issue be found?**
Data Types -> Note

**Describe the problem**
the "Numbers" and "this table" point to the same place.  This paragraph could be clearer for navigation.

**Steps to reproduce?**
1. Go to... this page, section "Note"
2. Click on... "Numbers" and "this page"
3. See error... They go to the same place, which is not a table.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hell @bkrauth,

The issue with the wrong links that you presented to us is extremely important, and we thank you for bringing it to our attention. They are updated:
Note: For the valid ranges for the numerical data types (Int, Double, and Float), see [Numbers](https://kotlinlang.org/docs/numbers.html). For specifics on the difference between Double and Float, look at [this table](https://kotlinlang.org/docs/numbers.html#floating-point-types) comparing the two data types.
