### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by Hisham313** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#114]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator#2**

**Run your app on the Android Emulator**

**Layout in Emulator is not matching that from Android Studio**

**Steps to reproduce?**
1. Unit 1: Your first Android app
2. Pathway 2: Set up Android Studio
3. 4. Run your first app on the Android Emulator > Take codelab
4. 3. Run your app on the Android Emulator
5. This is the code I have on Android Studio:

package com.example.greetingcard
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.greetingcard.ui.theme.GreetingCardTheme

class MainActivity : ComponentActivity()
{
    override fun onCreate(savedInstanceState: Bundle?)
    {
        super.onCreate(savedInstanceState)
        setContent {
            GreetingCardTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                )
                {
                    Greeting("Android")
                }
            }
        }
    }
}

@Composable
fun Greeting(name: String)
{
    Surface(color = Color.Cyan)
    {
        Text(text = "Hi, my name is $name!", modifier = Modifier.padding(33.dp))
    }
}

@Preview(showBackground = true)
@Composable
fun DefaultPreview() {
    GreetingCardTheme {
        Greeting("Hisham")
    }
}

**Versions**
_Android Studio version: android-studio-2021.3.1.17-windows.exe
_API version of the emulator: Resizable (Experimental) API 33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="449" alt="1" src="https://user-images.githubusercontent.com/118630987/202867720-b573d35e-342d-48d0-9973-70790163437d.png">
<img width="368" alt="2" src="https://user-images.githubusercontent.com/118630987/202867721-71062771-e0c3-4113-b662-c496d2f5221f.png">

I just started learning creating Android apps. I also just signed up for GitHub so I'm not really familiar with using this site but I'm trying to learn.
I know the code above has both; Android & Hisham (my name), but I was following the instructions on the "Android Basics with Compose course" so the instructors should be aware of having different names... or maybe I am missing something!!

Thanks in advance
Hisham

**Comment by polaco2022** [comment]
Thank  [Hisham313](https://github.com/Hisham313)  very much for your time and effort, my code is similar, but when importing "import androidx.compose.ui.unit.dp" it did not allow me. I'll try it, sorry for my English.

**Comment by jayeshmann** [comment]
Hi, you need to change the name both in `onCreate` and `DefaultPreview`. 

Have a great day!

**Comment by android-dev-lxl** [comment]
@Hisham313 
Thank you for reaching out to us. 
Thank you @jayeshmann for answering 
Yes, you need to change the argument in `onCreate` to reflect on the emulator. 

![image](https://user-images.githubusercontent.com/24260141/213611941-e9590556-cc13-46be-a5c0-5c9a2bec3e6c.png)

Hope this helps.

**Comment by osuleymanova** [comment]
Hello @Hisham313 ,

Closing this issue, since there is no response. 
Hope the issue was resolved thanks to the clarification given in the comments above. 
Please create a new one, if you still need any help.
