### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by DexterGenius** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#115]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4)

Everything is outdated

I am using the latest version of android studio and I was trying to learn using your codelabs but the stuff on the codelab
is entirely different from what we have on android studio

**Comment by osuleymanova** [comment]
Hello @DexterGenius,

Could you be more specific about the outdated codelab content please?

**Comment by DexterGenius** [comment]
Forgive me please,  it was my fault. I later realised I was selecting the
wrong activity. Instead of Empty Jetpack compose activity, I chose Empty
Activity, hence the frustration. Thank you for your response though

**Comment by osuleymanova** [comment]
@DexterGenius,
 Thanks for your prompt response, and no worries!
 
 Happy coding!
