### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by syedjk** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#117]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
7-Implement a relationship between classes -> Override superclass properties from subclasses

**Describe the problem**
It says "Override the deviceStatus property" but its actually overriding "deviceType" in the code

**Comment by osuleymanova** [comment]
Hello @syedjk,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-01-19 at 10 27 49 AM](https://user-images.githubusercontent.com/86437155/213530772-12359049-0b48-4b8a-86f1-edcc17cb6e2e.png)
