### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by TrivediVishal** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#118]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#6

**In which task and step of the codelab can this issue be found?**
Create and use Variable in Kotlin -Part 7 Commenting in your code

**Describe the problem**
Everything after //, or Assume the height is 1 to start with, is interpreted as a comment 
In the above line or should be removed, I thing it is a typo. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @TrivediVishal,

Thanks for reaching out to us and reporting this typo. The text is updated:

![Screen Shot 2022-12-13 at 4 13 18 PM](https://user-images.githubusercontent.com/86437155/207472978-ac923299-158d-472f-aec2-f18e9bbdd97f.png)
