### ISSUE TITLE
Practice problems: Android Basics with Compose

### ISSUE THREAD

**Issue by vpa2k** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#9

**In which task and step of the codelab can this issue be found?**
[ANDROID BASICS WITH COMPOSE](https://developer.android.com/courses/android-basics-compose/course)
Unit 1: Your first Android app
Pathway 3: Build a basic layout
Step 10: Get the solution code

**Describe the problem**
Can't clone a repository on Windows.
I think the problem is in the file name:
"Unit 1 | Pathway 1 | Practice Problems.md"
=> 
"Unit 1 - Pathway 1 - Practice Problems.md"

**Steps to reproduce?**
As described in step.

**Versions**
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true

**Additional information**
![clone_failed](https://user-images.githubusercontent.com/29216362/169516762-d0cb709e-55b2-408f-9735-3782fd87a8c4.png)

**Comment by jinatuni20** [comment]
I have the exactly same issue.

**Comment by osuleymanova** [comment]
@vpa2k 
Thank you for reaching out to us. The path was updated.
