### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ishanadvance** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#120]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
[4. Add an Image composable](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3)

**Describe the problem**
When I added the following code:
Image(
   painter = image
)

I got this build error instead of the one in the tutorial
Cannot access '<init>': it is package-private in 'Image'

**Steps to reproduce?**
Follow the tutorial

**Versions**
_Android Studio version:_ Android Studio Dolphin | 2021.3.1 Patch 1
_API version of the emulator:_ Pixel 6 Pro API 31
<img width="1440" alt="Screenshot 2022-11-27 at 7 09 52 PM" src="https://user-images.githubusercontent.com/59140636/204138345-55bee587-f4dd-4146-a1ae-0b558da0bc94.png">

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @ishanadvance,

Thanks for reaching out to us and sharing the image with the error you are facing. First suggestion is to import whatever Android Studio suggests, then expand "More actions...:"

![Screen Shot 2022-12-12 at 3 24 06 PM](https://user-images.githubusercontent.com/86437155/207181597-54cd8c64-f203-4af2-b485-6bae21eed061.png)

This is the full list of libraries imported:

![Screen Shot 2022-12-12 at 3 29 07 PM](https://user-images.githubusercontent.com/86437155/207181774-94b1bea6-502a-4a2d-ac4d-708421aca9b9.png)

After that, you should see this warning and follow the steps further:

![Screen Shot 2022-12-12 at 3 32 37 PM](https://user-images.githubusercontent.com/86437155/207182246-735d6c0b-021d-45a2-b1fd-9be4b2e424a8.png)

If the above steps don't help, please feel free to re-open the ticket.
