### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by Aleubyn** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#121]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2

**In which task and step of the codelab can this issue be found?**
Third step of the Practice: Compose Basics . The UI specification and the answer for the Task Manager exercise

**Describe the problem**
On the second specification of the task, it says that the first Text composable should be 24sp font size but the answer don't have. Also on the screenshot, the first Text composable font weight is in Bold(the answer also shows it is in Bold) but it is not mentioned on the required UI specification.

Link for the answer:
https://github.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/blob/main/Unit%201/Pathway%203/TaskCompleted/app/src/main/java/com/example/taskcompleted/MainActivity.kt
 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![a](https://user-images.githubusercontent.com/87900058/204708605-5148b17a-e85c-469f-a6b4-f6647645a4ae.png)

**Comment by osuleymanova** [comment]
Hello @Aleubyn,

Thank you for reaching out to us and reporting this missing UI specification. It is updated:

![Screenshot 2023-01-11 at 12 47 18 PM](https://user-images.githubusercontent.com/86437155/211914729-4fe04d73-97c9-4eb2-9251-bd9fdc27756f.png)
