### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by mohsincrt** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#122]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#3**

** "passing in the Image() composable function " after Step 3 in (4. Add an Image composable) ** 

**Android Studio displays an error that says that, "None of the following functions can be called with the arguments supplied" the arguments don't match the function. You can see the error when you hover over the Image composable. The reason for this error is that the arguments you are passing in the Image() composable function are not sufficient and do not match the function signature. In the next step, you fix the error.
              But in, next step there is no solution shown for this**

**Steps to reproduce?**
1. Visit the link at the top mentioned
2. Click on 4. Add an Image composable
3. Scroll down to step 3 "Android Studio displays an error that says that"

**Comment by android-dev-lxl** [comment]
Hi @mohsincrt 
Thank you reaching out to us!
In the next step, you add the contentDescription to resolve this issue.
Did you try adding it?

![image](https://user-images.githubusercontent.com/24260141/212242369-30e0c32a-569b-4a86-91b1-0410dc3c36b1.png)

**Comment by osuleymanova** [comment]
@mohsincrt,

Closing this issue, since there is no response. 
Hope the issue was resolved thanks to the steps provided in the comment above. 
Please create a new one, if you still need any help.
