### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by shmooth** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#123]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4

**In which task and step of the codelab can this issue be found?**

String > 5.

**Describe the problem**

This quoted text should have a space at the beginning:

> Use the + symbol to add the string literal "at work" to the end of the reminder string.

**Comment by osuleymanova** [comment]
Hello @shmooth,

Thanks for reaching out and sharing your feedback. A space is not required, as this sentence is consistent with the others:

![Screen Shot 2022-12-13 at 10 40 33 AM](https://user-images.githubusercontent.com/86437155/207418843-840adb96-da96-4643-9ff1-abca65ff1c68.png)

**Comment by shmooth** [comment]
weird, you right, i must've got confused, thanks.
