### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#124]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

text two of "Task App" has no font size specified in Solution/Image, 
although the assignment wants it

**Comment by android-dev-lxl** [comment]
@folsze 
Thank you for reaching out to us!
For the text one, **All Tasks completed** no need to set the font size, Text composable uses the default font size. 
For the text two, **Nice Work!** please use `16sp` as mentioned. 

<img width="694" alt="image" src="https://user-images.githubusercontent.com/24260141/212445006-65f4c4f7-fc30-4b15-b394-bd600aac0c14.png">
