### ISSUE TITLE
Text composables: Android Basics with Compose (Preview Composable function name is inconsistent)

### ISSUE THREAD

**Issue by michaelssim** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#13]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables)**

**In which task and step of the codelab can this issue be found?**
5. Design pane in Android Studio

**Describe the problem**
It's confusing to the learner when the name of the Preview Composable function is inconsistent. By default, the name is `DefaultPreview`. That's what's show in the image used by the codelab. Yet in the code block, it keeps referring to `BirthdayCardPreview()`. Ideally, these two should match so it is consistent.

**Additional information**
Here's the screen shot of the inconsistencies (function name mismatch):

![image](https://user-images.githubusercontent.com/81500505/169635917-22bfb0fd-addf-4b39-84dd-dd456da86db2.png)

![image](https://user-images.githubusercontent.com/81500505/169635924-f8c0156c-5921-448d-9d50-57053aad79d0.png)

**Comment by osuleymanova** [comment]
Hello @michaelssim,

Thank you for reaching out to us and reporting this issue. It is fixed:

![Screenshot 2023-01-06 at 3 59 32 PM](https://user-images.githubusercontent.com/86437155/211119338-536cc2a3-afd8-4e3b-bc49-9a95345c9480.png)
