### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by Bronek777** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#133]
[**URL of codelab**]
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems

(https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems&hl=en#3)

**In which task and step of the codelab can this issue be found?**
Practice: Compose Basics
4. Compose quadrant

**Describe the problem**
in these tasks I have a problem with proper compose of the four colored blocks.
I do proper task but my results have a strange issue. all blocks have a white border around.

![image](https://user-images.githubusercontent.com/16881959/208771396-91efb690-1eaa-4ca5-87a4-78c940d5a557.png)

I make a compare with solution and i have same steps in my code but results quite different.
after changes and few test i found solution.
order of applied modifiers are clue. i add padding first and after that others color etc. :)
when padding is last one everything is ok like in codelab.

i have also problems with apply modifier weight. I think will be nice when you describe more this topic because after reading a links included in task I not get it proper. In solution you add a fourth parameter with Modifier class and change it in lower parts of code. for beginners i think is a hard to understand that approach.

regards
Sebastian

**Comment by android-dev-lxl** [comment]
@Bronek777 
Could you please give us your before and after code.

**Comment by osuleymanova** [comment]
Hello @Bronek777 ,

Closing this issue, since there is no response. 
Please create a new one, if you still need any help.
