### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by dattasubham** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#134]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1)

[2. Compose article](https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1)

[**Describe the problem**](https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/main/Unit%201/Pathway%203/ComposeArticle/app/src/main/res/drawable-nodpi/bg_compose_background.png) not downloading

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@dattasubham 

Do you have access to the GitHub repo?
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app

Image is in the repo.

https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/24260141/211480740-4b36a407-aad3-4757-b8b9-9dac7b69009a.png">


If you are still facing issues downloading,  please do the following and check again? 

Could you please add Google Public DNS to the DNS servers list. 
8.8.8.8 and/or 8.8.4.4

[Instructions on MAC to configure DNS server
](https://support.apple.com/en-in/guide/mac-help/mh14127/mac#:~:text=To%20change%20these%20settings%2C%20choose,may%20need%20to%20scroll%20down&text=List%20of%20DNS%20servers)

[Instructions for Windows to configure DNS server](https://developers.google.com/speed/public-dns/docs/using#windows)

**Comment by osuleymanova** [comment]
Hello @dattasubham,

Closing this issue, since there is no response. 
Hope the issue was resolved thanks to the steps given in the comment above. 
Please create a new one if you still need any help.
