### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by HariPrasadSala** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#135]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**
Set up your app

**Describe the problem**
In the page section "Add an image to your project". I am unable to download the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png).

**Steps to reproduce?**
1. Go to "Set up your app" section.
2. Click on the birthday card app image link
3. Unable to download the image from GitHub.

**Additional information**
![image](https://user-images.githubusercontent.com/26438695/209423693-dd7d99ed-d74d-43b6-9d3c-96b6c20c729a.png)

**Comment by android-dev-lxl** [comment]
@HariPrasadSala 
The link seems to be working fine. Could you please check once again.

**Comment by HariPrasadSala** [comment]
Still the same, not able to access the link above.

Have completed learning with alternative image files in online...

**Comment by android-dev-lxl** [comment]
@HariPrasadSala 
Do you have access to the GitHub repo?
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app

Image is in the repo.

https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/24260141/211480740-4b36a407-aad3-4757-b8b9-9dac7b69009a.png">

**Comment by HariPrasadSala** [comment]
Yes I am able to access the repo but unable to download the image...

**Comment by android-dev-lxl** [comment]
@HariPrasadSala 
![image](https://user-images.githubusercontent.com/24260141/211482141-b8b42a06-0273-49e6-99cd-106584bf17a2.png)

What happens when you click the download button?

**Comment by HariPrasadSala** [comment]
File is not downloading, since service is taking too long to respond. It's
same when I access the link from laptop.

PFA for your reference
  Record_2023-01-10-12-40-30.mp4
<https://drive.google.com/file/d/1DmxAc7XmoMwtlbrh6FCEcSRTglrKV_gL/view?usp=drivesdk>

**Comment by android-dev-lxl** [comment]
@HariPrasadSala 
Could you please add Google Public DNS to the DNS servers list. 
8.8.8.8 and/or 8.8.4.4

[Instructions on MAC to configure DNS server
](https://support.apple.com/en-in/guide/mac-help/mh14127/mac#:~:text=To%20change%20these%20settings%2C%20choose,may%20need%20to%20scroll%20down&text=List%20of%20DNS%20servers)

[Instructions for Windows to configure DNS server](https://developers.google.com/speed/public-dns/docs/using#windows)

**Comment by HariPrasadSala** [comment]
Once the DNS1 and DNS2 is set to 8.8.8.8 and 8.8.4.4. I am able to download
the image from GitHub. Thanks !!!
