### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by joelpeyton** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#136]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images

**In which task and step of the codelab can this issue be found?**
Task 8. Adopt good code practices
Step 4

**Describe the problem**
After extracting resource, the code is replaced with 

`getString(R.string.happy_birthday_text)`

rather than 

`stringResource(id = R.string.happy_birthday_text)`

Noticed that if I then tried to use `getString()` in the Preview composable I would need to import it, which would then cause further errors.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0

_API version of the emulator:_ 

**Additional information**

**Comment by android-dev-lxl** [comment]
Hi @joelpeyton 
Thanks for reaching out to us. 
Extracting a string resource should result in `stringResource()` not `getString()`

https://user-images.githubusercontent.com/24260141/212182447-91496e9c-9b80-4115-8512-d64e233754df.mov
