### ISSUE TITLE
Practice problems: Android Basics in Compose

### ISSUE THREAD

**Issue by ttecster** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#14]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#6

**In which task and step of the codelab can this issue be found?**
7 - Implement basic math operations.

**Describe the problem**

fun main() {
    val firstNumber = 10
    val secondNumber = 5
    val thirdNumber = 8
    
    val result = add(firstNumber, secondNumber)
    val anotherResult = add(firstNumber, thirdNumber)

    println("$firstNumber + $secondNumber = $result")
    println("$firstNumber + $thirdNumber = $anotherResult")
}

// Define add() function below this line

"Can you define the add() function so that the program prints this output? "
10 + 5 = 15
10 + 8 = 18

The solution doesn't show how to print out the sum of firstNumber + thirdNumber , and when I add the third parameter thirdNumber it says value is not passed, can you please show a solution for the question?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ttecster 
Thank you for reaching out to us. Recently we updated the content in the Solution code section. Hopefully it clarifies your concern:

![Screen Shot 2022-07-27 at 11 59 05 AM](https://user-images.githubusercontent.com/86437155/181351158-6f2b6540-356b-413a-b1e4-0ea872eb5191.png)

You may also check the solution code there: <iframe src="https://pl.kotl.in/M1u1Y-Y6H"></iframe>
