### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by greatn8** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#140]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Watch the code-along video.

**Describe the problem**
in the code along video this line was used:
val image = painterResource(id = drawable.androidparty)

but it doesn't work and should have been:
val image = painterResource(R.drawable.androidparty)

this caused me to get stuck on the error while coding along.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@greatn8 
Thank you for approaching us.
In the code-along video also we are using the right code.
` val image = painterResource(id = R.drawable.androidparty)
`<img width="950" alt="image" src="https://user-images.githubusercontent.com/24260141/211088743-5b0cc6c8-642a-491e-9c17-ddca7322ac7a.png">

Android studio auto-imported `import com.example.happybirthday.R.drawable` automatically.
