### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by greatn8** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#141]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
Render problem

@Composable
fun BirthdayGreetingWithImage(message: String, from: String) {
    Box {
        val image = painterResource(id = R.drawable.androidparty)
        Image(painter = image, contentDescription = null, modifier = Modifier
            .fillMaxHeight()
            .fillMaxWidth(), contentScale = ContentScale.Crop)
        BirthdayGreetingWithText(message = "Happy Birthday Xin", from = "Nathan")
    }
}

gives in preview:

java.lang.NullPointerException: Parameter specified as non-null is null: method com.example.birthdaycard.MainActivityKt.BirthdayGreetingWithImage, parameter message console says that message: and from: is never used after completing the codelab 

fun BirthdayGreetingWithImage(message: String?, from: String?) 
makes everything work at the end of codelab.

**Versions**
_Android Studio version:_  Android Studio Dolphin | 2021.3.1 Patch 
_API version of the emulator:_ 21

**Additional information**
![image](https://user-images.githubusercontent.com/7834850/211014964-66b89ce8-7717-4f71-b4d6-6c69fa2bc0d4.png)

**Comment by Sparcte** [comment]
Thanks !!!

Le ven. 6 janv. 2023 à 13:45, Nathan Shorter ***@***.***> a
écrit :

**Comment by android-dev-lxl** [comment]
Hi @greatn8 
Thank you for reaching out to us.
Please make sure to use the `from` and `message` variables in the function as shown below. 
        `BirthdayGreetingWithText(message = message, from = from)`


Also please check if the preview function matches the below function.


```
@Composable
fun BirthdayGreetingWithImage(message: String, from: String) {
    val image = painterResource(R.drawable.androidparty)
    // Create a box to overlap image and texts
    Box {
        Image(
            painter = image,
            contentDescription = null,
            modifier = Modifier
                .fillMaxHeight()
                .fillMaxWidth(),
            contentScale = ContentScale.Crop
        )
        BirthdayGreetingWithText(message = message, from = from)
    }
}

@Preview(showBackground = false)
@Composable
private fun BirthdayCardPreview() {
    HappyBirthdayTheme {
        BirthdayGreetingWithImage( stringResource(R.string.happy_birthday_text),
            stringResource(R.string.signature_text))
    }
}
```

**Comment by osuleymanova** [comment]
@greatn8,
 
Closing this issue as resolved, since there is no response.
Please create a new one, if you need help.
