### ISSUE TITLE
Your course Kotlin (Introduction to programming in Kotlin  |  Android Basics Compose - First Android app  |  Android Developers)

### ISSUE THREAD

**Issue by mainze1** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#144]
Hi, 

I find this course great. For an absolute beginner like me in programming with Kotlin it is all confusing. I had even troubles to come back to the course in the internet. Maybe it is a bit more table of contents is possible. But as I said I find the course great. I have one question to this site 

(https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#7).

I can't understand what is the coding under "2. Replace the main() function implementation with this one:" good for. I can't understand the sense. There is also no solution denoted. 

Please inform me. 

Regards, mainze1 from Germany

**Comment by android-dev-lxl** [comment]
@mainze1 
Thank you for reaching out to us. 
That instruction is follow up instruction to the step1.  These are the updated instructions.

To print this output message: 
```

There's a new sign-in request on Unknown OS for your Google Account user_one@gmail.com.

There's a new sign-in request on Windows for your Google Account user_two@gmail.com. 

There's a new sign-in request on Mac OS for your Google Account user_three@gmail.com. 
```

Use this code:
```

fun main() {
    val firstUserEmailId = "user_one@gmail.com"


    // The following line of code assumes that you named your parameter as emailId. 
    // If you named it differently, feel free to update the name.
    println(displayAlertMessage(emailId = firstUserEmailId))
    println()


    val secondUserOperatingSystem = "Windows"
    val secondUserEmailId = "user_two@gmail.com"


    println(displayAlertMessage(secondUserOperatingSystem, secondUserEmailId))
    println()


    val thirdUserOperatingSystem = "Mac OS"
    val thirdUserEmailId = "user_three@gmail.com"


    println(displayAlertMessage(thirdUserOperatingSystem, thirdUserEmailId))
    println()
}
```


<img width="790" alt="image" src="https://user-images.githubusercontent.com/24260141/216460052-b2017eb2-2213-4b47-801d-44c9a9983202.png">

Hope this was helpful.
Updated instructions to be published.
