### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by DrPlanecraft** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#145]
[**URL of codelab**]
(https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6)

**In which task and step of the codelab can this issue be found?**
7. Align the text and add padding

**Describe the problem**

**Steps to reproduce?**
1. Open Android Studio
2. Add the Text Objects
3. Text(
                text = message,
                fontSize = 20.sp,
                color = Color.White,
                Modifier=Modifier.wrapContentWidth(Alignment.Start)
            )

and

Text(
                text = "- $from",
                fontSize = 15.sp,
                color = Color.White,
                fontStyle = FontStyle(1),
                Modifier=Modifier.fillMaxWidth()
            )

4. See error...
e: C:\Users\DrPlanecraft\OneDrive\Documents\LI ZHUOXI\ITE- College West\Lessons\Mobile Application Programming\BirthdayCard\app\src\main\java\com\example\birthdaycard\MainActivity.kt: (57, 13): None of the following functions can be called with the arguments supplied: 
public fun Text(text: AnnotatedString, modifier: Modifier = ..., color: Color = ..., fontSize: TextUnit = ..., fontStyle: FontStyle? = ..., fontWeight: FontWeight? = ..., fontFamily: FontFamily? = ..., letterSpacing: TextUnit = ..., textDecoration: TextDecoration? = ..., textAlign: TextAlign? = ..., lineHeight: TextUnit = ..., overflow: TextOverflow = ..., softWrap: Boolean = ..., maxLines: Int = ..., inlineContent: Map<String, InlineTextContent> = ..., onTextLayout: (TextLayoutResult) -> Unit = ..., style: TextStyle = ...): Unit defined in androidx.compose.material
public fun Text(text: String, modifier: Modifier = ..., color: Color = ..., fontSize: TextUnit = ..., fontStyle: FontStyle? = ..., fontWeight: FontWeight? = ..., fontFamily: FontFamily? = ..., letterSpacing: TextUnit = ..., textDecoration: TextDecoration? = ..., textAlign: TextAlign? = ..., lineHeight: TextUnit = ..., overflow: TextOverflow = ..., softWrap: Boolean = ..., maxLines: Int = ..., onTextLayout: (TextLayoutResult) -> Unit = ..., style: TextStyle = ...): Unit defined in androidx.compose.material

![image](https://user-images.githubusercontent.com/64484413/211715118-cebabf61-b07b-4742-8922-1f04163d2d95.png)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
![image](https://user-images.githubusercontent.com/64484413/211715278-d5bf4b05-5389-41e5-b486-88a9f34b362b.png)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
@Composable
fun BirthdayGreetingWithText(message: String="Android", from:String="A Developer") {
    Surface(modifier = Modifier.padding(0.dp).background(color = Color.DarkGray)) {

        Column() {
            Text(
                text = message,
                fontSize = 20.sp,
                color = Color.White,
                Modifier=Modifier.wrapContentWidth(Alignment.Start)
            )

            Text(
                text = "- $from",
                fontSize = 15.sp,
                color = Color.White,
                fontStyle = FontStyle(1),
                Modifier=Modifier.fillMaxWidth()
            )
        }

    }
}

**Comment by johnshea** [comment]
Hi.

The parameter is named "modifier" not "Modifier". It starts with a lower case "m".

Please change your code from:
`Modifier=Modifier.wrapContentWidth(Alignment.Start)` to `modifier=Modifier.wrapContentWidth(Alignment.Start)`
and
`Modifier=Modifier.fillMaxWidth()` to `modifier=Modifier.fillMaxWidth()`

If you are still having problems, please create a new issue.

Hope you are enjoying the course!

Regards.
