### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by philix615** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#147]
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-text-composables?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#6

![image](https://user-images.githubusercontent.com/110101595/212061986-ccc52744-29ca-4da7-a014-5051cdcad845.png)
![image](https://user-images.githubusercontent.com/110101595/212062069-64980c8c-2437-4d4b-909e-7410e826fd5d.png)
The project's name is 'Hello_wrold'

**Describe the problem**

![image](https://user-images.githubusercontent.com/110101595/212062270-5800a2c3-2674-4cd6-881a-a8fe2240e595.png)

**Versions**
android-studio-2021.3.1.17-windows

**Comment by android-dev-lxl** [comment]
@philix615 
Thank you for reaching out to us.
Could you please check your module level gradle file, `build.gradle (Module: HappyBirthday.app)` for the following imports:
```
    implementation 'androidx.activity:activity-compose:1.6.1'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.activity:activity-compose:1.6.1'
```
Could you also make sure to sync project files once you update gradle file?

![image](https://user-images.githubusercontent.com/24260141/212187791-294d6d84-1966-4ef6-bbd5-2fcc17facd01.png)
