### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by troycura** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#149]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#2

**In which task and step of the codelab can this issue be found?**
Number 2 - Create a Happy Birthday Card

**Describe the problem**

I encountered an issue for Kotlin 1.7.1
jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

This is in Android Studio.
- After selecting empty compose project
- It download and update gradle automatically

Found Fixes but it did not work...

1. remove gradle cache

2. build.gradle - project
ext {
        compose_version = '1.0.1'
        kotlinVersion = "1.7.0"
    }

3. build.gradle - module
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id("org.jetbrains.dokka") version ("1.6.20") apply false

}

Can anybody send a work around on how to fix this with Kotlin 1.7.1 it seems that its looking for older version...

**Comment by android-dev-lxl** [comment]
@troycura 
Thank you for reaching out to us.
Could you update your Android Studio to Electric eel and check please!

**Comment by osuleymanova** [comment]
@troycura,

Closing this issue, since there is no response.
Please create a new one, if you need help.
