### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by dendude** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
smartLightDevice.increaseBrightNess()
but it was wrote above as
smartLightDevice.increaseBrightness()

**Comment by osuleymanova** [comment]
@dendude 
The issue that you presented to us is very important, and I thank you for bringing it to our attention. The correct variant `smartLightDevice.increaseBrightness()` will be published soon.
