### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by maimoy** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#150]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1

**In which task and step of the codelab can this issue be found?**

[2. Compose article](https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1)

**Describe the problem**

the link for 
References
[TextAlign.Justify](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/TextAlign.Companion#Justify()) property

display an error

Sorry, we couldn't find that page.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @maimoy,

The broken link issue that you presented to us is extremely important, and I thank you for bringing it to our attention. It is fixed.
