### ISSUE TITLE
Add images: TextAlign.justify() page not found

### ISSUE THREAD

**Issue by iammasoodalam** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#151]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1

**In which task and step of the codelab can this issue be found?**
TextAlign.justify property under the References at the bottom of the page

**Describe the problem**
When I clicked on TextAligh.justify link it returned an error of 404.

![Screenshot 2023-01-14 014517](https://user-images.githubusercontent.com/54001173/212411227-a41389b5-88af-4f71-a019-09d0f1a5ed9a.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @iammasoodalam,

Thank you so much for reporting this issue. The broken link is fixed.
