### ISSUE TITLE
Text composables: Refactor BirthdayGreetingWithText

### ISSUE THREAD

**Issue by jameynakama** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#153]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#5

**In which task and step of the codelab can this issue be found?**

Step 6: Add a new text element

**Describe the problem**

On _Step 4: What is Jetpack Compose?_, one of the naming conventions for Composables is "NOT a nouned preposition: TextFieldWithLink", and 2 pages later, the lesson tells you to use a `BirthdayGreetingWithText` Composable in your app.

**Comment by PennRobotics** [comment]
Dupe #109

**Comment by osuleymanova** [comment]
Hello @jameynakama,

Thank you for reaching out to us. The composable function name is fixed and will be published soon:

![Screenshot 2023-04-13 at 3 43 17 PM](https://user-images.githubusercontent.com/86437155/231899338-4646ef96-311d-414a-b1c7-7f068315823a.png)

Happy Android learning!
