### ISSUE TITLE
Add images: import androidx.compose.foundation.Image 

### ISSUE THREAD

**Issue by JustinKirton** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#156]
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#4

Task 4: 
Add an image composable

Synopsis of problem:
I am new to Kotlin but am determined to overcome the difficulties I've been experiencing.  Having followed each step, (religiously), I have come to a point in the codelab when I am asked to add an image.

I downloaded the image (recommended by the codelab), & saved  it into the Resource Manager.  I then added the code as requested. I always get the same error. I have spent a couple of days searching You Tube and other places to see if other people have encountered the same issue. I can't believe there are no other instances of my problem, since I am sure I have followed the instructions 'to the letter'.

I (also) believe that my efforts could have possibly caused further issues & decided to uninstall the whole software, deleting all the files and rebooting so that no trace of android Studio (or the files it had already generated) were present.  

I then re-installed the software, again following all the steps, only to come up against the exact same problem. See lines 54 - 57 (Image 1)

The Error Message(s) are identical on each of my attempts (Image 2)

Versions:
Android Studio version:  Dolphin 2021.1.3.1.17-windows
API version of the emulator: 31 

![2023-01-17CodingIssueKotlin](https://user-images.githubusercontent.com/122461765/212874871-38bcdb4c-2592-47e7-9898-d435b30177c5.png)

![2023-01-17 Detail](https://user-images.githubusercontent.com/122461765/212873366-521b4675-4b8c-43bc-a412-c11e04d1de40.png),

**Comment by android-dev-lxl** [comment]
@JustinKirton 
Thank you for reaching out to us.
We are glad that you are determined to resolve this issue.
Could you please send us the entire file? 
I wanted to know if you have the right import. 

Thank you!

**Comment by Eddi101** [comment]
Hello, i had the same issue, [alt+enter to import on "Image"] does not have an option for the appropriate import.
The correct import according to the solution file is as follows:

import androidx.compose.foundation.Image

I would suggest adding to the guide.

**Comment by JustinKirton** [comment]
I have created a branch. I don't know of this is the correct way of linking it to this thread. I'm "You Tubing" my way around Github right now. I have much to learn! 

https://github.com/JustinKirton/issuesWithBirthdayCardTutorial.git

**Comment by android-dev-lxl** [comment]
@JustinKirton 
To attach the file just drag and drop the file in to the comment box. 
In the mean time try the following steps:

> To fix the error, please include the following import, at the top of your MainActivity.kt file:
> 
> `import androidx.compose.foundation.Image`



@Eddi101 
Thanks for the suggestion.
Fixed and to be published.

**Comment by AC-DB** [comment]
您好，我也遇到此错误，我添加了对应的 `import androidx.compose.foundation.Image` 引入但是此行引入是灰色状态，并且错误依旧存在，请帮帮我
