### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by fufferpish** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#158]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#0

**In which task and step of the codelab can this issue be found?**
3

**Describe the problem**

It tells you to use a non-existant feature, "Split."

**Steps to reproduce?**
1. Go to android studio
2. Create what it says to
3. See that the "Split" button does not exist 🤯

**Versions**
_Android Studio version: Electric Eel
_API version of the emulator: No emulator

**Additional information**
_Include screenshots if they would be useful in clarifying the problem.

**Comment by android-dev-lxl** [comment]
@fufferpish 
Thank you for reaching out to us!
Which file are you on. 
Could also please send us a screenshot of your Android Studio?

**Comment by osuleymanova** [comment]
Hello @dattasubham,

Closing this issue, since there is no response. 
Please create a new one, if you still need any help.
