### ISSUE TITLE
Your first program: Android Basics with Compose

### ISSUE THREAD

**Issue by psabadac** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#160]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
11 Conclusion task

**Describe the problem**

Always 1 min remaining, unable to complete the lab and get the badge.

**Steps to reproduce?**
1. Go to any codelab
2. Complete all steps
3. On the final step, you should be able to finalize the codelab.

**Versions**
_Android Studio version:_  NA
_API version of the emulator:_ NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by psabadac** [comment]
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?hl=en#10

**Comment by psabadac** [comment]
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=en#7

**Comment by osuleymanova** [comment]
Hello @psabadac,

Thank you for reaching out and sharing your concern.
The estimated reading time for the Conclusion section in the most of codelabs is 1 minute, but no worries, you may take as much time as you needed. Please refer to our notice in the Introduction codelab:

![Screenshot 2023-01-23 at 9 54 49 AM](https://user-images.githubusercontent.com/86437155/214115866-7316dd40-735b-4d0b-a1ff-56044a663e8a.png)

**Comment by osuleymanova** [comment]
@psabadac,

The Pathway 1 Introduction to Kotlin consists of 2 videos, 4 codelabs and 1 quiz. After completing all these activities ( not after each codelab) you can get 1 badge per Pathway:

![Screenshot 2023-01-23 at 3 03 31 PM](https://user-images.githubusercontent.com/86437155/214172874-1e87639e-c063-40bb-8e29-3ddb105ac893.png)

Hope it clarifies why you earned 1 badge only.

**Comment by psabadac** [comment]
Thanks for the clarifications!
