### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by mikey199** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#162]
None of this shit works and nothing gets explained..............ugh . im going to apple

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@mikey199 
Thank you for reaching out to us. 
Do you want to explain what seems to be the issue.

**Comment by osuleymanova** [comment]
@mikey199,

Closing this issue, since there is no issue description.
Please create a new one, if you need help.
