### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by eiliftanberg** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#163]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4

**In which task and step of the codelab can this issue be found?**
Step 5, "Create and use variables in Kotlin"

**Describe the problem**
Space is missing in string example
"Use the + symbol to add the string literal **"at work"** to the end of the reminder string."
should be
"Use the + symbol to add the string literal **" at work"** to the end of the reminder string."
to match output in sixth step under **String** headline

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @eiliftanberg,

Good catch! Updated and be published soon.
