### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Rnscd** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#164]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

7

**Describe the problem**

Not a code problem. But very confusing wording. It says that, "However, in Kotlin, all the classes are final, which means that you can't extend them, so you have to define the relationships between them."
And later, "The open keyword informs the compiler that this class is extendable, so now other classes can extend it."

I'm new to Kotlin, but so are the people taking this codelab, and it looks contradicting to a newbie like me.
A rewrite that would make sense to me would be, "However, in Kotlin, all the classes are final, which means that you can't extend them [by default] [...]"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
Thank you for reaching out to us.
To be published.
