### ISSUE TITLE
Build a basic layout (4. Add images to your Android app): Alignment.CenterHorizontally link 404 error

### ISSUE THREAD

**Issue by zerexei** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#165]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#8

**In which task and step of the codelab can this issue be found?**
1. click "Here's a hint: Use the `Alignment.CenterHorizontally` argument with the wrapContentWidth() function."
2. Sorry, we couldn't find that page. 

**Describe the problem**
broken link
https://developer.android.com/reference/kotlin/androidx/compose/ui/Alignment.Companion?authuser=1#CenterHorizontally()

**Steps to reproduce?**
1. go to URL of codelab above
2. click "Here's a hint: Use the `Alignment.CenterHorizontally` argument with the wrapContentWidth() function."
3.see  Sorry, we couldn't find that page. 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/69749146/215253739-5858bef2-b23b-4d76-abbe-ade5a122270f.png)
![image](https://user-images.githubusercontent.com/69749146/215253761-0b1f9367-8605-40a2-8816-2fa9157bee80.png)

**Comment by osuleymanova** [comment]
Hello @zerexei,

The broken link issue that you presented to us is extremely important, and I thank you for bringing it to our attention. It will be fixed and republished soon.
