### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by PrinceHassssoooon** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#169]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2

**In which task and step of the codelab can this issue be found?**

3, under the Unit type

**Describe the problem**

Copying and pasting the code (code below) in kotlin playground shows an error message (error message below), while the page tells me that the code should work just fine

Code 

fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}

Error message

No main method found in project.

**Steps to reproduce?**
1. Go to... link above
2. Copy code, paste in kotlin playground, run code
3. See error...

**Versions**
Kotlin playground Last updated 2021-08-17 UTC.

https://developer.android.com/training/kotlinplayground

**Additional information**

I thought something might be out of place but nothing was, all the symbols and spaces were correct. the only thing that fixed this problem for me was to change the name of the function from (birthdayGreeting) to (main) which is weird.

**Comment by johnshea** [comment]
Hi @PrinceHassssoooon 

Thank you for letting us know of your issue.

The instructions in this step are a continuation of the previous step. The code will not work as-is by copying and pasting the birthdayGreeting() function.

Please review [Create and use functions in Kotlin - Step 2 Define and call a function](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions) to see how the Kotlin Playgroudn should be setup.

```
fun main() {
    birthdayGreeting()
}

fun birthdayGreeting() {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}
```

Hope you are enjoying the course!

Regards.
