### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by cv127001** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#170]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Step 7

**Describe the problem**
wrong top menu
Replace "...To do this press Help ..."
With "... To do this press Code ..."

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@cv127001 
Thank you for reaching out to us. 
Could you please provide us with the name or link to the codelab you are referring to.

**Comment by android-dev-lxl** [comment]
@cv127001 
As there has been no response for the past two weeks, we are closing the issue. 
Please open a new ticket if you need further assistance.
