### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by pjd3** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#171]
**URL of codelab**
https://developer.android.com/training/kotlinplayground

**In which task and step of the codelab can this issue be found?**
val count = 2

The Kotlin compiler knows that you want to store 2 (a whole number integer) into the variable count, so it can infer that the count variable is of type Int. Convenient, right? This is one example of how writing Kotlin code is more concise!

**Describe the problem**

Not a problem exactly. apparently the Playground parser is limited.  In the tutorial -see above info,  but the playground can't handle that;
fun main() {
fun main() {
 val count: = 2 -------------------- THIS DOESN:T work in Plauground
    val banana: String = "banana"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @pjd3.

The issue is actually with your code.

You need to remove the ":".

Change...
`val count: = 2`
to
`val count = 2`

The Kotlin Playground should now work as expected.

Sounds like you are enjoying the course.

Regards.
