### ISSUE TITLE
First Android app: Android Basics Settings

### ISSUE THREAD

**Issue by nestaho833** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#180]
![image](https://user-images.githubusercontent.com/96278163/218091729-a522a05d-41bf-4beb-8484-e3084c630001.png)
**Android Studio Settings**
[ANDROID PROBLEM.txt](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/files/10707369/ANDROID.PROBLEM.txt)

**I am a beginner and just started to use android studio**

**I can't see the "Preview"**

**Versions**
_Android Studio version:_ Android Studio Flamingo 2022.2.1 Beta 1
[](url)

Please help :)

**Comment by android-dev-lxl** [comment]
@nestaho833 
Thank you for reaching out to us. 

Could you please build and run the app.
Let us know if it is still an issue.

**Comment by osuleymanova** [comment]
@nestaho833

Closing this issue, since there is no response back.
Please create a new one, if you need help.
All the best learning Android.
