### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by cayrol272** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#181]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**
I think this codelab using older version. My Android Studio version Chipmunk 2021.2.1 Patch 1. 
@Composable was error in my version, unresolved reference. Please assist?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version: Chipmunk 2021.2.1 Patch 1.  
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by cayrol272** [comment]
Issue solved. I choosing wrong template.

**Comment by android-dev-lxl** [comment]
@cayrol272 
Glad to know that you have resolved.
