### ISSUE TITLE
Your first program: Android Basics with Compose

### ISSUE THREAD

**Issue by bhminton** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#183]
im new to this 
but the function println( )

doesnt seem to follow the camel case typing you discussed earlier 

shoulndnt it be 

printLn (  )

im a beginner and this threw me off for a second 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@bhminton 
Thank you for reaching out to us. 

The function `println()` is part of Kotlin standard library not Android.
Please take a look at the official documentation: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/println.html

There is another similar function called `readln()` and here is the official documentation: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/println.html

We don't have control over the library functions, we can only name the functions in the source code you own and code.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no response back.
Please create a new one, if you need help.
