### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Vassago212** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#184]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
The methods for turnOn()  & turnOff() for the smartTvDevice & smartLightDevice classes referred to in Section 7 haven't been implemented at this point. Also the parameters for the two classes differ from earlier in the CodeLab:

class SmartTvDevice(deviceName: String, deviceCategory: String) :
    SmartDevice(name = deviceName, category = deviceCategory)

class SmartTvDevice(name: String, category: String) :
    SmartDevice(name = name, category = category)

leading to some confusion, unless I've overlooked something.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Vassago212 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished in the near future.

Hope you are enjoying the course!

Regards.
