### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by adeyyysh** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#185]
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app&hl=en#6

Step 7 (Add Padding)

Using the parameter as Modifier.padding(24.dp) does nothing. Rather it should be Modifier.padding(all = 24.dp).

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by SebastianWozniczka** [comment]
Good morning, it just worked for me, but for the whole subtitle background only after editing the text it worked fine.

![Zrzut ekranu_20230309_171037](https://user-images.githubusercontent.com/49164201/224084951-409ae9a0-2eca-43ef-a58e-abd0be2218f2.png)

![Zrzut ekranu_20230309_171215](https://user-images.githubusercontent.com/49164201/224085065-55584104-5c98-497f-9c60-ecdaef10c9be.png)

![Zrzut ekranu_20230309_171242](https://user-images.githubusercontent.com/49164201/224085112-353fdb12-b078-4062-bb7d-f5282111e04e.png)

**Comment by android-dev-lxl** [comment]
@SebastianWozniczka 
Both code snippets you gave should work the same way. 

Seems like you figured it out. Closing this issue.
