### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by Delfairen** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#187]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4)

5 Update the text

Text references "setContent()" but this is not the same as the code from android studio which is "setContentView()"

**Comment by osuleymanova** [comment]
Hello @Delfairen,
Thank you so much for reaching out to us. It is hard to debug your problem without full description or the screenshot.
Please verify your code matches with the code block in section:
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#4

<img width="786" alt="Screenshot 2023-03-17 at 4 59 17 PM" src="https://user-images.githubusercontent.com/86437155/226071610-b40df5eb-c4e0-443a-ab2b-880f2a910699.png">
If that also does't solve the problem, please zip and share your code.
