### ISSUE TITLE
problem 7 

### ISSUE THREAD

**Issue by bhminton** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#189]
**Describe the problem**
the practice problem #7 requests the value of number 1 plus number 2 
and number one plus number 3 

the solution key only addresses 1 value adding number 1 and number 2 
it doesnt mention how to use make an  add function to produce 2 separate value

**Comment by johnshea** [comment]
Hi @bhminton 

Thank you for writing in with your issue.

The variable names can be anything you choose. The names in the lesson were not meant to indicate they can only be used with number 1 and number 3.

Hope this helps!

Regards.
