### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Tllc** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#191]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=1#5

**In which task and step of the codelab can this issue be found?**
6. Add a new text element](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=1#5)

**Describe the problem**
1) No mention is made that in the Surface function, the modifier needs to be deletated, and only leaving the color.
2) at task 4, it mentions the following: "Before the BirthdayCardPreview() function, add a new function called BirthdayGreetingWithText(). Don't forget to add the @Composable annotation before the function because this will be a compose function emitting a Text composable." - Shouldn't the BirthdayGreetingWithText(). added before the @Preview(showBackground = true) line.
3) Task 6 introduces a Text() Composable, however, errors appear which can be corrected by updating the libraries.
4) Under Preview the function, under task 2 shouldn't the "@Preview(showBackground = false)" line be true, if not it could not update the Design view.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Electric Eel | 2022.2.2 Pathch 1
_API version of the emulator:_ Pixel 6 Pro API 33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Tllc 

Thank you for writing in and bringing these issues to our attention.

The lesson has been updated to address the, and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
