### ISSUE TITLE
Text composables: Android Basics with Compose - setter does not work in main

### ISSUE THREAD

**Issue by developerpeet** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#192]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#4

**In which task and step of the codelab can this issue be found?**
step 5

**Describe the problem**
I define the setter like described:
var speakerVolume = 2
    set(value) {
        if (value in 0..100) {
            field = value
        }
    }
but if I use the setter in main like
smartTvDevice.set(5)
 I get an error message

Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: public inline operator fun kotlin.text.StringBuilder /* = java.lang.StringBuilder */.set(index: Int, value: Char): Unit defined in kotlin.text

I tried as well to define a variable of type Int and set that as well as I defined the type of  speakerVolume : Int
But that did not work neither

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
kotlinplayground from developer.android.com

**Additional information**
class SmartDevice{
    val name = "Android TV"
       
    var speakerVolume = 2
    set(value) {
        if (value in 0..100) {
            field = value
        }
    }
    
    fun turnOn(){
        println("Smart Device $name is turned on with Speaker volume $speakerVolume")
    }
}

fun main() {
    val smartTvDevice = SmartDevice()
    val setVolumeto : Int = 5
    smartTvDevice.turnOn()
    println("This was a message from ${smartTvDevice.name}")
    println("The volume is set to ${smartTvDevice.speakerVolume} and not to $setVolumeto")
    smartTvDevice.set(setVolumeto)
    smartTvDevice.turnOn()
    println("This was a message from ${smartTvDevice.name}")
}

**Comment by developerpeet** [comment]
I learned that the getter and setter are implicit and it does not work to invoke them explicitly.

**Comment by johnshea** [comment]
Hi @developerpeet 

Glad you were able to solve your own issue. That is an important step to learn as a developer.

If you are still experiencing any issues with the course, please do not hesitate to create a new issue.

Hope you are enjoying the course.

Regards.
