### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by sanqure** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#193]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator#2

**In which task and step of the codelab can this issue be found?**
Step#3 Run your App on emulator

**Describe the problem**
I created an AVD with Pixel 5, was able to Download "S" and when i was done and tried running the app on the emulator, it says following Error:
**Running Intel® HAXM installer
'silent_install.bat' is not recognized as an internal or external command,
operable program or batch file.
Intel® HAXM installation failed. To install Intel® HAXM follow the instructions found at: https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows**

**Steps to reproduce?**
1. Go to... Tools > Device Manager > Create Device
2. Click on... Run App button
3. See error... the above

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@sanqure 
Please follow the instructions to install HAXM.
Let us know if still have issues with your emulator.
