### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by Dpr1815** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#195]
Nothing in the doc is replicable. I have an XML file that renders everything, I do not understand how to have the same functions that u have in your doc

**Comment by osuleymanova** [comment]
Hello @Dpr1815,

Thank you for reaching out to us. In order to proceed further please provide the detailed information about what issue you are facing.

**Comment by android-dev-lxl** [comment]
I think you selected a wrong template. 
Please chose compose template. 
Try re-creating the project.
