### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by chafik1234** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#199]
![Capture](https://user-images.githubusercontent.com/126253669/221177149-8d66b4e2-d15f-4341-b497-d17f87bc24f2.PNG)
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?authuser=3&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2

**In which task and step of the codelab can this issue be found?**
return a value from a function
**Describe the problem**
The Unit type
code is wrong

fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}

my output is 
No main method found in project.

**Steps to reproduce?**
![2](https://user-images.githubusercontent.com/126253669/221177643-40393983-7fb4-4ae7-bcb2-e90b0f30623e.PNG)
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if ![Capture](https://user-images.githubusercontent.com/126253669/221177025-852b4798-fbc4-49e8-87d8-a4aba1967722.PNG)would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
Hi @chafik1234 
Thank you for reaching out to us.
Your code block should have a main function as shown below from the previous task. 

```
fun main() {
    val greeting = birthdayGreeting()
}

fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}
```

Try it out and it should work as expected.
