### ISSUE TITLE
subtract function

### ISSUE THREAD

**Issue by Neopi420** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#201]
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

fun main() {
    val firstNumber = 10
    val secondNumber = 5
    val thirdNumber = 8
    
    val result = add(firstNumber, secondNumber)
    val anotherResult = subtract(firstNumber, thirdNumber)

    println("$firstNumber + $secondNumber = $result")
    println("$firstNumber - $thirdNumber = $anotherResult")
}

fun add(firstNumber: Int, secondNumber: Int): Int {
    return firstNumber + secondNumber
}

fun subtract(firstNumber: Int, secondNumber: Int): Int {
    return firstNumber - secondNumber
}

shouldn't it be 
fun subtract(firstNumber: Int, thirdNumber: Int): Int {
        return firstNumber -thirdNumber
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Neopi420** [comment]
![image](https://user-images.githubusercontent.com/109392097/221347989-10e9ff53-5611-43e6-a96c-6ff3cfff331d.png)


just making sure I'm understanding but shouldn't it be thirdNumber instead of secondNumber?

**Comment by android-dev-lxl** [comment]
@Neopi420 
Thank you for reaching out to us.
The parameters in the fucntion definataion can be anything. 

```
fun subtract(firstNumber: Int, secondNumber: Int): Int {
return firstNumber - secondNumber
}
```

the above function can also be 

```
fun subtract(firstOperand: Int, secondOperand: Int): Int {
return firstOperand - secondOperand. // These variables names in the function parameter are only used in the function body.
}
```
The variable names in the function parameter need not match with the function call, there are completely different variables.
