### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by sinh927** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#205]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#7

**In which task and step of the codelab can this issue be found?**
* 8 Adopt good code practices
  * Step.6 Notice the changes in code.

**Describe the problem**
The description says "The hardcoded string is now replaced with a stringResource() function." 
but it is actually "getString() function".

**Versions**
_Android Studio version:_ 
Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="644" alt="image" src="https://user-images.githubusercontent.com/6648716/222610839-a9fe029d-936c-4f64-9260-190686826174.png">
![image](https://user-images.githubusercontent.com/6648716/222610906-ae9786cf-abb9-46ab-8f8a-65758ed3f484.png)
![image](https://user-images.githubusercontent.com/6648716/222610952-895b5148-891b-404a-a2a8-ddbebb3c1461.png)

**Comment by android-dev-lxl** [comment]
@sinh927 
Thank you for reaching out to us.
There is an issue with some of the Android Studio versions. Please change the code to use `stringResource()` function
