### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by TAMILARASAN-D** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#207]
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6

modifier = modifier.fillMaxSize()
In the above code have to make small change(Modifier)as below
modifier = Modifier.fillMaxSize()

**Comment by osuleymanova** [comment]
Hello @TAMILARASAN-D,

Thank you for reaching out to us.
It is a best practice to use the passed in Modifier argument in the root layout of the composable.
Instructions are updated and to be published
