### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by mikerown7087** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#208]
In step 4 of Add Images to Your Android, I am running into a problem.

It indicates to correct the problem of "None of the following functions can be called" by adding "import androidx.compose.foundation.Image". I have addded that and the errors still persist.

I am sure I am missing something easy, but cannot find it.

**Versions**
Android Studio Elecric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 16, 2023

![ScreenShot](https://user-images.githubusercontent.com/126905511/222793832-1d8dff3b-b036-4c71-b0da-6df52ddd3942.png)

Following is the entire code package to this point
---------------
package com.example.happybirthday

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent  //<-----------------
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.sp
import com.example.happybirthday.ui.theme.HappyBirthdayTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HappyBirthdayTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    BirthdayGreetingWithText(message = "Happy Birthday Debbie",
                                             from = "From Mike")
                }
            }
        }
    }
}

@Composable
fun BirthdayGreetingWithText(message: String, from: String) {
    Column{
        Text(
            text = message,
            color = Color.Magenta,
            fontSize = 36.sp
        )
        Text(
            text = from,
            color = Color.Black,
            fontSize = 12.sp
        )
    }
}

@Composable
fun BirthdayGreetingWithImage(mesage: String,
                              from: String,
                              modifier: Modifier = Modifier) {
    val image = painterResource(R.drawable.androidparty)
    Image(                          //<----------
        painter = image       //<----------
    )
}
@Preview(showBackground = true)
@Composable
fun BirthdayCardPreview() {
    HappyBirthdayTheme {
        BirthdayGreetingWithText(message = "Happy Birthday Debbie",
                                 from = "From Mike")
    }
}

**Comment by mikerown7087** [comment]
I did discover that by adding a second argument to Image, namely "contentDescription = null", the error went away. But, without the second argument, the error remained. 

    Image(
        painter = image,
        contentDescription = null // without this line the error remains
    )

**Comment by osuleymanova** [comment]
Hello @mikerown7087,

Thank you for reaching out to us and sharing your concern.

As suggested by @mikerown7087(thanks for your input!)  you need to add another named argument contentDescription and set its value to null:
![Screenshot 2023-04-03 at 4 54 30 PM](https://user-images.githubusercontent.com/86437155/229651699-9fe8247e-a4a1-4f79-b3de-94dd241814a7.png)
 Please refer to the codelab as its content has been recently updated and some instructed steps have been added.
Happy Android learning!
