### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Remi-Lerolle** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#210]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
The sentence
"Les noms des variables doivent être en majuscule et commencer par une lettre minuscule."
Is a wrong translation 
Of
'Variable names should be in camel case and start with a lowercase letter.'

Camel case in french is camelcase not majuscule

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Remi-Lerolle 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
