### ISSUE TITLE
Add images: Android Basics with Compose - No finish button

### ISSUE THREAD

**Issue by maiow** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#213]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images

**In which task and step of the codelab can this issue be found?**
[11. Conclusion](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#10)

**Describe the problem**
No finish button at the end of codelab

**Additional information**
screenshot:
![123](https://user-images.githubusercontent.com/113892176/222988621-3026666f-2d42-4d1e-8b77-ab1e547d4464.jpg)

**Comment by osuleymanova** [comment]
Hello @maiow,

Thanks for reaching out to us and sharing your concern. 
Actually the button "Done" takes place if using the full url path:
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#10.

![Screenshot 2023-03-06 at 5 08 41 PM](https://user-images.githubusercontent.com/86437155/223292993-6019fa24-7b94-4b4a-8a86-c30a813cbbcd.png)
