### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by PeterS-ZH** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#214]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#3

**In which task and step of the codelab can this issue be found?**

[Build a simple app with text composables]

[4. What is Jetpack Compose?] and following...

**Describe the problem**

**Instruction**: Composable function names ... The Compose function:...  **NOT** a nouned preposition: TextFieldWithLink()

**Usage** one step later (and also in the introduction video):

@Composable
fun **BirthdayGreetingWithText**(message: String) {
    Text(
       text = message
    )
}

Contradicting....

**Steps to reproduce?**
Just check the documentation / codelab

**Versions**
(irrelevant)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/127112741/223121277-4de1141d-a90c-44cb-bc89-3a9996381938.png)

![image](https://user-images.githubusercontent.com/127112741/223121488-eb51ac8e-1a63-4399-b1ca-6fe02ab221b0.png)

**Comment by johnshea** [comment]
Hi @PeterS-ZH 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
