### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by suap-dev** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#216]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#2

**In which task and step of the codelab can this issue be found?**
9. Click Split on the top right of Android Studio, this allows you to view both code and design. You can also click Code to view code only or click Design to view design only.

**Describe the problem**
There is no such thing as described and shown in the Android Studio.

**Steps to reproduce?**
I just did all the previous stepps like described in manual and there was no "Split" button.

**Versions**
_Android Studio version:_ 
Android Studio Electric Eel | 2022.1.1 Patch 2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![andr](https://user-images.githubusercontent.com/95355453/224223307-16881c02-26bf-44be-9e2d-e30b313e0f04.jpg)

**Comment by AndrewRowley** [comment]
Did you manage to sort this?

**Comment by suap-dev** [comment]
No, I did not.

Also I wrote the ticket because it's rather for you guys to sort it, not
for me. It's a problem in the course.
-- 
Bartosz Słapa
e-mail: ***@***.***
mobile: (+48) 505 707 827


śr., 15 mar 2023 o 18:27 AndrewRowley ***@***.***> napisał(a):

**Comment by AndrewRowley** [comment]
drop me an email and I will try and help you sort it that way andrew.rowley@outlook and send me a bit more detail with a full screenshot of the entire Android Studio screen.

I don't work for Android Developers, I wish! :)

**Comment by suap-dev** [comment]
Ohhh, I didn't notice that you're not one of them, was quite surprised by
the super informal format and language u used. :D

Is the domain of your e-mail outlook[dot]live[dot]com?


-- 
Bartosz Słapa
e-mail: ***@***.***
mobile: (+48) 505 707 827


śr., 15 mar 2023 o 21:03 AndrewRowley ***@***.***> napisał(a):

**Comment by AndrewRowley** [comment]
Yes, it's my email address


________________________________

**Comment by osuleymanova** [comment]
Hello @suap-dev,

Thank you for reaching out to us and sharing your concern.
As for the screenshot provided, it's not clear if you created an app (and what app?) from the template as described in the previous section:
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#2

Our suggestion is to start all over again from the first steps of creating a project. In case if you still face the issue, please feel free to re-open the ticket.
Happy Android learning!
