### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Laurax64** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#218]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6

**In which task and step of the codelab can this issue be found?**
Task 7, Step 2, Step 3

**Describe the problem**
I think that modifier = modifier.fillMaxSize() should be modifier = Modifier.fillMaxSize() because the goal is to access the method fillMaxSize() from Modifier.

**Versions**
_Android Studio version:_ 
Android Studio Dolphin | 2021.3.1
_API version of the emulator:_ 31

**Comment by johnshea** [comment]
Hi @Laurax64 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
