### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Mr-Starkk** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#219]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4)**

**The issue can be found in the last line of the first paragraph of 5. Functions With Multiple Parameters**

**It's written here that "In this section, you'll modify the greeting so that it also changes based on the dog's age." 
   Since, we're talking about a person in reference to this function. The "dog's" should be replaced by "the person's"
**

**Screenshot included**
![Screenshot from 2023-03-11 11-21-21](https://user-images.githubusercontent.com/82252606/224467580-8600fb8e-41e4-4146-89fb-8610a8cf6e04.png)

**Comment by osuleymanova** [comment]
Hello @Mr-Starkk,

Thank you for reaching out to us. 
This sentence is correct as it primarily refers to dogs in the codelab: Rover and Rex.
