### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by LunarBots** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#22]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables&hl=en#3

**In which task and step of the codelab can this issue be found?**
Part 4: Update Variables
         subsection 5 - expected output box

**Describe the problem**
Typo:
value says: "cartTotal: 20" 
should say: "Total : 20"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@LunarBots 
Thank you for reaching out to us. The ticket will be closed as won't fix: the content of the codelab is correct. Please review the screenshot below for further clarification:

![Screen Shot 2022-07-21 at 2 44 26 PM](https://user-images.githubusercontent.com/86437155/180321847-a4795019-422e-4957-b127-b87749f3e9e9.png)
