### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by nxbita** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#23]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3)

Check your app for accessibility

contentDescription = null >> but always is red line and can'y preview

**Steps to reproduce?**
1. Go to...
![001BB](https://user-images.githubusercontent.com/93174599/170860313-45562cc1-af61-457c-92f9-f19978e8c51d.jpg)

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by nxbita** [comment]
![3](https://user-images.githubusercontent.com/93174599/170860824-a053e180-efae-43ae-a044-3279ab3e8d2b.jpg)
![4](https://user-images.githubusercontent.com/93174599/170860826-b1e8cc67-5231-4119-acab-dd034c027c39.jpg)

now ok

**Comment by osuleymanova** [comment]
@nxbita 
Thank you for reaching out to us. There should be no error message if androidx.compose.foundation.Image is previously imported. Please check the full list of libraries imported:

![Screen Shot 2022-07-27 at 11 33 06 AM](https://user-images.githubusercontent.com/86437155/181348248-30aa3841-06c0-44e4-954e-c2d712bc2ef5.png)
