### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by nintendoit** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#234]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
In step [5. Update the text](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#4) at the task to rebuild the app

**The problem**
According to the tutorial, there should be an icon like ![this image](https://user-images.githubusercontent.com/91181094/226174811-22fa6ccb-4808-40f5-8e94-4e3f18d33146.png) in the top left corner of the design pane.But in android studio, there is no button like this.As seen in the screenshot, the 'Build and Refresh' button is in the right corner.

**Versions**
_Android Studio version:_ Android Studio Electric Eel | 2022.1.1 Patch 2

**Additional information**
_Screenshot_
![image](https://user-images.githubusercontent.com/91181094/226175545-bb61647e-91a7-4381-bd2d-a64deec53b25.png)

**Comment by AndrewRowley** [comment]
Did you manage to sort this out?

**Comment by nintendoit** [comment]
I used the build and refresh (Ctrl + Shift + F5) as shown in the screenshot for this purpose.

**Comment by osuleymanova** [comment]
Hello @nintendoit,

Thank you for reaching out to us and sharing your feedback. The codelab content will be updated soon due to the new UI of the Android Studio version.
