### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Hancss** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#236]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?hl=es_419#4

**In which task and step of the codelab can this issue be found?**
USA CLASES Y OBJETOS EN KOTLIN / Define las propiedades de la clase, Paso 3

**Describe the problem**
En la línea después de la variable smartDevice this is  INCORRECT, smartTvDevice is CORRECT 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @Hancss, 
Thank you for reaching out to us and reporting this typo. It will be fixed and republished soon.
