### ISSUE TITLE
Web profile update issue

### ISSUE THREAD

**Issue by LazzaAU** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#237]
It appears to me that if you sign into the Web tutorial then leave the page open (referring g to via a mobile that is) and go do something else for a short time, then return to the tutorial, it I dicates that your are still logged in, however your developer profile won't update unless you log out then log back in. Can be frustrating if you do x amount of pathways then realise none of them have been recorded. You then have to log out , log in, then go through each pathway and click done.

Happens on all tutorials not just this one

**Comment by AndrewRowley** [comment]
This has happened with me as well

**Comment by android-dev-lxl** [comment]
@LazzaAU 
@AndrewRowley 
Thank you for reporting, we forwarded this issue to the concerned team.
