### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ghost** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#241]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1

**In which task and step of the codelab can this issue be found?**
2. Compose article

**Describe the problem**
_**"In this exercise, you build a screen for the app, which displays a tutorial for Jetpack Compose. You use the image and string resources provided in the Resources section for this problem."**_ Slightly unsure what is meant by "**You use the string resources provided in the Resources section for this problem**" Does it mean follow the course or copy the code?

**Versions**
Android Studio version:_ Android Studio Electric Eel | 2022.1.1 Patch 2

**Comment by johnshea** [comment]
Hi.

Thank you for writing in with you question.

The resources are listed lower down on the page.

<img width="831" alt="Screenshot 2023-09-22 at 12 41 23 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/618b3ae8-2770-4ff5-b20e-1a0efd93ce1c">

Hope you are enjoying the course!

Regards.
