### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by 202120210** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#243]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

I cant reinstall android studio on my windows

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @202120210,

Thank you for reaching out to us.
Could you please give us some more context, like what exactly is incorrect?
