### ISSUE TITLE
 TUTORIAL Jetpack Compose Tutorial - Lesson 1: Composable functions

### ISSUE THREAD

**Issue by ghost** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#246]
I have started working on the below tutorial, I have followed these instructions from the tutorial: **New Project, and under the Phone and Tablet category, select Empty Compose Activity. Name your app Compose Tutorial and click Finish.** and the course does not relate to what's showing in the project set up in Android Studio and the tutorial does not explain very well.

https://developer.android.com/jetpack/compose/tutorial

Example:
![image](https://user-images.githubusercontent.com/127499443/227936673-1815dfca-49e8-4149-8cea-678fa79b2921.png)

This tutorial needs work. I understand it from the start but it does not relate to what's showing in Android Studio and it does not explain very well on what actions to take. 

I have not reached the end, so I will wait. Also, I am waiting until I hear back regarding the Jetpack Compose course.

I feel that these courses should be worked on.

**Comment by johnshea** [comment]
Hi @umaar 

Thank you for writing in with your comment regarding the lesson wording.

Your observation is being passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
