### ISSUE TITLE
Practice problems: Android Basics in Compose

### ISSUE THREAD

**Issue by YaerQ** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#25]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11)

Task 12 Solution Code

There are some errors and some stuff missing
In the Message Formatting Section, the values in the exercise are 5000 and 1000 but in the Code Solution the values shows as 500 and 100. 

In the Implement basic math operations section, in step 2 you ask several things 
1. Create an add() function that accepts a firstNumber parameter, secondNumber parameter and thirdNumber parameter, all of Int type, and returns an Int value. 
2. add the values of firstNumber and secondNumber 
3. add the values of firstNumber and thirdNumber
4. return the result of both operations in the following format firstNumber + secondNumber = result and  
 firstNumber + thirdNumber=result (ex. 10 + 5 = 15) 
5. add a subtract function using the add function as a template.

On the Code Solution section for this task on step 2  the solution is incomplete it only shows this: 

```
fun add(firstNumber: Int, secondNumber: Int): Int {
    return firstNumber + secondNumber
} 
```

as a solution, it doesn't shows what code to add on the main function or how to return both addition operations that were asked (firstNumber + secondNumber and firstNumber + thirdNumber) in the format asked: 10+5=15. If I'm not mistaken the given solution will only print the result number. Also it doesn't show the subtract solution.

**Comment by osuleymanova** [comment]
@YaerQ 
The issues that you presented to us are extremely important, and I thank you for bringing it to our attention. The actions were taken to fix and clarify the content in the Solution code section:

![Screen Shot 2022-07-27 at 11 47 34 AM](https://user-images.githubusercontent.com/86437155/181349630-945547f1-834c-46b0-99fd-f06f8b1299a1.png)
