### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#250]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#5

**In which task and step of the codelab can this issue be found?**
Task 6

**Describe the problem**
you had us create a function BirthdayGreetingWithText(), but then the parameter you passed was "Happy Birthday Sam!". So, it's not really a birthday greeting function, is it? it's just a simple Greeting() function. Kind of unnecessary.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @reknoZ 

Thank you for writing in and bringing this to our attention.

The lesson has been updated to address this issue and already republished.

Hope you are enjoying the course!

Regards.
