### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by ghost** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#251]
@osuleymanova @android-dev-lxl 
Hope all is well.

I have a question, I have noticed that there's a lot of reading as well as the course content to complete. Would you be able to advise of the best way to learn please as in structure?

I am learning Jetpack Compose Basics and also, I sometimes struggle to retain and absorb the information. I am dyslexic.

Advise welcome.

**Comment by johnshea** [comment]
Hi.

Thank you for your question.

I would suggest doing all the hands on parts of the lesson so you get practice programming what you are learning.

After you complete a section, try to think of a sample problem in your head and then code that too.

For example, if the lesson shows how to add two numbers together. You could then try to add three numbers together to test yourself.

Hope this helps and you are enjoying the course!

Regards.
