### ISSUE TITLE
Add images: Android Basics with Compose - incomplete guide

### ISSUE THREAD

**Issue by m-kubalewski** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#255]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Task 4 -> Accessing resources -> step 3

**Describe the problem**
In step 3 guide asks the user to add an Image composable. Creating such composable the way guide asks the user to do:
```
Image(painter = image)
```
 leads to an issue with not enough arguments supplied. According to the codelab, providing additional library in form of
```
import androidx.compose.foundation.Image
```
Is enough to solve an error, which is false, because user needs to provide _contentDescritpion_ argument too. Adding second argument to the Image composable is show in the next section of the lab, which may prove problematic to the less experienced students.

**Steps to reproduce?**
Irrelevant to the issue

**Versions**
Irrelevant to the issue

**Additional information**
In the screenshot provided code presented to the user appears to be sufficient to complete the task, but is not.
![image](https://user-images.githubusercontent.com/123179373/229391367-cdcb5ca4-6bff-4c22-a096-b018a64a6ff0.png)

**Comment by johnshea** [comment]
Hi @m-kubalewski 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
