### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by TonyGoOnline** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#256]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions&authuser=1#2

**In which task and step of the codelab can this issue be found?**
Task 2. Run the code and observe that everything still works.

**Describe the problem**
//in Task 1 it is asked to use this code in Kotlin Playground:
fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}
//in Kotlin Playground it returns error 'No main method found in project'

**Steps to reproduce?**
1. Go to... Kotlin Playground
2. Click on... Green triangle to play)
3. See error... No main method found in project.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/28984258/230085215-57c89cbf-a844-4b13-830e-349b4a8752da.png)
![image](https://user-images.githubusercontent.com/28984258/230084907-66026de1-a83e-4218-b1a7-9df19e5e5364.png)

**Comment by osuleymanova** [comment]
Hello @TonyGoOnline,

Thank you for reaching out to us and sharing the screenshot with the code failed. 
In the previous section "Define and call a function" you called birthdayGreeting() function in the main() function:
![Screenshot 2023-04-05 at 10 21 45 AM](https://user-images.githubusercontent.com/86437155/230156406-64864be2-dce9-43d4-9698-48612dc4876e.png)
Looking at your code in the screenshot it becomes clear that the main() function is missing. Please refer to the correct code below:

![Screenshot 2023-04-05 at 10 25 23 AM](https://user-images.githubusercontent.com/86437155/230157150-2b09e05b-3f89-45ff-8996-b01c715f7e4d.png)

I hope this helps you to continue learning Android!
