### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by PaidupatiBharath** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#259]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#5

**In which task and step of the codelab can this issue be found?**
Create your first android app -> Change the background color

**Describe the problem**

Incorrect reference provided for optimizing imports

**Steps to reproduce?**
1. It says in step7 that, In your code, the best practice is to keep your imports listed alphabetically. To do this press Help on the top toolbar, type in optimize imports, and click on Optimize Imports.
2. Actually, the Help option doesn't have the optimize imports option. Whereas it is present in Code option

**Versions**
_Android Studio version:_ 2021.2.1
_API version of the emulator:_ NA

**Comment by android-dev-lxl** [comment]
@PaidupatiBharath 
Thank you for reaching out to us. the actual instructions does not say you need to enter `optimized import` and click on Optimized import.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/24260141/231311476-8c2fae76-49b5-43e2-9fe3-aa9955e8f455.png">

**Comment by johnshea** [comment]
Lesson wording is correct.

Closing this issue to resolve it.
