### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by SHPILEVAYAEVGENIYA** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#260]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#8

**In which task and step of the codelab can this issue be found?**
9. Define property delegates

**Describe the problem**
"Note: The **KProperty** is an interface that represents a declared property and lets you access the metadata on a delegated property. It's good to have high-level information about what the **KProperty** is."

"KProperty" is bold blue color text. If it must link - it doesn't works.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @SHPILEVAYAEVGENIYA 

Thank you writing in regarding this issue.

The correction has been made and the lesson will be republished again in the near future.

Hope you are enjoying the course.

Regards.
