### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by chawk073** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#261]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#6)

**Task 7 Step 2**

`import androidx.compose.ui.unit.dp` must be added to `MainActivity.kt` for the app to build. Suggest adding step after step 2 describing ways to import the missing package.

**Versions**

**Android Studio**
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 16, 2023
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Emulator Properties**
avd.ini.displayname              Pixel 5 API 30
avd.ini.encoding                 UTF-8
AvdId                            Pixel_5_API_30
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:3274126e0242a0d86339850416b0ce34
hw.device.manufacturer           Google
hw.device.name                   pixel_5
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   440
hw.lcd.height                    2340
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         30
image.sysdir.1                   system-images\android-30\google_apis\x86\
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      256

**Comment by osuleymanova** [comment]
Hello @chawk073,

Thank you for reaching out to us and sharing your feedback. I will pass it along to the team for further consideration. The codelab will be updated and published soon.
