### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by ouiminga** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#264]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Les noms des variables doivent être en majuscule et commencer par une lettre minuscule.

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5 
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ouiminga 

Thank you for reporting this issue.

It is a [duplicate](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/210) that is already scheduled to be fixed so I will be closing this one.

Hope you are enjoying the course!

Regards.
