### ISSUE TITLE
Text composables: Inconsistencies with naming convention

### ISSUE THREAD

**Issue by Gamer2015** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#265]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**In which task and step of the codelab can this issue be found?**
Task 6, Step 4

**Describe the problem**
The composable function name `BirthdayGreetingWithText` is not compatible with the naming conventions for composables that are specified in Task 4 > Composable function names:
```
The Compose function:
- NOT a nouned preposition: TextFieldWithLink()
```

**Additional information**
Naming conventions:
<img width="1327" alt="Bildschirmfoto 2023-04-11 um 23 55 47" src="https://user-images.githubusercontent.com/6293177/231303656-db42e4ff-631d-4346-83ad-839b14745552.png">
Inconsistent naming of a composable:
<img width="1333" alt="Bildschirmfoto 2023-04-11 um 23 55 41" src="https://user-images.githubusercontent.com/6293177/231303645-dc78db11-c0c4-4f9f-b9c7-3f384055c1ed.png">

**Comment by osuleymanova** [comment]
Hello @Gamer2015 ,

Thank you for reaching out to us. The composable function name is fixed and will be published soon:

![Screenshot 2023-04-13 at 3 43 17 PM](https://user-images.githubusercontent.com/86437155/231899338-4646ef96-311d-414a-b1c7-7f068315823a.png)

Happy Android learning!
