### ISSUE TITLE
Add images: Android Basics with Compose: typo

### ISSUE THREAD

**Issue by jderijke** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#268]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6
**In which task and step of the codelab can this issue be found?**
task 7, strep 3

**Describe the problem**
typo:
text:           Arrange the text elements to the top of the align them center horizontal.
should be: Arrange the text elements to the top of the column and align them center horizontal.

**Comment by johnshea** [comment]
Hi @jderijke 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
