### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by HTfeuerstein** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#269]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#6

**In which task and step of the codelab can this issue be found?**
7. Add padding  -> 1.Add these imports to the import statement section.
Make sure to use Optimize Imports to alphabetize the new imports.

**Describe the problem**

If you optimize Imports before the code is changed in Step 2, then the unused imports will be removed, so the code is not working after Step 2

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @HTfeuerstein 

Thank you for noticing this issue and reporting it.

The lesson content has been updated to address it.

The updated lesson content has already been republished to production.

Hope you are enjoying the course!

Regards.
