### ISSUE TITLE
Functions in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by Nazir23** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#27]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions&hl=en#3

**In which task and step of the codelab can this issue be found?**
5 and 7

**Describe the problem**
output should also print (you are now 5 years old!)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Nazir23 
Thank you for reaching out to us. The code output in both snippets is fixed and published:

![Screen Shot 2022-07-25 at 3 08 56 PM](https://user-images.githubusercontent.com/86437155/180882174-f7c861cd-0dc9-4e2a-a01c-e280859317b9.png)
