### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by SKNsiddharth** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#270]
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4

fun main() {
    val trip1 = 3.20
    val trip2 = 4.10
    val trip3 = 1.72
    val totalTripLength = trip1 + trip2 + trip3
    println("$totalTripLength miles left to destination")
}

**val**  is used which cannot be reassigned a value , **var** should be used in its place

**Comment by johnshea** [comment]
Hi @SKNsiddharth 

Thank you for writing in with your comment.

The of use `val` is correct in this program.

The variable values are assigned once when they are declared and they are not being reassigned at any time so `var` is not needed.

Please refer to [Variables](https://kotlinlang.org/docs/basic-syntax.html#variables) in the Kotlin documentation for additional information.

Hope you are enjoying the course!

Regards.
