### ISSUE TITLE
First Android app: Android Basics with Compose - unordered list below image

### ISSUE THREAD

**Issue by ctag** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#273]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
5. Update the text

**Describe the problem**
An image about halfway through uses three numbers to label some code in android studio. Below it is an unordered list, which could benefit from being an ordered list to link the descriptions to the numbered labels in the image.

The first list item is: "You add the @Composable annotation before the function."

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/6200085/233437994-5f64ed01-3372-4457-8c78-4486cfe0e55b.png)

**Comment by johnshea** [comment]
Hi @ctag 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
