### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by slug-enjoyer** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#275]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
none of the sections are marking complete after i hit done. kind of makes it hard to track progress

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @slug-enjoyer 

Thank you for writing in.

Are you possibly using an incognito tab?

At this time we are unable to duplicate your issue.

If you are still experiencing a problem, please provide screenshots and browser information so we can investigate further.

Hope you are enjoying the course!

Regards.
