### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by TboneBEL** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#276]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5)

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
informations fausses :

"être en majuscule et commencer par une lettre minuscule" (le contraire est vrai : les noms de variables doivent commencer par une lettre minuscule et utiliser la convention de casse de style camel)
"insérer une espace après les deux-points (:) lorsque vous spécifiez le type de données" (il ne doit pas y avoir d'espace après les deux-points)
"Double", "Une flèche pointe vers l'espace entre le signe deux-points et le type de données" (le mot "Double" est correct mais il ne doit pas y avoir d'espace après les deux-points)
"Il doit y avoir une espace avant et après un opérateur" (il doit y avoir un espace avant et après les opérateurs)
"avec une étiquette indiquant une espace" (l'étiquette doit dire "un espace" au lieu de "une espace")
"la limite est fixée à 100 caractères par ligne" (la limite recommandée est de 120 caractères par ligne)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @TboneBEL 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
