### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by e-mccormick** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#277]
Split no longer exits. Makes me wonder what other basic things you are telling people to do that they simply can't because of interface changes.

**Comment by johnshea** [comment]
Hi @e-mccormick 

As you did not provide any of the requested information it is not possible to provide you with further assistance.

If you could create a new issue and provide additional information and screenshots, we would be happy to improve the course content as needed.

Hope you are enjoying the course!

Regards.
