### ISSUE TITLE
Unresolved reference: dp, i am again and again was getting this error and was not able to find the solution please help

### ISSUE THREAD

**Issue by vatysa** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#28]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jincy-p-janardhanan** [comment]
See this issue: https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/40
I've mentioned the solution.

**Comment by osuleymanova** [comment]
@vatysa 
Thank you for reaching out to us. Please check in MainActivity fie if the line 'import androidx.compose.ui.unit.dp' is added in the package.
Happy coding!
