### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by SkipperShark** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#283]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Task 9 ("Try This Challenge")
Step 2?

**Describe the problem**
I think there might be a small thing that was missed out on one of the screenshots for how our app should look.
The challenge wants us to add some padding-right onto one of the text components and shows an example of how the app should look after the padding was added. But I think the example image / screenshot that was shown does not have any padding applied.
I've attached a screenshot, hopefully you guys can see it.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ not applicable
_API version of the emulator:_ not applicable

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/74845288/233942897-80a914a4-6438-40e1-9d89-356f64101855.png)

**Comment by johnshea** [comment]
Hi @SkipperShark 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
