### ISSUE TITLE
Description Error

### ISSUE THREAD

**Issue by dongmenpiaoqian** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#285]
**URL of codelab**
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-add-images?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
![image](https://user-images.githubusercontent.com/12571213/234262491-93f4cf77-c718-46b6-875c-93ec9dad0712.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @dongmenpiaoqian 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
