### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by sravanatvaio** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#286]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#4

**In which task and step of the codelab can this issue be found?**
design pane in android studio

**Describe the problem**
why is there a sentence HappyBirthdayTheme .....it shows error on android studio.
and it has no use explained in the course too.
kindly clarify .

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @sravanatvaio 

Thank you for writing in.

I reviewed the linked material and your description but was unable to understand the issue. The course has been updated so it is possible this has already been resolved.

If you have time and the desire, please review the lesson again to see if the issue still exists.  If it does, please create a new issue and provide screenshots and the requested information so it can be looked into further.

Hope you are enjoying the course!

Regards.
