### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by eclassconsulting** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#287]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app&hl=en#1

**In which task and step of the codelab can this issue be found?**

Create your first Android app

**Steps to reproduce?**
1. Go to create a template Empty Compose Activity

The dialog and the actual project created differ in version from your course, which is out of date

**Versions**
_Android Studio version:_ 2022 (Flamingo)
_API version of the emulator:_  (whatever, does not matter)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @eclassconsulting 

Thank you for writing in with this issue.

The course content and screen images have been updated to reflect the latest stable version of Android Studio so this issue has been corrected.

Hope you are enjoying the course!

Regards.
