### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by vmrocha** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#289]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app

**In which task and step of the codelab can this issue be found?**
First statement.

**Describe the problem**
The template name should be "Empty Activity" and not "Empty Compose Activity" as per the most recent/stable version of Android Studio.

**Steps to reproduce?**
N/A

**Versions**
_Android Studio version:_ 2022.2.1
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @vmrocha 

Thank you for writing in with this issue.

You are correct and the course content and screen images have been updated to reflect the latest stable version of Android Studio.

As this issue has been resolved, I will mark it as closed.

Hope you are enjoying the course!

Regards.
