### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by SamiraCavalcanti** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#29]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Eu terminei ,mas nao aparece como concluído 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@SamiraCavalcanti 
Obrigado por nos contactar. Verifique se você está conectado.
