### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by Neosfeeraty** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#290]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**Describe the problem**
Android Studio 2022.2.1 gives an error when replacing colorSheme with color

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 2022.2.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Neosfeeraty 

Thank you for writing in with your issue.

I reviewed the lesson but was unable to determine what part was causing you an issue.

If you have time, please try the lesson again to see if the issue still exists as we have been updating and improving the course. If it does, please create a new issue and include all the relevant information including screenshots so we can help you troubleshoot further.

Hope you are enjoying the course!

Regards.
