### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by JustTheK** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#292]
Image download

[**URL of codelab**](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png)

Error 404 not found

**Comment by aseba1** [comment]
Same problem, Tried to go to the earliest issue# with this but heres the correct link and the broken one. :)

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
2.
Add an image to your project

**Describe the problem**
Incorrect Link
Correct Link = [https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png](url)

Incorrect Link = [https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png](url)
