### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by pnwbob** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#293]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Add an image to your project

1. In this task, you'll download an image from the internet and add it to your Happy Birthday app.

2. Open the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png).
    Click Download.

**Describe the problem**

The link in step 2 is broken and should be fixed. 

**Steps to reproduce?**
1. Go to the url above
2. Click on the link above
3. See error...

**Versions**
_Android Studio version:_ Android Studio Flamingo | 2022.2.1 Patch 1
_API version of the emulator:_ 

**Additional information**
 I was able to root around in the folder structure and find it here:
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/tree/main/app/src/main/res/drawable-nodpi
_Include screenshots if they would be useful in clarifying the problem._

**Comment by heidy-miguel** [comment]
Thanks for the correct image path.

**Comment by johnshea** [comment]
Hi @pnwbob 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
