### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by brian-voter** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#294]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Task 2, "Add an image to your project"

**Describe the problem**
The link at: 

`Open the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png). `

is invalid

**Steps to reproduce?**
1. Go to...
2. 
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png

3. See error...

**Comment by johnshea** [comment]
Hi @brian-voter

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
