### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by kesteve** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#295]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images

**In which task and step of the codelab can this issue be found?**
Open the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png).

**Describe the problem**
The image URL is broken.

**Comment by johnshea** [comment]
Hi @kesteve 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
