### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by jpphl** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#297]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%26hl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images&hl=en#1

**In which task and step of the codelab can this issue be found?**
Add images to your Android app, Step 2 Set up your app

**Describe the problem**
Broken GitHub link to image required for task: https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @jpphl 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
