### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by AlexRantos** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#298]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
2

**Describe the problem**
The [link ](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png) to download the image returns 404 from Github

**Steps to reproduce?**
1. click on the " [link ](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png)"
2. new tab opens with github
3. page shows 404

**Versions**
N/A

**Additional information**

**Comment by johnshea** [comment]
Hi @AlexRantos 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
