### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#3]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
[5. Solution code](https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?hl=en#4)

**Describe the problem**
Solution links don't work

**Steps to reproduce?**
1. Just check the links.

**Versions**
N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Morteza-Rastgoo 
Thank you for reaching out to us. The issue is not reproducible as the links are working fine.
