### ISSUE TITLE
Functions in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by MasoudBB** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#30]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4

**In which task and step of the codelab can this issue be found?**
Functions with multiple parameters

**Describe the problem**
function definition:

fun birthdayGreeting(name: String, age: Int): String {
    val nameGreeting = "Happy Birthday, $name!"
    val ageGreeting = "You are now $age years old!"
    return "$nameGreeting\n$ageGreeting"
}

output:
Happy Birthday, Rover! You are now 5 years old!
Happy Birthday, Rex! You are now 2 years old!

in the return statement there is \n and output should be:

Happy Birthday, Rover!
You are now 5 years old!
Happy Birthday, Rex!
You are now 2 years old!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@MasoudBB 
Thank you for reaching out to us. The output is fixed and published:

![Screen Shot 2022-07-25 at 3 14 52 PM](https://user-images.githubusercontent.com/86437155/180883007-9a56d6aa-60d2-4cb8-bead-a16f9c654483.png)
