### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Jena-vie** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#300]
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

Section 2, Step 1

Provided link does not work: takes you to github 404 error page.

**Steps to reproduce?**
1. Go to...Section 2
2. Click on... link in Step 1
3. See error...404

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Jena-vie 

Thank you for writing in with your issue.

I checked the link and it is working for me as expected. I do not get a 404.

If you are still having a problem and have the time, please create a new issue with all the requested information and provide full screen screenshots so we can see what you are viewing, clicking, and the response you get so the team can further investigate.

Hope you are enjoying the course!

Regards.
