### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Sargius** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#301]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Step 2

**Describe the problem**
The link is broken. There is no image to download

https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Sargius 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
