### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by alexisalmeida** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#302]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
[2. Set up your app](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1)

**Describe the problem**

The link to the "androidparty" image is no longer available

**Steps to reproduce?**
1. In the item "Add an image to your project", click on the "[link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png)"

**Comment by osuleymanova** [comment]
Hello @alexisalmeida,

Could you please double check the link as it's working on my side?
If you are still facing this issue, please use the link below:
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png

**Comment by alexisalmeida** [comment]
Hi!

Yes, it works for me now. Thanks.

Aléxis

Em qui., 8 de jun. de 2023 20:08, osuleymanova ***@***.***>
escreveu:
