### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by fcozza** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#303]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8)

Step 9 

Adopt good practice
It is a good practice to pass the modifier attribute(s) along with the modifier from the parent composable. Update the modifier parameter in the GreetingText() as follows:

onCreate()

**Steps to reproduce?**
Step 9 Adopt good practice does not update the code it's already ok

**Comment by AndrewRowley** [comment]
Are you finding the course easy to follow?

**Comment by fcozza** [comment]
Yes ...
but it's still the begininng :)

**Comment by johnshea** [comment]
Hi @fcozza 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
