### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by fcozza** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#304]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1)

Step 2

Open the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/M3_migration/app/src/main/res/drawable-nodpi/androidparty.png).

The link is broken

Correct link could be:

https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png

**Comment by AndrewRowley** [comment]
I've just raised this as well

**Comment by osuleymanova** [comment]
@fcozza,

Thank you! It will be fixed shortly.
Please use this link instead:
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png
