### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by AndrewRowley** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#305]
Hi @osuleymanova @android-dev-lxl

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

When I click on this link i've highlighted in yellow
![image](https://user-images.githubusercontent.com/130699271/236564546-46fb3ffc-46e7-4aa1-936a-f1c003e407a3.png)

I then end up with this
![image](https://user-images.githubusercontent.com/130699271/236564629-577e7aae-b5f9-4e1d-9127-9441741927cf.png)

I will use an alternative image in the meantime.

**Comment by osuleymanova** [comment]
Hello @AndrewRowley,

The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. Actions will soon be taken to fix it.
Please use this link:
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png

**Comment by User202379** [comment]
Your welcome
________________________________
