### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by DeocBrut** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#308]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#7

**In which task and step of the codelab can this issue be found?**
Task 8, "Arrange the text elements in a row"

**Describe the problem**

When highlighting "Text" as instructed and bulb is clicked and text surround with row is selected, it only puts the first text composable in a row and not the second one also. But the instruction says select the two Text composables, and then the code that codelab shows isn't the same as the code that you get in Android Studio.

**Versions**
_Android Studio version:_ 2022.2.1
_API version of the emulator:_ 

**Additional information**
Spot the difference on the attached images.
_Include screenshots if they would be useful in clarifying the problem._
![Codelab's code](https://user-images.githubusercontent.com/107075275/236636195-69e7b676-a58d-4701-a577-3662431e1078.jpg)
![Android Studio code](https://user-images.githubusercontent.com/107075275/236636196-aca04b7f-a97b-43f1-8ac9-e88c35baed94.jpg)

**Comment by johnshea** [comment]
Hi @DeocBrut 

Thank you for writing in.

I worked through this part of the lesson again and after selecting the two Text composables I was able to click on the "bulb" and surround them with a Row composable as the following steps instructed.

If you are still having an issue and have the time, please redo this portion of the lesson by removing the Row composable and trying to reselect both Text composables and then surrounding them with the Row composable.

As you are doing this, take screenshots (including the two Text composables being selected) so the team can redo your example step-by-step for troubleshooting.

Create a new GitHub issue and lease provide these screenshots, your Android Studio information, your OS information, and anything else you feel could help us resolve this issue.

Hope you are still enjoying the course!

Regards.
