### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by BenAttenborough** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#309]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**
Add an image composable

**Describe the problem**
The image does not render in the preview (but does render on the emulator).
On the preview pane I see an error which says "Some issues were found while trying to render this preview."

Viewing the problem gives me the following message:
java.lang.IllegalArgumentException: Only VectorDrawables and rasterized asset types are supported ex. PNG, JPG   at androidx.compose.ui.res.PainterResources_androidKt.loadImageBitmapResource(PainterResources.android.kt:111)   at androidx.compose.ui.res.PainterResources_androidKt.access$loadImageBitmapResource(PainterResources.android.kt:1)   at androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:70)   at com.example.happybirthday.MainActivityKt.GreetingImage(MainActivity.kt:66)   at com.example.happybirthday.ComposableSingletons$MainActivityKt$lambda-4$1.invoke(MainActivity.kt:79)   at com.example.happybirthday.ComposableSingletons$MainActivityKt$lambda-4$1.invoke(MainActivity.kt:78)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

_API version of the emulator:_ 
Unknown

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="1919" alt="Screenshot 2023-05-06 at 21 29 24" src="https://user-images.githubusercontent.com/8101421/236645416-7f0fdb08-bad2-4222-bae7-b910e1424656.png">

**Comment by johnshea** [comment]
Hi @BenAttenborough 

Thank you for writing in with this issue.

I tried but was unable to duplicate it.

We are updating the lesson and will be republishing it again in the near future. In addition, there is a new stable version of Android Studio released.

If you have time and are willing, once the updated lesson is published see if you are able to duplicate this issue so we can troubleshoot it further.

Hope you are enjoying the course.

Regards.
