### ISSUE TITLE
all trinaings / Translation error german "Back"

### ISSUE THREAD

**Issue by trubbert2013** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#310]
**URL of codelab**

all codelab / German buttons

**Describe the problem**

"Zurücksetzen" means resetting. The correct translation for "Back" is "Zurück".

**Comment by johnshea** [comment]
Hi @trubbert2013 

Thank you for taking your time to report this.

It was will be shared with the team so it can be addressed.

Hope you are enjoying the course!

Regards.
