### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by ghost** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#311]
@osuleymanova @android-dev-lxl 

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#9

**In which task and step of the codelab can this issue be found?**
10 Get The Solution Code.

**Describe the problem**
The code on the left in Android Studio is exactly what's been instructed in the course to write. But, then when I look at the solution code in Get The Solution Code, the code is different from whats been instructed to write. 
![image](https://user-images.githubusercontent.com/130699271/236796279-10c8295f-1e0f-44f2-9be4-a5c3ce5ca3ad.png)

For example, the below screenshot, in the GreetingText fuction, shows no padding on the modifier, although the course has instructed me to add a padding to the modifier of 8.dp as you will see in Android Studio.
![image](https://user-images.githubusercontent.com/130699271/236797072-d4742412-a232-4d15-9948-86510ce93f30.png)

Regarding the emulators in the screenshots, I have fixed the issue by changing fontSize to 100.sp

--
I have noticed similar issues in the Kotlin Basics course.

**Comment by User202379** [comment]
Also, i'm unable to find an import for GreetingImage.

I will try again once this course has been updated. By the time I complete both codelabs and get to the practice, I don't know what to do all because of the course content, it losses me.

**Comment by User202379** [comment]
@android-dev-lxl @osuleymanova 

Hope all is well,

Can I have an update please regarding the issues raised?

Also, is there a direct contact in Android Developers I can contact regarding issues like these?

Thank you.

**Comment by johnshea** [comment]
Hi.

Thank you for writing in and bringing these issues to our attention.

The lesson has been updated to address them and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
