### ISSUE TITLE
Android Basics in Kotlin

### ISSUE THREAD

**Issue by User202379** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#312]
@android-dev-lxl @osuleymanova

This course requires attention and an update
![image](https://user-images.githubusercontent.com/130699271/236829477-1440868c-138a-4558-bf06-716c5bdc0b51.png)
 
Some of the course content is nonsensical because of how its been written and there are a lot of issues.

I would expect these courses to be easy to follow along to and easy retain as they are created by JetBrains and by Android Developer.

**Comment by osuleymanova** [comment]
Hello @User202379,

Thank you for your feedback. We're sorry to hear that the courses don't live up to your expectations.
