### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by harshivsah** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#315]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#2

**In which task and step of the codelab can this issue be found?**
Second line of the page  has spelling mistake "Define versus use a variable."
![Opera Snapshot_2023-05-12_133746_developer android com](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/133331335/dc1d0ae9-2ecc-4f28-b9da-d2f99790038b)

**Describe the problem**
It is a simple spelling mistake to be corrected.

**Comment by User202379** [comment]
Where is the spelling mistake?

**Comment by harshivsah** [comment]
I believe this sentence doesn't convey the meaning accurately " Define
versus use a variable ".
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#2

**Comment by johnshea** [comment]
Hi @harshivsah 

Thank you for writing in with your comment regarding the lesson wording.

Your observation is being passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
