### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Spemncert** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#317]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#1

**In which task and step of the codelab can this issue be found?**

task 5, step 2.

**Describe the problem**

the diagram does not include alt text. It instead reads the name of the image. 

**Steps to reproduce?**
1. Go to step 2 (define and call a function)
2. scroll down to the syntax for designing a function diagram
3. realise your screenreader is reading a bunch of rubbish (7b20f70d7a68c790.png) instead of alt text like the other diagrams in the course

**Additional information**
_![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/133476065/e9bb84fb-be48-43bd-915e-62056c522d5b)

**Comment by Spemncert** [comment]
man this happened in part 3 too :(

**Comment by Spemncert** [comment]
and 4. Im gonna assume the rest in this section dont have alt text.

**Comment by User202379** [comment]
Both the Compose and Kotlin courses need urgent attention, its not fair on us as learners

**Comment by johnshea** [comment]
Hi @Spemncert 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and will be republished in the near future.

Hope you are enjoying the course!

Regards.
