### ISSUE TITLE
Use classes and objects in Kotlin

### ISSUE THREAD

**Issue by dkmacharia** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#319]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Override superclass methods from subclasses

2. In the SmartLightDevice subclass before the fun keyword of the turnOn() and turnOff() methods, add the override keyword:

We never created the turnOn() and turnOff() methods in SmartLightDevice. Same applies to SmartTvDevice

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @dkmacharia 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
