### ISSUE TITLE
Functions in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#32]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#6

**In which task and step of the codelab can this issue be found?**
in 7. Default arguments

**Describe the problem**
just search for this:
> The second call to birthdayGreeting() still uses the Rex value, which you passed in for the name.

The expression "still uses" seems weird in that context, as if it's something that was already done from way before, it doesn't seem to be referring to the function call just written, but of course it can't refer to anything else, so by exclusion, it's eventually understood.
But maybe's just me that understands it this way.

**Additional information**
![Untitled2](https://user-images.githubusercontent.com/106607441/176769770-71bc7644-29e3-4df8-9af2-c8d0986ebeff.png)

**Comment by osuleymanova** [comment]
@correabuscar 
Thank you for reaching out to us and sharing your feedback. 
As the content of the codelab doesn't need any fix so the ticket is closed.
