### ISSUE TITLE
Install Android Studio: Android Basics with Compose Typo

### ISSUE THREAD

**Issue by adam662006** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#321]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-install-android-studio#0)

**In which task and step of the codelab can this issue be found?** On the first step, labelled _Before you begin_.

**Describe the problem**

On the second paragraph, it says _Android Studio is the official integrated development environment (IDE) for Android app, development built and distributed by Google_, and I believe the comma at the end should be after _development_, like so:

_Android Studio is the official integrated development environment (IDE) for Android app development, built and distributed by Google_

**Comment by johnshea** [comment]
Hi @adam662006 

Thank you for noticing and bringing this issue to our attention.

The content has been corrected and republished.

Hope you are enjoying the course!

Regards.
