### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by shitalrahane1234** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#323]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1

**In which task and step of the codelab can this issue be found?**
In 2nd 8th step of the codelab this issue can be found

**Describe the problem**
To create a new project with compose we need to select:  **Empty Compose Activity** instead of **Empty Activity** option because these are two different things.

**Steps to reproduce**
1.  New Project
2. Empty Compose Activity

**Versions**
  Android Studio Arctic Fox | 2020.3.1 Patch 3

**Additional information**

<img width="1059" alt="Screenshot 2023-05-18 at 4 17 34 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/18083222/30d050a4-de60-42f9-854d-33ca344348c8">

**Comment by User202379** [comment]
You have the old version of Android Studio, if you wish you can update to the latest version of Android Studio

**Comment by dgball** [comment]
Thankyou for this. I was wondering why the code i was being shown in the tutorial didnt match with the project created.

**Comment by osuleymanova** [comment]
Hello @shitalrahane1234, @dgball,

Thank you for reaching out to us.
In fact, in Android Studio Arctic Fox version you need to create a project selecting Empty Compose Activity, while in the latest Flamingo version it is called as Empty Activity:

![Screenshot 2023-06-07 at 4 33 04 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/86437155/62145525-aabb-49be-805c-1f7ec03cefcb)
 Probably you've noticed the specific icon for Compose Activity.
 
 Hope it clarifies a lot and clear your confusion.
