### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by joserossodeveloper** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#324]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Des-419#8**

**In which task and step of the codelab can this issue be found?**
Build a simple app with text composables, step 9, add greeting to the app

**Describe the problem**
In Adopt good practice, missing the `modifier = Modifier.padding(8.dp)` on the call to the GreetingText

```
onCreate()


Surface(
   //...
) {
    GreetingText( message = "Happy Birthday Sam!", from = "From Emma")
}
GreetingText()


@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
   Column(
       verticalArrangement = Arrangement.Center,
       modifier = modifier
   ) {
       //...
   }
}
```
```
Possible correction
Surface(
    modifier = Modifier.fillMaxSize(),
    color = MaterialTheme.colors.background
) {
    GreetingText(
        message = "Happy Birthday Sam!",
        from = "From Emma",
        modifier = Modifier
            .padding(8.dp)
    )
}
@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    Column(
        verticalArrangement = Arrangement.Center,
        modifier = modifier
    ) {
        // ...
    }
}
```

**Comment by JoseRosso26** [comment]
I got a little confused in that part, but I get it, but it would be ideal that in the onCreate() you pass a Modifier to the GreetingText() function so that it is better understood.

**Comment by johnshea** [comment]
Hi @joserossodeveloper 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
