### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by AlinTimofte** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#326]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#4

**In which task and step of the codelab can this issue be found?**
Task 5

**Describe the problem**

The suggested code should not be:
color = MaterialTheme.colors.background
-it leads to a bunch of errors
I think what it needs to be is:
color = MaterialTheme.colorScheme.background

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @AlinTimofte 

Thank you for writing in and bringing this issue to our attention.

The lesson and code have been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
