### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by htg1889** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#327]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2&hl=ja#4

**In which task and step of the codelab can this issue be found?**
5-3 (Perhaps what I've found is only part of the problem. Information on all Japanese pages seems outdated.)

**Describe the problem**
While doing the Japanese version of the tutorial, I noticed that DefaultPreview() was missing in the auto-generated code.

```Kotlin
@Preview(showBackground = true)
@Composable
fun DefaultPreview() {
   GreetingCardTheme {
       Greeting("Meghan")
   }
}
```

https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2&hl=ja#4

When I checked the English version of the tutorial, the same GreetingPreview() as my code was posted.
```Kotlin
@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    GreetingCardTheme {
        Greeting("Meghan")
   }
}
```

https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2#3

I presume that the information written in Japanese is old information.

**Steps to reproduce?**
1. Proceed with project creation according to the Japanese tutorial.

**Versions**
_Android Studio version:_ 
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 20, 2023

_API version of the emulator:_ 
None

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/31609682/6b0de5be-358f-4899-b2fa-5bab543b24a7)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/31609682/886a8b90-6815-4412-bfcc-6cefd5972d96)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/31609682/d17852c2-aa63-4d7d-8ad2-a0fda3d2196e)

**Comment by osuleymanova** [comment]
Hello @htg1889,

Thank you for reaching out to us and sharing your concern.
Please note that after updating the content of the English version, it takes about another couple of weeks for the update in all other languages. 
If after another 1-2 weeks the mismatch is still observed, please do not hesitate to open a new GH issue.
