### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by alanlowzies** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#329]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**
Step 3: Add an Image Composable, under the task sub-header 'Accessing resources'.

**Describe the problem**
In the guide, it explains the reason why an initial declaration of the Image composable will have an error, and how to fix it:
> To fix the error, please include the following import, at the top of your `MainActivity.kt` file:
> ```import androidx.compose.foundation.Image```

The import step alone will not fix the error, but the following step in the guide (i.e. adding `contentDescription = null` to the Image composable) will fix the issue altogether. 

I felt that this part of the guide was slightly confusing. Perhaps a better way would be to instruct the user to add the import and `contentDescription` statements first before explaining the rationale for having the `contentDescription` variable set to `null`? This could potentially be less confusing.

**Steps to reproduce?**
1. After adding the Image composable (and the `image` variable), add the import statement.
2. Error still persists, despite the guide saying this should fix the error.

**Versions**
_Android Studio version:_ 2022.2.1 Patch 1
_API version of the emulator:_ 33

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/30099983/64fee622-8452-411f-a0e0-edc71b7c63b7)
_Fig. 1: Guide instructs on how to fix the error_

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/30099983/1918eef1-c3bc-4f45-8fba-88b45425715c)
_Fig. 2: Error persists after inserting the import statement_

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/30099983/a3290f29-7ac4-4a77-9bc6-d20569352fe2)
_Fig. 3: Guide subsequently explains accessibility and instructs to add the `contentDescription` argument_

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/30099983/24830752-e66d-4fe0-b8f8-1848cb37d125)
_Fig. 4: Error is fixed after adding `contentDescription` argument)_

**Comment by User202379** [comment]
The course does need updating, I am fully with you on this and with many others who experience issues with the course and its not fair on those trying to learning who are new to this.

Its also the same with Kotlin Basics.

And sometimes the course team don't respond.

I've been on the Kotlin course for well over a year and cant pass the first pathway due to how its been written and its also nonsensical and believe me, i'm a fast learner. Same with the Compose course, i've been on this now for a few months and by the time I reach the practices, I have no idea how to complete them.

**Comment by johnshea** [comment]
Hi @alanlowzies 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
