### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by jeffbruma** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#33]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#5

**In which task and step of the codelab can this issue be found?**
[6. Define a constructor](https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#5)
Note: If the class doesn't have a default constructor and you attempt to instantiate the object without arguments, the compiler reports an error.

**Describe the problem**
The codelab states that "if the class doesn't have a default constructor and you attempt to instantiate the object without arguments, the compiler reports an error." I tried and the compiler did not report an error.

**Steps to reproduce?**
1. Go to the Kotlin playground and create this:
class SmartDevice {
    val name = "Android TV"
    val category = "Entertainment"
    var deviceStatus = "online"
    var speakerVolume = 2
        set(value) {
            if (value in 0..100) {
                field = value
            }
        }    
    
    fun turnOn() {
        println("Smart device is turned on")
    }
    
    fun turnOff() {
        println("Smart device is turned off")
    }
    
}

fun main() {
    val smartDevice = SmartDevice()
    
    println("Device name is: ${smartDevice.name}")
    smartDevice.turnOn()
    smartDevice.turnOff()
}

3. Click on Run
4. See no error
![SSnoError](https://user-images.githubusercontent.com/72720043/176802699-c0706196-950b-4e10-81ca-d9aff643ee0e.png)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by SagarBegale** [comment]
For the code below:
```
class SmartDevice {
 ...
}
```

The compiler will add a default constructor in the background.
