### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by harshilshrma** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#331]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Add Images to your Android Lab > (2) Set up your app

**Describe the problem**
I cannot download the background image ("androidparty.png") whose link is given. It redirects to a GitHub site from where I cannot download the file. I wished it was available for direct download :(

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
The issue was fixed and published. The ticket is closed as resolved.
