### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Arthur-Milchior** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#333]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#1

**In which task and step of the codelab can this issue be found?**
2

**Describe the problem**
The description states to use "Empty Compose Activity". But today, it's called "Empty activity"
![2023-05-21-233256_900x650_scrot](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/357361/04b20c5d-bf14-4b58-9e2d-2381d49455bc)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  Android Studio Flamingo | 2022.2.1
_API version of the emulator:_

**Comment by johnshea** [comment]
Hi @Arthur-Milchior 

Thank you for writing in and bringing this discrepancy to our attention.

The lesson wording and screenshots are being updated to reflect the latest stable release version of Android Studio.

The updated lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
