### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by AnhVu12x08** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#335]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4)

**In which task and step of the codelab can this issue be found?** 5. Functions with multiple parameters, step 3

**Describe the problem**
type wrong

**Steps to reproduce?**
No value passed for parameter 'age'
No value passed for parameter 'age'** **must change to**
No value passed for parameter 'name'
No value passed for parameter 'age'

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/118417677/4f85fc59-f884-4a9c-9400-aae7cf4559d5)

**Comment by johnshea** [comment]
Hi @AnhVu12x08 

Thank you for writing in with your comment.

The code is correct as we are calling the function two times.

Once for "Rover" and once for "Rex".

We are passing a `name` each time but we have not yet passed an `age`.

<img width="886" alt="Screenshot 2023-07-19 at 2 21 49 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/08669859-6b0d-4388-8df1-b3e7ab054fae">

If I am misunderstanding your issue or you have further doubts, please do not hesitate to create a new issue.

Hope you are enjoying the course!

Regards.
