### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Jaseren** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#340]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10

**In which task and step of the codelab can this issue be found?**
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HappyBirthdayTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    BirthdayGreetingWithText( message = "Happy Birthday Sam!", from = "- from Emma")
                }
            }
        }
    }
}

**Describe the problem**

color = MaterialTheme.colors.background  .... colors=unresolved reference

**Steps to reproduce?**
1. Go to...line 16 import com.example.happybirthday.ui.theme.HappyBirthdayTheme  unresolved reference com
2. line 26  color = MaterialTheme.colors.background  unresolved reference coors
3. Click on...com.  and  colors
5. See error...

**Versions**
_Android Studio version:_ Android Studio Flamingo | 2022.2.1 Patch 1
_API version of the emulator:_  Pixel_3a_API_33:x86:64

**Additional information**

![screenHapybirrthday](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/127626128/aba7c4af-f18f-4c7b-8ace-a59962ca6fb4)
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/127626128/3c6bc9eb-7a8e-4ce0-8f4a-17ae61a47399)

**Comment by johnshea** [comment]
Hi @Jaseren 

Thank you for writing in about this issue.

The lesson wording, screenshots, and code are all being worked on to address this issue.

The corrected content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
