### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by Detective-Khalifah** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#342]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator

**In which task and step of the codelab can this issue be found?**
Codelabs with YouTube videos linked in them.

**Describe the problem**
A video keeps playing even when the user leaves the page on which it is embedded.

**Steps to reproduce?**
1. Go to a codelab that has a YouTube video embedded in it.
2. Play the video.
3. Go to the next/previous page of codelab.
4. Notice the video keeps playing.

**Versions**
_Opera browser version: 99.0.4788.31_ 
_Windows OS version:_

**Comment by osuleymanova** [comment]
Hello @Detective-Khalifah,

Thanks for reaching out and reporting this issue- we'll pass the feedback to the team.
In the future, we recommend pausing the video before moving to the next page.
