### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ikram-khan-fahim** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#345]
**URL of codelab**
[Add images to your Android app](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images)

**In which task and step of the codelab can this issue be found?**
Task: [3. Add an Image composable](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#2)
Step: Resources in Jetpack Compose > Accessing resources

**Describe the problem**
The tutorial says:
> Android Studio displays an error that says that, "None of the following functions can be called with the arguments supplied." the arguments don't match the function signature...To fix the error, please include the following import, at the top of your MainActivity.kt file:

```kotlin
import androidx.compose.foundation.Image
```

Expected: The import should resolve the error.
Observed: The import doesn't do away with the error.

**Versions**
_Android Studio version: 2022.2.1 Patch 2_

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/107660333/d9331688-20e4-42ca-9094-8ae2023dbbb1)
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/107660333/18f85bb2-d891-4bca-9161-7c9f97c77822)

**Comment by o-alquimista** [comment]
That's right, I ran into the same error. If you let the IDE autocomplete the `Image` composable, it will also add the `contentDescription` argument, which seems to be required.

**Comment by johnshea** [comment]
Hi @ikram-khan-fahim 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
