### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by tomb00105** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#348]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
Step 9 - Add greeting to the app

**Describe the problem**
The given code does not vertically center the message on the screen, it stays at the top. Adding .fillMaxSize to the column seems to resolve the issue

**Steps to reproduce?**
1. Copy solution code to Android Studio
2. Run solution code
3. It is not centered on the emulator

**Versions**
_Android Studio version:_ 
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

_API version of the emulator:_  
33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @tomb00105 

Thank you for writing in with your issue.

I reviewed the lesson's instructions and they appear to be working as described.

As you did not provide your code this is only a guess but make sure your `Surface` compsable has the the following modifier `modifier = Modifier.fillMaxSize()`, perhaps it is missing.

If you are still having an problem, please create a new issue and include your code and emulator screenshot so we can help you troubleshoot it further.

Hope you are enjoying the course!

Regards.
