### ISSUE TITLE
First Android app: Android Basics in Compose

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#35]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
`5. Update the text`

**Describe the problem**
The text `The Greeting() function under the onCreate() function is a Composable function. Notice the @Composable annotation above it. ` gives me the impression that there's code above that should be there but it isn't! In fact, such code is below this text instead!

In other words, `The Greeting() function` isn't above at all, there's a function **__call__**, but it is inside, not `under`, the onCreate() function.
There's no `@Composable annotation` above! And there's no way to scroll down inside the above code(so, the code that's visible is all the code), see screenshot below.

So there's likely code missing above. Or maybe, I'm supposed to look only at my project contents and notice that code there? 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Untitled3](https://user-images.githubusercontent.com/106607441/177745395-f6b2ee34-56e4-4acc-bfd7-3c125151605f.png)

The missing code is duplicated below though:
![Untitled4](https://user-images.githubusercontent.com/106607441/177746759-2d348c53-c147-4628-af3d-b0ef42b03fb1.png)

**Comment by osuleymanova** [comment]
@correabuscar 
Thank you for reaching out to us. The text was modified and published:

![Screen Shot 2022-07-25 at 3 26 47 PM](https://user-images.githubusercontent.com/86437155/180887210-074535ab-12e4-47ec-8cd9-2ce4c9466d7c.png)
