### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by dgball** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#352]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#3

**In which task and step of the codelab can this issue be found?**
update the text

**Describe the problem**
the code descibed in the tutorial doesnt match up with the code created in the template in android studio. As I beginner I find this a major road block to learning.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @dgball,

Thanks for reaching out to us. Could you be more specific what is your blocker? Please provide the screenshot or describe in details.

**Comment by osuleymanova** [comment]
Hello @dgball,

We appreciate you opening this issue but as we did not receive additional feedback from you, we will be closing this issue at this time as there unfortunately is nothing further we can do to assist you.

We have been busy updating the course and hopefully have addressed it for you.

If you are still experiencing an issue, please do not hesitate to create a new issue with the requested items so we can address it.

Hope you are enjoying the course!

Regards.
