### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Benimacle** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#353]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5

**In which task and step of the codelab can this issue be found?**
6

**Describe the problem**
Les noms des variables doivent être en majuscule et commencer par une lettre minuscule
==> toutes les variable sont en minuscule. 

**Steps to reproduce?**
NA

**Comment by johnshea** [comment]
Hi @Benimacle 

Thank you for reporting this issue.

It is a [duplicate](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/264) that is scheduled to be fixed so I will be closing this issue.

Hope you are enjoying the course!

Regards.
