### ISSUE TITLE
subtraction error

### ISSUE THREAD

**Issue by mkaomwakuni** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#356]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**
Message formatting

**Describe the problem**

 I  came across an issue when you have this it would be more accurate to use the thirdNumber instead of the secondNumber as the parameter for calculating the difference

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
before the fix looks this 
![c1](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/61048381/cb759337-5dfd-4a33-8172-e1a4d0150407)
after the fix should be like this
![c2](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/61048381/ec5e65c3-96da-4891-b79e-b02b15214042)

**Comment by johnshea** [comment]
Hi @mkaomwakuni 

Thank you for writing in with this concern.

The function is meant to be using the parameter names `firstNumber` and `secondNumber` in a general way.

It is not meant to represent the variables `firstNumber` and `secondNumber` declared in the code.

I do understand your point that these could be improved.

Hope you are enjoying the course!

Regards.
