### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Scovela** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#358]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#7**

**8. Arrange the text elements in a row and column: Trailing lambda syntax**

**The text is incomprehensible and does also not correspond with code given.**

"Instead of putting the function body along with the function name within the parentheses({}), you put the parentheses along with the function body after the function name." 

The above text is incomprehensible for me as a developer. And the explanation after (about lambda) is also a mystery to me, but maybe because of the beginning. In the image above I see a very standard function defninition syntax, so is this related to the trailing lambda syntax? Also {} are called parentheses in your text.

**Comment by johnshea** [comment]
Hi @Scovela 

Thank you for writing in and bringing this to our attention.

The team is updating the lesson and will revise this to make it clearer to the students.

Hope you are enjoying the course!

Regards.
