### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by patrickdark** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#360]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2

**In which task and step of the codelab can this issue be found?**
Create and use functions in Kotlin: Return a value from a function

**Describe the problem**
The blockquoted error message “A 'return' expression required in a function with a block body ('{...}')” should appear after the text “Run your code. You'll get the error.” Instead, it appears at the end of the step (Step 2) text.

Alternatively, “the error” should be “an error”.

**Comment by johnshea** [comment]
Hi @patrickdark 

Thank you for writing in to bring these issues to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
