### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by wrighw2093** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#361]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#1 

**In which task and step of the codelab can this issue be found?**
Step 2:  Define and Call a Function in Kotlin

**Describe the problem**
The code using the Unit default return type does not return the declared output when copied into the Kotlin Playground.  According to the lesson, the below code should result in Happy Birthday, Rover! and You are now 5 years old!.  

Instead, the Kotlin Playground returns: No main method found in project.  

fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}

**Steps to reproduce?**
1. Go to the link I posted above.  
2. Then copy the link into the Kotlin Playground.  
3. Run the program
4. See error: No main method found in project.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Failed Code](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/50055152/c6882e76-e84b-467f-aadb-e7a45cf72c8a)

**Comment by johnshea** [comment]
Hi @wrighw2093 

Thank you for writing in with your issue.

The code you shared is a continuation from the previous step. It does not stand alone.

Following from Step 2 through "The Unit type", your code should look like this...

<img width="876" alt="Screenshot 2023-07-19 at 2 40 28 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/800272da-6bcd-4794-8c4f-23cdb8160c83">

If you have any further doubts, please do not hesitate to create a new issue.

Hope you are enjoying the course!

Regards.
