### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by ignacio5000** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#362]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
val is for declaring constants, not variables.
var is for declaring variables.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ignacio5000 

Thank you for writing in with your comment.

`val` is for declaring variables that are assigned a value once.
`var` is for variables that can have their value reassigned.

`val` and constants are similar but technically different.

For additional information please refer to the [Kotlin documentation](https://kotlinlang.org/docs/basic-syntax.html#variables).

Hope you are enjoying the course.

Regards.
