### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by AliGIran** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#363]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#6)**

**7. add another element**

**i use the exact code but get error for the second text box**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  flamingo
_API version of the emulator:_  33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @AliGIran 

Sorry to learn you are having difficulties with the lesson.

As you did not provide the requested information, we are unable to assist you further at this time.

Feel free to create a new issue with all the required information so we can help you.

Hope you are enjoying the course!

Regards.
