### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by t5181825** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#367]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

Override superclass methods from subclasses
2. In the SmartLightDevice subclass before the fun keyword of the turnOn() and turnOff() methods, add the override keyword: ...

**Describe the problem**

The parameters given here in this step 2 do not match the previous SmartLightDevice declaration, from step 7 of the previous task in the same codelab (deviceName instead of name, etc).

AND, the SmartLightDevice class does not yet contain turnOn() and turnOff() functions.

**Steps to reproduce?**    Nothing to reproduce, this is simply your (excellent) tutorial
1. Go to...
2. Click on...
3. See error...

**Versions**    Not required, I'm just working through your tutorial
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information** 
_Include screenshots if they would be useful in clarifying the problem._

None, I hope my description above is sufficient.   (It seems likely that something got updated, and this bit was missed?)

Congratulations on an excellent tutorial so far (Android Basics with Compose)

**Comment by t5181825** [comment]
Edit: Addendum:  the rest of this activity, Unit 2 Pathway 1 4: Use classes and objects in Kotlin.   From the previously described above point onwards in this activity, the descriptions (of how to continue adding to the Kotlin smart device practice code) do not match what came before.   For example, in the "Visibility modifiers" section, it says: _"1. In the SmartDevice superclass's deviceStatus property, add the protected modifier to the set() function:"_ - but the deviceStatus property in the SmartDevice superclass doesn't have a set() function. That property is instead referenced in the superclass's constructor, however.   This is just one example, there are other places where there is a mismatch.   It looks like part of the code and the text of this activity have been updated, but the rest of it hasn't been?   If it is wished to put this right, I might respectfully suggest that one of the authors could usefully work through this activity, as if learning it for the first time, building up the code as the activity describes, to discover all the places that don't match? (However, these small errors do not detract greatly, the general ideas being explained are still clear enough to learn from, these are not difficult examples.)

**Comment by johnshea** [comment]
Hi @t5181825 

Thank you for writing in and bringing these issues to our attention.

The lesson has been updated to address them and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
