### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by DamionG1** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#371]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1

**In which task and step of the codelab can this issue be found?**
Step 2

**Describe the problem**
Step 2 is not consistant with the Androidstudio Flamingo on description. On program load for "Greeting Card" the error in the software says "Gradle project sync failed. Basic functionality (e.g. editing, debugging)will not work properly"

**Steps to reproduce?**
Following Step 2 on the codelab up to this point

In this codelab, you create an Android app with the Empty Activity project template provided by Android Studio.

To create a project in Android Studio:

    Double click the Android Studio icon to launch Android Studio.

4853d32c0c91ae24.png

    In the Welcome to Android Studio dialog, click New Project.

new project open project and other options

The New Project window opens with a list of templates provided by Android Studio.

935c2d9a4df8b864.png

In Android Studio, a project template is an Android project that provides the blueprint for a certain type of app. Templates create the structure of the project and the files needed for Android Studio to build your project. The template that you choose provides starter code to get you going faster.

    Make sure the Phone and Tablet tab is selected.
    Click the Empty Activity template to select it as the template for your project. The Empty Activity template is the template to create a simple project that you can use to build a Compose app. It has a single screen and displays the text "Hello Android!".
    Click Next. The New Project dialog opens. This has some fields to configure your project.
    Configure your project as follows:

The Name field is used to enter the name of your project, for this codelab type "Greeting Card".

Leave the Package name field as is. This is how your files will be organized in the file structure. In this case, the package name will be com.example.greetingcard.

Leave the Save location field as is. It contains the location where all the files related to your project are saved. Take a note of where that is on your computer so that you can find your files.

Select API 24: Android 7.0 (Nougat) from the menu in the Minimum SDK field. [Minimum SDK](https://developer.android.com/guide/topics/manifest/uses-sdk-element) indicates the minimum version of Android that your app can run on.

c860e875eefd68b7.png

    Click Finish. This may take a while - this is a great time to get a cup of tea! While Android Studio is setting up, a progress bar and message indicates whether Android Studio is still setting up your project.

it is here the errors are shown and i cannot proceed further

**Versions**
_Android Studio version:_ 2022.2.1 Patch 2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/106623836/469fafde-efd1-4fb1-b000-6c66be4afa50)

**Comment by DamionG1** [comment]
[idea.log](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/files/11771294/idea.log)

**Comment by AvDjah** [comment]
From what I could find, I think you need to update your JDK version to 11 or above.
Other thing that you can do is :

build.gradle(project)

```
plugins {
    id 'com.android.application' version '8.0.0' apply false
    id 'com.android.library' version '8.0.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
}

```


build.gradle(:app)

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
```

**Comment by johnshea** [comment]
Hi @DamionG1 

Thank you for writing in with your issue.

We were unable to duplicate your issue.

Have you tried the suggestions provided by the other student?

Please try again with Android Studio Giraffe, which is the latest stable version.

If you are still having a problem and have the time, please create a new issue with all the requested information so we can pass it along to the appropriate team.

Hope you are enjoying the course!

Regards.
