### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ugugsoft** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#372]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?authuser=1&hl=ja&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%26hl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#4

**In which task and step of the codelab can this issue be found?**
ComposeQuadrant

**Describe the problem**
In the task, it says "Use androidx.compose.ui.graphics.Color.Green",
but in the solution code, like this
backgroundColor = Color(0xFFEADDFF)

**Steps to reproduce?**
See the solution code

**Versions**
None

**Additional information**
None

**Comment by johnshea** [comment]
Hi @ugugsoft 

Thank you for writing in with this issue.

The lesson has been updated to address it and has recently been republished.

Hope you are enjoying the course!

Regards.
