### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by GuySMowbray** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#373]
**URL of codelab**
Codelab 

**In which task and step of the codelab can this issue be found?**

4 edit the text

**Describe the problem**
Code snip

The class MainActivity : ComponentActivity() {
   override fun onCreate(savedInstanceState: Bundle?) {
       super.onCreate(savedInstanceState)
       setContent {
           GreetingCardTheme {
               // A surface container using the 'background' color from the theme
               Surface(
                   modifier = Modifier.fillMaxSize(),
                   color = MaterialTheme.colors.background
               ) {
                   Greeting("Android")
               }
           }
       }
   }
}
The description below the snip explains the code snip and refers to @composable functions. But this is confusing to newbies as there is no ref to @composables in the code snip.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @GuySMowbray 

Thank you for writing in with your comment regarding the lesson wording.

Your observation is being passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
