### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Grendeth9495** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#375]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#8

**In which task and step of the codelab can this issue be found?**

The whole thing.

**Describe the problem**

Did you think that introducing this many new topics in a module wouldn't discourage most new programmers? Class, inheritance, overrides, fine, okay. private, protected, internal? A bit much for a new programmer to worry about. range values and explicit setters and getters? Come on, in the same module you're introducing classes? Might as well ask them to create a stack and work out a bubble sort. This is way too much for someone who's never programmed before. You could have just made the min and max values into vals and use it in a super class, while yes, it is a roundabout and clumsy manner to do so, I see no compelling reason add more jargon and syntax to an already abstract concept such as classes. The whole point of Kotlin was to be a softly typed, less boilerplate heavy implementation of Java. This module adds in complexity that isn't needed for someone who's likely never so much as de-fragmented a hard drive or set a static IP, let alone create classes, instance or used type setting. I understand the desire to educate and help the next generation of programmers along, but as someone who has programming experience prior to this, this is too much for one module. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Grendeth9495 

Thank you for writing in and providing your feedback on the lesson content and pacing.

As an experienced developer you provide a valuable point of view.

Your feedback will be shared with the learning team so it can reviewed and the course improved where possible.

Hope you are still enjoying the course!

Regards.
