### ISSUE TITLE
Install Android Studio: Android Basics with Compose -- Studio won't start on default installations of Windows 11/10 LTSC or after recommended settings for Windows were applied

### ISSUE THREAD

**Issue by claudiusraphael** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#376]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-install-android-studio#2

**In which task and step of the codelab can this issue be found?**
3. Windows: Download and install Android Studio

**Describe the problem**
Android Studio will install but not start on Windows 11 and Windows 10 LTSC with default-settings, as well as on Windows 10 when the recommended safety-settings are applied, because  in "Windows Security" under "App & Browser control" the setting for "Force randomization for images (Mandatory ASLR)  is set to "Use default (On)"

**Steps to reproduce?**
1. Execute the installer of Android Studio in an uncustomized/default installation of Windows 11 or Windows 10 LTSC or apply the recommended defaults in Windows 10
2. After the installation is done attempt to launch Android Studio
3. A dialogue will show "The application was unable to start correctly (0xc000007b). Click OK to close the application."
4. To fix it: Open "Windows Security" -> "App & browser control" -> "Program Settings" -> "Add program to customize" -> "Add by program name" -> "studio64.exe"
5.  Enable "Override system settings" on "Force randomization for images (Mandatory ASLR)"
6. Set the status of Mandatory ASLR to "Off"
7. Attempt to launch Android Studio, now it will start.

**Versions**
_Android Studio version:_ 2022.2.1 Patch 2
_API version of the emulator:_ n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/84972255/97cac9ac-1859-4a5c-9528-c54401c9d162)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/84972255/14b6a464-d6ab-40b0-b40b-25898675c320)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/84972255/204a2e9c-6110-4775-8040-33b7d956728d)

**Comment by johnshea** [comment]
Hi @claudiusraphael 

Thank you for writing in with this issue and providing screenshots and steps to reproduce it.

Your observation is being passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
