### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by mark-yieh** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#377]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4

**In which task and step of the codelab can this issue be found?**
Function Signature

**Describe the problem**
The function signature does NOT include the return type.

**Steps to reproduce?**
1. Go to url above
2. Scroll to the section that's titled "Function Signature"
3. Observe that it says "So far you've seen how to define the function name, inputs (parameters), and outputs. These are collectively known as the function signature. The function signature consists of everything before the opening curly brace and is shown in the following code snippet."
```fun birthdayGreeting(name: String, age: Int): String```
5. However, this is a false statement as the return type is not part of the function signature. You cannot have 2 functions defined that only differ in their return type.

**Versions**

**Additional information**
![Screenshot 2023-06-23 000448](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/35759250/fd2e7912-b5fb-40ba-b06f-33f60da1ecab)

**Comment by johnshea** [comment]
Hi @mark-yieh 

Thank you for writing in and bringing this to our attention.

The lesson content has been updated in the "Function Signature" section and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
