### ISSUE TITLE
Solution code: Use classes and objects in Kotlin

### ISSUE THREAD

**Issue by thabotswana** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#378]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#9

**In which task and step of the codelab can this issue be found?**
The final solution

**Describe the problem**
When testing the solution code, I encountered the following errors:

- Modifier 'private' is not applicable to 'value parameter'
- Unresolved reference: minValue
- Unresolved reference: maxValue
- Cannot find a parameter with this name: deviceName
- Cannot find a parameter with this name: deviceCategory
- No value passed for parameter 'name'
- No value passed for parameter 'category'

**Steps to reproduce?**
1. Run the solution code in [Kotlin Playground](https://developer.android.com/training/kotlinplayground).
2. See the above-mentioned errors

**Additional information**
I ended up making changes and ran the following code which worked:

```
import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

open class SmartDevice(val name: String, val category: String) {
    var deviceStatus = "online"
    	protected set
    
    open val deviceType = "unknown"

    open fun turnOn(){
        deviceStatus = "on"
    }

    open fun turnOff(){
        deviceStatus = "off"
    }

}

class SmartTvDevice(name: String, category: String) : SmartDevice(name, category) {
    
    override val deviceType = "Smart TV"
    
    private var speakerVolume by RangeRegulator(initialValue = 2, minValue = 0, maxValue = 100)

    private var channelNumber by RangeRegulator(initialValue = 1, minValue = 0, maxValue = 200)
        
    override fun turnOn() {
        super.turnOn()
        println("$name is turned on. Speaker volume set to $speakerVolume and channel number is " +
                "set to $channelNumber.")
    }

    override fun turnOff() {
        super.turnOff()
        println("$name is turned off")
    }
    

    fun increaseSpeakerVolume() {
        speakerVolume++
        println("Speaker volume increased to $speakerVolume.")
    }

    fun nextChannel() {
        channelNumber++
        println("Channel number increased to $channelNumber.")
    }
}

class SmartLightDevice(deviceName: String, deviceCategory: String) : SmartDevice(deviceName, deviceCategory) {
    
    override val deviceType = "Smart Light"
    
    private var brightnessLevel by RangeRegulator(initialValue = 2, minValue = 0, maxValue = 100)
        
    override fun turnOn() {
        super.turnOn()
        brightnessLevel = 2
        println("$name is turned on. The brightness level is $brightnessLevel.")
    }

    override fun turnOff() {
        super.turnOff()
        brightnessLevel = 0
        println("$name is turned off")
    }    

    fun increaseBrightness() {
        brightnessLevel++
        println("Brightness increased to $brightnessLevel.")
    }
}

class SmartHome(
    val smartTvDevice: SmartTvDevice,
    val smartLightDevice: SmartLightDevice
) {
    
    var deviceTurnOnCount = 0
    	private set
    
    fun turnOnTv() {
        deviceTurnOnCount++
        smartTvDevice.turnOn()
    }
    fun turnOffTv() {
        deviceTurnOnCount--
        smartTvDevice.turnOff()
    }
    fun increaseTvVolume() {
        smartTvDevice.increaseSpeakerVolume()
    }
    fun changeTvChannelToNext() {
        smartTvDevice.nextChannel()
    }
    fun turnOnLight() {
        deviceTurnOnCount++
        smartLightDevice.turnOn()
    }
    fun turnOffLight() {
        deviceTurnOnCount--
        smartLightDevice.turnOff()
    }
    fun increaseLightBrightness() {
        smartLightDevice.increaseBrightness()
    }
    fun turnOffAllDevices() {
        turnOffTv()
        turnOffLight()
    }
}

class RangeRegulator(
    initialValue: Int,
    private val minValue: Int,
    private val maxValue: Int
) : ReadWriteProperty<Any?, Int> {

    private var fieldData = initialValue

    override fun getValue(thisRef: Any?, property: KProperty<*>): Int {
        return fieldData
    }

    override fun setValue(thisRef: Any?, property: KProperty<*>, value: Int) {
        if (value in this.minValue..this.maxValue) {
            fieldData = value
        }
    }
}

fun main() {
    val smartHome = SmartHome(
    SmartTvDevice("Android TV", "Entertainment"),
    SmartLightDevice("Google light", "Utility")
)


    smartHome.turnOnTv()
    smartHome.turnOnLight()
    println("Total number of devices currently turned on: ${smartHome.deviceTurnOnCount}")
    println()

    smartHome.increaseTvVolume()
    smartHome.changeTvChannelToNext()
    smartHome.increaseLightBrightness()
    println()

    smartHome.turnOffAllDevices()
    println("Total number of devices currently turned on: ${smartHome.deviceTurnOnCount}.")
}
```

**Comment by Razviter** [comment]
Tell me where i can find a solution for "try this challenge"?

[11. Try this challenge](https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#10)

* In the `SmartDevice` class, define a `printDeviceInfo()` method that prints a `"Device` `name:` `$name,` `category:` `$category,` `type:` `$deviceType"` string.
* In the `SmartTvDevice` class, define a `decreaseVolume()` method that decreases the volume and a `previousChannel()` method that navigates to the previous channel.
* In the `SmartLightDevice` class, define a `decreaseBrightness()` method that decreases the brightness.
* In the `SmartHome` class, ensure that all actions can only be performed when each device's `deviceStatus` property is set to an `"on"` string. Also, ensure that the `deviceTurnOnCount` property is updated correctly.

After you're done with the implementation:

* In the `SmartHome` class, define an `decreaseTvVolume()`, `changeTvChannelToPrevious()`, `printSmartTvInfo()`, `printSmartLightInfo()`, and `decreaseLightBrightness()` method.
* Call the appropriate methods from the `SmartTvDevice` and `SmartLightDevice` classes in the `SmartHome` class.
In the `main()` function, call these added methods to test them.

**Comment by johnshea** [comment]
Hi @thabotswana 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address these issues and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
