### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by Athena-Nemesis** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#379]
Bonjour, 

Quand j'ajoute la ligne : import androidx.compose.ui.graphics.Color
elle reste en gris, et ne veux pas me la valider, quand je réorganise tout elle disparaît. 
Pouvez vous m'aider ? 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Athena-Nemesis 

Thank you for noticing this issue and reporting it.

The lesson content has been updated to address it.

The updated lesson content has already been republished to production.

If you are still experiencing an issue, please do not hesitate to create a new issue.

Hope you are enjoying the course!

Regards.
