### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Mold1988** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#381]
**[URL of codelab*](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2)*

**In which task and step of the codelab can this issue be found?**
[Create and use functions in Kotlin](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions)

Create and use functions in Kotlin > Return a Value from a function

<img width="667" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/130028292/5b46d5f9-31b8-4da7-bff9-b3de47c99060">

**Describe the problem**

When I ran the code under the "The Unit Type" to Kotlin Playgound its not working.

<img width="728" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/130028292/b1a90e96-5df9-4f7b-bc71-f29eaac75433">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Mold1988 

Thank you for writing in.

This code is meant to be a continuation from the previous step.

Please refer to this [issue](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/361) for additional information.

Hope you are enjoying the course!

Regards.
