### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by SedSim** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#384]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables#9

**In which task and step of the codelab can this issue be found?**
In the Column part

**Describe the problem**
The text is not centering in the middle of the screen of the emulator as described after copying the source code to correct all mistakes.

**Steps to reproduce?**
Add "modifier = modifier.fillMaxSize()"
under the line with "verticalArrangement = Arrangement.Center,"

**Versions**
_Android Studio version:_ 2022.2.1 Patch 2
_API version of the emulator:_ API 31

**Comment by AvDjah** [comment]
Can you share the code you are executing, it would be more helpful I guess.

**Comment by SedSim** [comment]
The original part of the code that needs to be corrected is this one:

Column(
       verticalArrangement = Arrangement.Center,
       modifier = modifier
   ) {
       Text(
           text = message,
           fontSize = 100.sp,
           lineHeight = 116.sp,
           textAlign = TextAlign.Center
       )
       Text(
           text = from,
           fontSize = 36.sp,
           modifier = Modifier
               .padding(16.dp)
               .align(alignment = Alignment.End)
       )
   }

**Comment by AvDjah** [comment]
This works on my side, not sure what the issue is. Can you share the emulator output screenshot and the full code?

**Comment by SedSim** [comment]
> This works on my side, not sure what the issue is. Can you share the emulator output screenshot and the full code?

Do you have a line with:

"modifier = modifier.fillMaxSize()" ???

Because without it the whole content should be at the top of the screen. I think that was the problem.

I would like to note: I'm still a beginner and this confused me when following the codeLab tutorials.

Anyways, thanks for your support and help.

**Comment by SedSim** [comment]
The solutuion should actually look like this:

[https://developer.android.com/static/codelabs/basic-android-kotlin-compose-text-composables/img/74dd02e4f7fa1780_856.png](https://developer.android.com/static/codelabs/basic-android-kotlin-compose-text-composables/img/74dd02e4f7fa1780_856.png)

But it does not?

**Comment by johnshea** [comment]
Hi @SedSim 

Thank you for writing in with your issue.

I followed the lesson steps on the latest stable version of Android Studio and it is centering as expected.

If you are still experiencing a problem, please create a new issue and provide your code and emulator screenshot so we can see what you are doing and help troubleshoot it with you.

Hope you are enjoying the course!

Regards.
