### ISSUE TITLE
Use classes and objects in Kotlin - part 11. Try this challenge

### ISSUE THREAD

**Issue by skhoosh** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#385]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#10

**In which task and step of the codelab can this issue be found?**
Challenge 

**Describe the problem**
Could you please provide the solution for the challenge?

**Comment by johnshea** [comment]
Hi @skhoosh 

Thank you for writing in with you question.

At this time we are not providing solutions to challenges.

If it changes in the future, we will update the lessons accordingly.

Hope you are enjoying the course!

Regards.
