### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by vicogimenez** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#390]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#2

**In which task and step of the codelab can this issue be found?**
The diagram that is under the sentence "The following diagram is an example of annotated function:", where annotations are explained.

**Describe the problem**
There is a missing colon (':') on the modifier part of the function signature. It is stated as "modifier Modifier" and it should be "modifier: Modifier".

**Steps to reproduce?**
N/A - it is just about the content of a static image.

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![screenshot](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/2934013/2abe7f29-229a-4cb2-a389-95c7658af92b)

**Comment by johnshea** [comment]
Hi @vicogimenez 

Thank you for noticing and reporting this issue.

The image has been updated and it will be republished in the near future.

Hope you are enjoying the course!

Regards.
