### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by JJ-connect** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#392]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8)

**In which task and step of the codelab can this issue be found?**
Build a simple app with text composables > Step 9 Add greeting to the app > Adopt good practice

**Describe the problem**
The instructions are to "Update the modifier parameter in the `GreetingText()` as follows"
But then the `onCreate` codeblock is exactly the same as last edited (see image at the beginning of step 9)
The `GreetingText()` codeblock is the same as previously but with the `.padding(8.dp)` removed.

When the text says "It is a good practice to pass the modifier attribute(s) along with the modifier from the parent composable.", it is not clear what this in relation to the two given codeblocks.

What is the best practice to follow here? What is this message trying to say?

**Steps to reproduce?**
1. Go to: Build a simple app with text composables > Step 9
2. See error: confusing wording

**Versions**
_Android Studio version:_ n/a
_API version of the emulator:_ n/a

**Additional information**
See below state of the codeblocks for examples:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/109976286/49a868ef-1fd8-452e-91b9-c4e1b6e68ee4)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/109976286/c1eb3c9c-4d31-4325-a334-01bdb52d29b4)

Then the instruction to update to nearly the same code:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/109976286/d0df7700-3a60-4451-ba41-13d1ba061611)

**Comment by johnshea** [comment]
Hi @JJ-connect 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
