### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by hardik89** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#394]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Learn more resource section has a broken link for Pixel Density

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10
2. Click on Pixel density
3. See error 404

**Comment by johnshea** [comment]
Hi @hardik89 

Thank you for writing in with this issue.

The lesson has been updated to address it and the lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
