### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by MyNameIsLala** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#396]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to... code/split screen not showing - can't figure it out or what to hit! 
![Screenshot 2023-07-25 175543](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/32015273/376f0c51-2fb2-4b97-8126-f875e458e5e9)

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @MyNameIsLala 

Thank you for writing in with your issue.

From the screenshot, I am not sure what lesson or step you are on.

If you are still having an issue, please create a new issue and provide all the required information so we can help you troubleshoot further.

Hope you are enjoying the course!

Regards.
