### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by bordenc** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#398]
**Tutorial URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**In which task and step of the codelab can this issue be found?**
Task 9 step 2

**Describe the problem**
Tutorial omits instructions to `import`:

1. `androidx.compose.foundation.layout.padding`,
2. `androidx.compose.ui.Alignment`,
3. `androidx.compose.ui.text.style.TextAlign`; and
4. `androidx.compose.ui.unit.dp`

which causes **Unresolved Reference** errors. I figured out the correct imports from the following task "Get the solution code." I'm not sure whether Google expects students to guess where these imports are hiding. It's kinda mean, though, as some imports aren't obvious.

**Comment by johnshea** [comment]
Hi @bordenc 

Thank you for writing in with your issue.

The missing import statements should have been autoimported by Android Studio as needed.

I would suggest that you check that you have your Android Studio configured for autoimports.

Hope you are enjoying the course!

Regards.
