### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by mourahi** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#4]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?hl=en#4

**Describe the problem**
Link to github is not correcte (Page not found)

**Comment by osuleymanova** [comment]
@mourahi 
Thank you for reaching out to us. The issue is not reproducible. Please check the links again and if you face the same issue please provide more details and screenshots.
