### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by vivek-sridhar** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#400]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#2

**In which task and step of the codelab can this issue be found?**
3

**Describe the problem**
"In the variable declaration, the variable name follows the val keyword."
val is a final keyword which makes it such that you can alter the expression. It is technically not a variable keyword.
var is the correct keyword to declare a variable.

**Steps to reproduce?**
1. Go to... - https://developer.android.com/training/kotlinplayground?authuser=1
2. Enter code in Kotlin playground:
3. fun main() {
    val count: Int = 2
    count++
    println(count)
}
4. See error... - Val cannot be reassigned

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @vivek-sridhar 

Thank you for writing in with your concern.

According to the [kotlinlang.org](https://kotlinlang.org/docs/basic-syntax.html#variables) website, "Read-only local variables are defined using the keyword val."

Hope you are enjoying the course!

Regards.
