### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Sooraj-Mlahi** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#402]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**

add an image composable

**Describe the problem**

Render Issue when add GreetingImage function

**Steps to reproduce?**
If you have the same code as shown in the above task then go to "MainActivity.kt" then click on split or Design, it displays the message Render issue instead of preview

**Versions**
_Android Studio version:_  Giraffe
_API version of the emulator:_   API 34

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Sooraj-Mlahi 

Thank you for writing in with your issue but we were unable to duplicate your issue.

If you are still having a problem and have the time, please create a new issue with all the requested information so we can pass it along to the appropriate team. Please also include your code and screenshots.

Hope you are enjoying the course!

Regards.
