### ISSUE TITLE
Text composables: Android Basics with Compose - Create an Empty Activity should be Create an Empty Compose Activity

### ISSUE THREAD

**Issue by LinuxBrickie** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#403]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#1

**In which task and step of the codelab can this issue be found?**

2. Set up a Happy Birthday app - Create an Empty Activity project - 2. In the New Project dialog, select Empty Activity and then click Next.

**Describe the problem**

The instructions should say Create an Empty *Compose* Activity rather than Empty Activity. If you follow the instructions and Create an Empty Activity project then not only does running it show a different thing to the screenshot but there is also no @Composable Greeting or GreetingPreview functions generated for you.

**Steps to reproduce?**
1. Follow instructions on Set up a Happy Birthday app to Create an Empty Activity project
2. Build and run to get something that shows Hello World! in the centre of the screen.
3. Note the absence of Greeting and GreetingPreview functions in MainActivity.kt.

**Versions**
Android Studio Electric Eel | 2022.1.1 Patch 2 (Linux)
Don't know how to get the _API version of the emulator but it's not important for this issue

**Additional information**

**Comment by johnshea** [comment]
Hi @LinuxBrickie 

Thank you for writing in with your issue.

From your report, you are using an older version of Android Studio.

The prompts have changed in newer versions which is why you are experiencing this issue.

Please update to the latest stable version of Android Studio as this should resolve your issue.

Hope you are enjoying the course!

Regards.
