### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by nyam-aste** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#405]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#5

**In which task and step of the codelab can this issue be found?**
Your turn! In the MainActivity.kt file, scroll to the GreetingText() function and notice the padding attribute.

**Describe the problem**
the padding attribute to notice isn't in the GreetingText() function but in the GreetingImage() function where a call to the GreetingText() function is made and the padding attribute to notice is on the "modifier" passed as argument

**Comment by johnshea** [comment]
Hi @nyam-aste 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
