### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by JohnWifi** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#406]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Android Studio doesn't charge my emulator,only opens the window of the my emulator but doesn't charges, what i can do,
i ask you please that improve android studio because ¡ i passed 3 days trying to install the intel haxm!, please help, thank you for your attention

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @JohnWifi 

Thank you for writing in regarding your issues with the emulator and Android Studio.

It is being passed along to the team for their review.

Hope you are enjoying the course!

Regards.
