### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by oldrefery** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#408]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10

**In which task and step of the codelab can this issue be found?**
11. Conclusion

**Describe the problem**
Section "Learn more"
1. Link to "Pixel Density" is incorrect
[Pixel density](https://m3.material.io/design/layout/pixel-density.html#pixel-density)
2. Doesn't work the link to "Kotlin for Jetpack Compose"
[Kotlin for Jetpack Compose](https://developer.android.com/jetpack/compose/kotlin)

**Steps to reproduce?**
1. Go to...  step 11. Find the last block "Learn more" 
2. Click on... "Pixel Density
3. See error... Open a new web page with the info "This page cannot be found
Try a different destination or head back to the [homepage](https://m3.material.io/)."
4. Click on... "Kotlin for Jetpack Compose"
5. See error... The new web-page doesn't open

**Versions**
_Android Studio version:_  Android Studio Giraffe | 2022.3.1
_API version of the emulator:_ API 33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @oldrefery 

Thank you for writing in to bring this to our attention.

re: "Pixel Density" link - This has been corrected and the updated lesson will be republished again in the near future.

re: "Kotlin for Jetpack Compose" link - This link works correctly for me. If you have time, please retry it and if you are still having an issue, create a new issue and provide a screenshot and any other relevant information so we can investigate further.

Hope you are enjoying the course!

Regards.

**Comment by oldrefery** [comment]
Do not close the bug before posting. In case you want me to verify the fixes
