### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Zoliam05** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#409]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Les variables ne sont pas déclarées entre les parenthèses suivant le nom de la fonction. Pourquoi?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Zoliam05 

As you did not provide enough information regarding your question, I am not sure what is the issue so I am unable to assist you further.

If you still have a question, please do not hesitate to create a new issue and provided at least the requested information.

Hope you are enjoying the course!

Regards.
