### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by NuriG** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#41]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

<img width="1058" alt="Снимок экрана 2022-07-21 в 12 22 46" src="https://user-images.githubusercontent.com/52043289/180179290-19552d9d-0e5c-499c-a40c-08cefa74dd01.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

help me please! don't work your instruction

**Comment by funnygerman** [comment]
You probably get wrong auto import.
The right import should be `import androidx.compose.foundation.Image`

**Comment by osuleymanova** [comment]
@NuriG 
Thank you for reaching out to us. It would be nice to see the full file MainActivity.kt so we could help with troubleshooting. For now I may suggest checking the list of imported libraries: 

![Screen Shot 2022-09-19 at 3 23 13 PM](https://user-images.githubusercontent.com/86437155/191130529-57c64421-7462-4083-ae97-aa941503a001.png)

If it doesn't help please feel free to reopen the ticket by providing the required information and visual proof.
