### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Krutik1302** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#410]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems

**In which task and step of the codelab can this issue be found?**
Compose article

**Describe the problem**
I can not download the image from the link in github

**Steps to reproduce?**
1. Go to Resorce in the page Compose artical
2. Click on "this image"
3. See error that image can not be downloaded

**Versions**
_Android Studio version:_ 2022.3.1
_API version of the emulator:_ 28

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by brettyance** [comment]
I'm not with Google, but if there *was* an issue, it's fixed now.

**Comment by johnshea** [comment]
Hi @Krutik1302 

Thank you for writing in with your issue.

I can confirm that the link to the image is working.

It is possible that link is being blocked depending on where you are located in the world which is beyond our control.

Hope you are enjoying the course!

Regards.
