### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by putterfly** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#411]
[**URL of codelab**](https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-1?hl=zh-cn)

**In which task and step of the codelab can this issue be found?**
ALL especially in Section 4 'using class and object in kotlin

**Describe the problem**

very low-quality  Chinese translation, hard to read, hard to understand, the translator himself seems like is a native Chinese speaker but paying as less time as he can to just finish the job.

Please rewrite them, please.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @putterfly 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
