### ISSUE TITLE
Text composables: Android Basics with Compose - dead link

### ISSUE THREAD

**Issue by psabadac** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#412]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

Step 11
**Describe the problem**
Dead link for Pixel Density

https://m3.material.io/design/layout/pixel-density.html#pixel-density

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10
2. Click on Pixel Density Link
3. See error

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @psabadac 

Thank you for writing in and bringing this issue to our attention.

It has been fixed and the lesson will be republished again in the near future.

Hope you are enjoying the course.

Regards.
