### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by seyckra** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#414]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
"Override superclass methods from subclasses" - Step 2 

**Describe the problem**
Nowhere up to this point are we told to create turnOn() and turnOff() methods in the SmartLightDevice or SmartTvDevice subclasses but this step asks us to put the override keyword in front of them

**Comment by johnshea** [comment]
Hi @seyckra 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
