### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by ronniedroid** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#415]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5

**In which task and step of the codelab can this issue be found?**
- Variable names should be in camel case and start with a lowercase letter.

**Describe the problem**
You are not doing a good job if showing this point to the learner.

Proposed solutions: 
- change the sentence to "Variable names should be in camelCase and start with a lowercase letter."
- change the variable name in the example form `discount` to `discountAmount`

**Additional information**
![kotlin-variables](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/9327361/a2bf5c77-cf11-4cec-8c38-637c34bbd20e)

**Comment by johnshea** [comment]
Hi @ronniedroid 

Thank you for writing in with your suggestions regarding the lesson wording.

They are being passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
