### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by ejtorcello** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#417]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

file:///C:/Users/Jose/AndroidStudioProjects/GreetingCard/app/src/main/java/com/example/greetingcard/MainActivity.kt:21:34

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
Impossible to keep up with the steps
**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ejtorcello 

Thank you for writing in.

The link you provided is for your personal computer so it is not accessible.

If you are still having an issue, please provide all the required information and screenshots so we can try to assist you further.

Hope you are enjoying the course.

Regards.
