### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by scropion86** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#418]
**URL of codelab**

[](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10)

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

in learn more link the link to [Pixel density](https://m3.material.io/design/layout/pixel-density.html#pixel-density) is broken

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @scropion86 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course.

Regards.
