### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by hasbalaban** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#42]
**(https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#7)**

**8**

**message: String, from: String -> we have 2 variable but we use one variable , variable is "from",  but output was merge of 2 variable**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @hasbalaban 

The first variable is being taught in step "[Add a new text element](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables)"

The step you are referring to is implementing the second variable `from` as you have noted.

Please review the step mentioned and see if that resolve your issue.

If you are still having an issue, please do not hesitate to open a new issue.

Hope you are enjoying the course!

Regards.
