### ISSUE TITLE
This is not a kotlin exercise

### ISSUE THREAD

**Issue by fox-zhw** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#420]
**[URL of codelab](https://developer.android.google.cn/courses/pathways/android-basics-compose-unit-2-pathway-1?hl=zh-cn)**

**Comment by brettyance** [comment]
I am not with Google.

If you go to the bottom of the page and select another language, it goes to the correct lab.

**Comment by johnshea** [comment]
Hi @fox-zhw 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
