### ISSUE TITLE
Challenge section on classes and objects in kotlin

### ISSUE THREAD

**Issue by wingsofgreed** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#422]
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#10

**In which task and step of the codelab can this issue be found?**

Is not on the codelab is on the kotlinplayground when you are doing the challenge on the classes and objects in kotlin.
**Describe the problem**
When i realize the challenge and  i was testing my solution it answer my like this: 
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name "getSpeakerVolume" with signature "()I" in class file SmartTvDevice
 at java.lang.ClassLoader.defineClass1 (:-2) 
 at java.lang.ClassLoader.defineClass (:-1) 
 at java.security.SecureClassLoader.defineClass (:-1) 

And as you may notice on the code that i paste here there is no double "getSpeakerVolume" not only on smartTvDevice Class but on the whole document.
This is the code:

import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

open class SmartDevice(val name: String, val category: String) {
    var deviceStatus = "off"
        protected set

    open val deviceType = "unknown"

    // Se debe declarar speakerVolume y channelNumber como propiedades dentro de SmartDevice
    private var speakerVolume by RangeRegulator(initialValue = 0, minValue = 0, maxValue = 100)
    private var channelNumber by RangeRegulator(initialValue = 1, minValue = 0, maxValue = 200)
 
    open fun turnOn(){
        deviceStatus = "on"
    }

    open fun turnOff(){
        deviceStatus = "off"
    }

    fun isDeviceOn(): Boolean {
        return deviceStatus == "on"
    }

    open fun decreaseVolume(){
        speakerVolume--
        println("Speaker volume decreased to $speakerVolume.")// reto2
    }

    open fun previousChannel() {
        channelNumber--
        println("Channel number decreased to $channelNumber.")//reto 2
    }

    fun printDeviceInfo() { //instruccion 1 reto, no debe ser open?
        println("Device name: $name, category: $category, type: $deviceType")//instruccion 1 reto
    }
}

class SmartTvDevice(deviceName: String, deviceCategory: String) : 
    SmartDevice(name = deviceName, category = deviceCategory) {

    override val deviceType = "Smart TV"

    private var speakerVolume by RangeRegulator(initialValue = 0, minValue = 0, maxValue = 100)
    
    // Declaración de channelNumber dentro de SmartTvDevice
    private var channelNumber by RangeRegulator(initialValue = 1, minValue = 0, maxValue = 200)

    override fun turnOn() {
        super.turnOn()
        println(
            "$name is turned on. Speaker volume is set to $speakerVolume and channel number is " +
                "set to $channelNumber."
        )
    }

    override fun turnOff() {
        super.turnOff()
        println("$name turned off")
    }

    fun increaseSpeakerVolume() {
        speakerVolume++
        println("Speaker volume increased to $speakerVolume.")
    }
    
    fun getSpeakerVolume(): Int {
        return speakerVolume
    }

    fun nextChannel() {
        channelNumber++
        println("Channel number increased to $channelNumber.")
    }
 
    // Método para obtener el número de canal
    fun getChannelNumber(): Int {
        return channelNumber
    }
    
}    
    
class SmartLightDevice(deviceName: String, deviceCategory: String) : 
    SmartDevice(name = deviceName, category = deviceCategory) {

    override val deviceType = "Smart Light"
        // Declarar brightnessLevel como propiedad en SmartLightDevice
    private var brightnessLevel by RangeRegulator(initialValue = 2, minValue = 0, maxValue = 100)

    override fun turnOn() {
        super.turnOn()
        brightnessLevel = 2
        println("$name turned on. The brightness level is $brightnessLevel.")
    }

    override fun turnOff() {
        super.turnOff()
        brightnessLevel = 0
        println("$name turned off")
    }
    
    fun increaseBrightness() {
        brightnessLevel++
        println("Brightness increased to $brightnessLevel.")
    }

    fun decreaseBrightness() {
        brightnessLevel--
        println("Brightness decreased to $brightnessLevel.") //reto 3
    }
}
    

class SmartHome(val smartTvDevice: SmartTvDevice, val smartLightDevice: SmartLightDevice) {
    // Métodos para controlar los dispositivos...
    
    var deviceTurnOnCount = 0
        private set
    
    fun turnOnTv() {
        if (smartTvDevice.isDeviceOn()) { //para la instrucción 4 asi solo se aplicara si esta enccendido.
            deviceTurnOnCount++
            smartTvDevice.turnOn()
        } else {
            println("${smartTvDevice.name} is off. Cannot turn on")// como instrucción solo funcionara.
        }// si esta previamente encendido.
    }
    
    fun turnOffTv() {
        if (smartTvDevice.isDeviceOn()) { //para la instrucción 4 asi solo se aplicara si esta enccendido.
        deviceTurnOnCount--
        smartTvDevice.turnOff()
        } else {
            println("${smartTvDevice.name} is already")// Ya esta apagado
        }
    }
    
    fun increaseTvVolume() {
        if (smartTvDevice.isDeviceOn()) {
            smartTvDevice.increaseSpeakerVolume()
        } else {
            println("${smartTvDevice.name} is off. Cannot increase the volume")//Solo si esta encendido.
        }
    }

    fun decreaseTvVolume() {
        if (smartTvDevice.isDeviceOn()) {
            smartTvDevice.decreaseVolume()
        } else {
            println("${smartTvDevice.name} is off. Cannot decrease the volume")//Solo si esta encendido.
        }
    }
    
    fun changeTvChannelToNext() {
        if (smartTvDevice.isDeviceOn()) {
            smartTvDevice.nextChannel()
        } else {
            println("${smartTvDevice.name} is off. Cannot change the channel")//Solo si esta encendido.
        }
    }
    
    fun changeTvChannelToPrevious() {
        if (smartTvDevice.isDeviceOn()) {
            smartTvDevice.previousChannel()
        } else {
            println("${smartTvDevice.name} is off. Cannot change the channel")//Solo si esta encendido.
        }
    }
    
    fun printSmartTvInfo() {
        if (smartTvDevice.isDeviceOn()) {
            println("Smart TV Information:")
            println("Device Name: ${smartTvDevice.name}")
            println("Device Type: ${smartTvDevice.deviceType}")
            println("Current Speaker Volume: ${smartTvDevice.getSpeakerVolume()}")
            println("Current Channel Number: ${smartTvDevice.getChannelNumber()}")
     } else {
            println("${smartTvDevice.name} is off. Cannot retrieve information.")
        }
    }
            
    
    fun turnOnLight() {
        if (smartTvDevice.isDeviceOn()) {
            deviceTurnOnCount++
            smartLightDevice.turnOn()
        } else {
            println("${smartLightDevice.name} is off. Cannot turn on.")//Solo si esta encendido.
        }
    }

    fun turnOffLight() {
        if (smartTvDevice.isDeviceOn()) {
            deviceTurnOnCount--
            smartLightDevice.turnOff()
        } else {
            println("${smartLightDevice.name} is already off.")//Solo si esta encendido.
        }
    }
    
    fun increaseLightBrightness() {
        if (smartLightDevice.isDeviceOn()) {
            smartLightDevice.increaseBrightness()
        } else {
            println("${smartLightDevice.name} is off. Cannot increase brightness.")
        }//Solo si - encendido.
    }
    
    fun decreaseLightBrightness() {
        if (smartLightDevice.isDeviceOn()) {
            smartLightDevice.decreaseBrightness()
        } else {
            println("${smartLightDevice.name} is off. Cannot decrease brightness.")
        }//Solo si - encendido.
    }
     
    fun printSmartLightInfo() {
        if (smartLightDevice.isDeviceOn()) {
            println("Smart Light  Information:")
            println("Device Name: ${smartLightDevice.name}")
            println("Device Type: ${smartLightDevice.deviceType}")
        } else {
            println("${smartLightDevice.name} is off. Cannot retrieve information.")
        } // instrucción 5
    }
     
     fun turnOffAllDevices() {
        turnOffTv()
        turnOffLight()
    }
}

class RangeRegulator(
    initialValue: Int,
    private val minValue: Int,
    private val maxValue: Int): 
    ReadWriteProperty<Any?, Int> {

    private var fieldData = initialValue

    override fun getValue(thisRef: Any?, property: KProperty<*>): Int {
        return fieldData
    }

    override fun setValue(thisRef: Any?, property: KProperty<*>, value: Int) {
        if (value in minValue..maxValue) {
            fieldData = value
        }
    }
}

fun main(){
    val smartHome = SmartHome(
        SmartTvDevice(deviceName = "Android TV", deviceCategory = "Entertainment"),
        SmartLightDevice(deviceName = "Google light", deviceCategory = "Utility")
    )

    smartHome.turnOnTv()
    smartHome.turnOnLight()
    println("Total number of devices currently turned on: ${smartHome.deviceTurnOnCount}")
    println()

    smartHome.increaseTvVolume()
    smartHome.decreaseTvVolume()
    smartHome.changeTvChannelToNext()
    smartHome.changeTvChannelToPrevious()
    smartHome.printSmartTvInfo()
    
    smartHome.increaseLightBrightness()
    smartHome.decreaseLightBrightness()
    smartHome.printSmartLightInfo()
    println()

    smartHome.turnOffAllDevices()
    println("Total number of devices currently turned on: ${smartHome.deviceTurnOnCount}.")
}

..

**Versions**
kotlinplayground

**Comment by johnshea** [comment]
Hi @wingsofgreed 

Thank you for writing in with your issue.

What I suspect is happening is that you are declaring variable speakerVolume in two classes, SmartDevice and SmartTvDevice, which is causing your issue.

The lesson does not have this variable in class SmartDevice.

Please make that correction and try running it again.

If you still have an issue, please create a new issue and provide all your code and screenshots so we can help you troubleshoot it further.

Hope you are enjoying the course!

Regards,

John
