### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Rohit18112001** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#424]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Phone number of the sender (String)
It should be integer
Phone number of the sender (Int)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Rohit18112001 

Thank you for writing in with your concern.

The team decided to use "String" as the field might contain non-numeric characters such as "()", "-",  or "+" to separate the digits and/or to indicate an international phone number.

Hope this helps and that you are enjoying the course!

Regards.
