### ISSUE TITLE
Information in Wrong Order and Misleads New Developers - Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by brettyance** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#425]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images

**In which task and step of the codelab can this issue be found?**
3. Add an image composable

**Describe the problem**

After the codelab instructs you to create the Image composable, it says, "Android Studio displays an error that says that, "None of the following functions can be called with the arguments supplied.""

It suggests that importing Image will fix this issue. The issue this fixes is the invalid reference (which is the actual issue.)

Once you import Image, the error the codelab gives is finally provided.

In order to clear that message, you must go to the next step, where it gives you the contentDescription value.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 

Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    vin.howe.themeGotham (0.0.7)
    IdeaVIM (2.1.0)

_API version of the emulator:_  n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

In the image provided by the codelab, Image has already been imported.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/46544627/eec9d4e8-5997-490b-9c8c-7c1e78f0dd08)

This step is what removes the error.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/46544627/8274baea-088d-4a49-9424-efd3644a23d5)

**Comment by johnshea** [comment]
Hi @brettyance 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
