### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by josebailon** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#426]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
Task: Build a simple app with text composables
Step 9; Add greeting to the app

**Describe the problem**
At the end of this step it shows an image of the message centered vertically on the screen on the phone but the code explained does not make the text centered vertically. Instead it shows it at the top of the phone screen.

**Steps to reproduce?**
1. Follow tutorial as it is

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1
_API version of the emulator:_ Pixel4 API 28

**Additional information**

In order to solve this I had to add modifier.fillMaxSize() to the Column element in the GretingText function and not only to the Surface component in onCreate function

**Comment by johnshea** [comment]
Hi @josebailon 

Thank you for writing in with your issue.

I followed the lesson's steps on the latest version of Android Studio and it is centering as the lesson describes.

If you are still experiencing a problem, please create a new issue and include your code and emulator screenshot so we can see what you are doing and help you troubleshoot it further.

Hope you are enjoying the course!

Regards.
