### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by AryaS01** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#427]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Task 3 in "diagram is an example of annotated function:"

**Describe the problem**
the word "fun" is actually the function declaration but it is mentioned as "name" being the function declaration.

**Steps to reproduce?**
1. Go to UNIT 1, PHASE 3:[Build a simple app with text composables]
2. Click on 3. What is Jetpack Compose?
3. See error in the annotations section in the diagram.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![error](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/99812089/4a4997f2-5665-4065-97d4-b7834bebe2fb)

**Comment by johnshea** [comment]
Hi @AryaS01 

Thank you for writing in with your concern.

The intention of the arrow pointing from "Function declaration" was meant to point to the whole line, it was not meant to indicate that "name" was the function declaration.

Hope you are enjoying the course!

Regards.
