### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by hypertetu** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#428]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
「[Empty Compose Activity] テンプレートをクリックし、プロジェクトのテンプレートとして選択します。Empty Compose Activity テンプレートは、Compose アプリの構築に使用できるシンプルなプロジェクトを作成するためのテンプレートです。単一の画面に「"Hello Android!"」というテキストが表示されます。」にある

"Empty Compose Activity"が存在しない

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @hypertetu 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
