### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by tsarahanael** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#429]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#7

**In which task and step of the codelab can this issue be found?**
in the step named "Arrange the text elements in a column"

**Describe the problem**
The screenshot giving the objective to achieve as an exercise gives the answer to said exercise

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/62378303/d35df4d0-d0cb-4de2-ae35-de41728f7983)

**Comment by johnshea** [comment]
Hi @tsarahanael 

Thank you for writing in with this issue.

The image has been updated to address it and the lesson will be republished in the near future.

Hope you are enjoying the course!

Regards.
