### ISSUE TITLE
Your first program: Android Basics with Compose

### ISSUE THREAD

**Issue by tocretpa** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#433]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program#4

**In which task and step of the codelab can this issue be found?**
5. Parts of a function

**Describe the problem**

Instead of: You can have many functions in your program or only a single one.

Maybe: There can be one or more functions in a Kotlin program.

Instead of: 
In other languages declare and define have different meanings.

Maybe: In some other (programming) languages declare and define can have different meanings.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @tocretpa 

Thank you for writing in with your suggestions regarding the lesson wording.

They have been passed along to the team so they can review and make changes as necessary.

Hope you are enjoying the course!

Regards.
