### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by trleminhduy** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#435]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?hl=vi&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Dvi%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**

task 3
**Describe the problem**

when i added this line into the first of MainActivity.kt, its still error 
import androidx.compose.foundation.Image

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/117763853/cdba60d5-5592-4e06-a835-b3bb1af7cc3e)
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/117763853/d21cf35a-f184-4e1a-88a0-26c66ced747e)

**Comment by johnshea** [comment]
Hi @trleminhduy 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
