### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by vanshtarar4** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#436]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
in 2nd task 

**Describe the problem**
In the second task  where we are required to download the image from github link.
the image is not available for downloading

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @vanshtarar4 

Thank you for writing in with your issue.

I can confirm that the link is working as expected.

Depending on where you are located in the world, it is possible that it is being blocked.

Feel free to use another image of your choosing if you are still unable to download the recommended one.

Hope you are enjoying the course!

Regards.
