### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by zx-81-16k** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#438]
**URL of codelab**
https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/new?assignees=&labels=&template=add-images-issue-template.md&title=Add+images%3A+Android+Basics+with+Compose

**In which task and step of the codelab can this issue be found?**
Step 3

**Describe the problem**
In part on adding composable Image, there is description 
that adding import is needed, but this is not sufficent
adding contentDescription is mandatory but
is described in another section as optional 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @zx-81-16k 

Thank you also for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
