### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by zx-81-16k** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#439]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Section 4

**Describe the problem**
In code example is used outadted MaterialTheme.colors reference
instead of current MaterialTheme.colorScheme

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @zx-81-16k 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
