### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by rafaover** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#44]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects&hl=en#6

**In which task and step of the codelab can this issue be found?**
Implement a relationship between classes -> Override superclass methods from subclasses

**Describe the problem**

// FIX "...use the var keyword to define a SmartDevice variable of SmartDevice type that instantiates a SmartTvDevice object that..."

4. In the main() function, use the var keyword to define a SmartDevice variable of SmartTvDevice type that instantiates a SmartTvDevice object that takes an "Android TV" argument and an "Entertainment" argument:

fun main(){
    var smartDevice: SmartDevice = SmartTvDevice("Android TV", "Entertainment")
}
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @rafaover,

Thanks for reaching out to us and reporting this issue. It is fixed:

![Screen Shot 2022-12-13 at 12 01 30 PM](https://user-images.githubusercontent.com/86437155/207432748-3a6db03c-d91c-4032-91d5-4292eeeee2d1.png)
