### ISSUE TITLE
Text composables: Android Basics with Compose, Step 9

### ISSUE THREAD

**Issue by shiv19** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#443]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
Step 9 (Add Greeting to the app) -> Adopt good practice

**Describe the problem**

The instruction says:
"It is a good practice to pass the modifier attribute(s) along with the modifier from the parent composable. Update the modifier parameter in the GreetingText() as follows:"

In the code that follows it, I notice that the ".padding(8.dp)" was removed from the Column widget.
So I expect this to be passed as an argument from the call to GreetingText.

```kt
GreetingText(
    message = "Happy Birthday Sam!",
    from = "From Emma",
    modifier = Modifier.padding(8.dp)
)
```

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/9407019/a338ec35-c33c-40a1-9903-65985bcf583c)

**Comment by johnshea** [comment]
Hi @shiv19 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
