### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by luqmanbuic** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#444]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator#2

**In which task and step of the codelab can this issue be found?**
the emulator for avd is terminated

**Describe the problem**

dear sir/madam, when i run the android virtual device then this issue comes: the emulator for avd is terminated.
i searched alot in youtube, google but not get my main point. please send me steps to follow.
thanks
![Screenshot (22)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/146452063/879fb879-67d8-40aa-b8d1-bbc66b5f8281)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1 Patch 2 for Windows
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by muhammadravi251001** [comment]
I suppose, that is because of lack of free space on your disk. Previously I am encountered this problem, until I check my almost-empty free space on my C.

**Comment by johnshea** [comment]
Thank you for trying to help @muhammadravi251001 

As there have been no additional follow ups, I will be closing this issue.
