### ISSUE TITLE
Use classes and objects in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Kalyan19111999** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#446]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
Override superclass methods from subclasses

**Describe the problem**
The word "method" in this line ("To provide this device-specific behavior, you need to override the turnOn() and turnOff() method defined in the superclass.") should be plural. This is the second line of the section

**Steps to reproduce?**
1. Go to URL of the codelab
2. Scroll to **Override superclass methods from subclasses section**
3. Check the word "method" in the second line of the first paragraph

**Versions**
_Android Studio version:_  NA
_API version of the emulator:_ NA 

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56710445/461f70fe-3289-4e2b-9ea6-2ab9e009c0ca)

**Comment by johnshea** [comment]
Hi @Kalyan19111999 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
