### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by bogoliy** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#448]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#9

**In which task and step of the codelab can this issue be found?**
9.2

**Describe the problem**

Vertical Alignment not works

**Steps to reproduce?**
1. Run the example on emulator
2. Check that text is at Top

**Versions**
Android Studio Giraffe | 2022.3.1 Patch 2

**Additional information**

<img width="1303" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/1389601/bb19cbb4-834c-4613-a8ae-eac98d0dc826">

Adding fillMaxSize eto Column fixes the issue
```
Column(
        verticalArrangement = Arrangement.Center,
        modifier = modifier.fillMaxSize()
    ) 
```
<img width="1303" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/1389601/af86a7af-16de-45e3-89c7-a3915ccfdd73">

**Comment by johnshea** [comment]
Hi @bogoliy 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to address it and the revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
