### ISSUE TITLE
Before you begin: Android Basics with Compose

### ISSUE THREAD

**Issue by SidharthPati** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#449]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-before-you-begin#0

**In which task and step of the codelab can this issue be found?**
Issue is seen after clicking the "Done" button

**Describe the problem**
Chapter is not marked as done even after clicking done.

**Steps to reproduce?**
1. Go to "Before you begin" chapter.
2. Click on "Done" at the end of page.
3. See error: It doesn't mark this chapter as "Done" in unit 1 (Introduction to programming in Kotlin unit). Even if you proceed with other chapters, it resets the progress to 0%.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2023-10-09 at 3 58 13 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/22004791/42304478-9189-42c8-bd13-7485a8b8776b)

**Comment by johnshea** [comment]
Hi @SidharthPati 

Thank you for writing in to bring this to our attention.

I will let the team know so they can look into it further.

Hope you are enjoying the course!

Regards.
