### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by yuuwe-n** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#45]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**

When creating:
```
Image(
     painter = image,
     contentDescription = null
)
```
the import context directs towards the (old android view?) package. The composable import is crossed out during import.

**Steps to reproduce?**
1. Follow up to step 4
2. Inside BirthdayGreetingWithImage, create val image, and create Image(painter=image)
3. Follow context menu, import Image (android.media)
4. variables within Image() are errors

**Solution**
Clear misunderstandings within the tutorial (no instance saying to import which one) or modify android studio context menu behavior. I think just adding to the tutorial would be much better. It would also clear up misunderstandings to anyone new to coding (they will get abstract object errors, and I think it would be hard for new coders to troubleshoot out of it)

**Versions**
_Android Studio version:_ 2021.2.1 Patch 2

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/55438165/183820462-5d566043-e7f3-4851-add3-d23c23a092d8.png)

**Comment by fritsjan** [comment]
I needed to add: import androidx.compose.foundation.Image before it worked...

**Comment by Habib599** [comment]
wow it's work

**Comment by osuleymanova** [comment]
@yuuwe-n 
Thank you for reaching out to us. Please check the list of imported libraries:

![Screen Shot 2022-09-19 at 3 23 13 PM](https://user-images.githubusercontent.com/86437155/191331192-d967d72c-e81c-4571-970b-47de7ecf615d.png)
