### ISSUE TITLE
Install Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by michelm** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#450]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-install-android-studio&hl=en#7

**In which task and step of the codelab can this issue be found?**
NA

**Describe the problem**
Missing description of Android studio installation on Chromebooks

**Steps to reproduce?**
NA

**Versions**
NA

**Additional information**
NA

**Comment by johnshea** [comment]
Hi @michelm 

Thank you for writing in with your concern.

I will share this with the team so they can review and update the lesson as needed.

Hope you are enjoying the course.

Regards.
