### ISSUE TITLE
The sample tutorial contains some errors that require rectification.

### ISSUE THREAD

**Issue by Eve-Middleton** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#452]
Hello, I would like to offer feedback regarding an issue pertaining to the output generated by this code, as illustrated below.
Problem url：https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-first-program?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program#8

`
fun main() {
    println("1")
    println("2")
    println("3")
}`

I believe that the expected output of the aforementioned code should be

`1 2 3 `

rather than 
`I'm
learning
Kotlin!`

**Comment by johnshea** [comment]
Hi @Eve-Middleton 

Thank you for writing in with your question.

Those are from different questions so what you said for the output could be correct.

Question 1 asks you to review the code and try to figure out what will be printed when you run those lines of code.

Quest 2 ask you how to write the code to print that message.

Hope you are enjoying the course!

Regards.
