### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by tamura23** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#458]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
No option whose name is "Empty Compose Activity" exists on android studio. Instead of its option, "Empty Activity" exists.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @tamura23 

Thank you for writing in with your issue.

Android Studio has changed the title from "Empty Compose Activity" to "Empty Activity" as you have noticed.

Please use "Empty Activity".

We are actively updating the course and will be fixing these as we go.

Hope you are enjoying the course.

Regards.
