### ISSUE TITLE
Add images: Android Basics with Compose - Closing }

### ISSUE THREAD

**Issue by cameronpovey** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#459]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images#5

**In which task and step of the codelab can this issue be found?**
6

**Describe the problem**
Closing '}' missing on first code snippet for the GreetingText function

**Additional information**

_fixed code snippet_
`
@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    // Create a column so that texts don't overlap
    Column(
        verticalArrangement = Arrangement.Center,
        modifier = modifier
    ) {
        Text(
            text = message,
            fontSize = 100.sp,
            lineHeight = 116.sp,
            textAlign = TextAlign.Center
        )
        Text(
            text = from,
            fontSize = 36.sp,
            modifier = Modifier
                .padding(16.dp)
                .align(alignment = Alignment.End)
        )
    }
}
`

**Comment by johnshea** [comment]
Hi @johnshea 

Thank you for bringing this to our attention.

The lesson content has been updated and will be republished again in the near future with this fix.

Hope you are enjoying the course.

Regards.
