### ISSUE TITLE
Functions in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by zhouzhouzhoumiao** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#46]
**URL of codelab**
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#3

**In which task and step of the codelab can this issue be found?**
in step 4

**Describe the problem**
missing the colon
![image](https://user-images.githubusercontent.com/45782460/183824755-cb2c6424-03c5-45ad-8cea-7b8f3cfd8fd7.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@zhouzhouzhoumiao 
Thank you for reaching out to us. The missing colon issue is fixed and will be published soon:

![Screen Shot 2022-09-16 at 2 58 17 PM](https://user-images.githubusercontent.com/86437155/190808396-ad1c649b-0d86-44fa-9080-f0c5ab1d29d0.png)
