### ISSUE TITLE
Jetpack Compose - Learning

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#461]
I've been learning Jetpack Compose Basics and I cannot complete Unit 1, I have tried for several months and i've even tried Kotlin Basics and I cannot complete Unit 1.

I have re-done Unit 1 for both courses and tried for over 1 year.

Are you able to offer some tips and advice please.

And also, how do Developers remember all the var, fun and class names and all of the other information needed to write code, im interested to know.

**Comment by johnshea** [comment]
Hi @AR102023 

I would recommend going in small steps and try to understand as much as you can at each point. Before moving on, try to make small changes to see the new end result. For example, try changing the background color and see what happens.

Practice and repetition might help for learning the keywords and coding.

Regards.

**Comment by AR102023** [comment]
Hi John,

A lot of the codelabs don't match the solution code on GitHub.

Are there any plans to introduce a Kotlin course for beginners?

Thank you.


________________________________
