### ISSUE TITLE
Android Basics in Kotlin

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#462]
Will you be removing the below course from your Training Material or will the course still continue to be available?

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/6c561c99-59a9-4a99-965c-45bf9eca9fa8)

**Comment by johnshea** [comment]
Hi @AR102023 

This course is deprecated and will be removed in the near future.

Regards.
