### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by hhasert** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#463]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**
3 Add an image composable

**Describe the problem**
When I enter only 

Image(
   painter = image
)

The Image tag is not recognized.  I added the import but nothing changed, Image was displayed in white and red underlined.  

The tooling only works with :

 Image(
      painter = image,
      contentDescription = null
  )

**Steps to reproduce?**
1.  as described above
![Screenshot 2023-10-23 160934](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/11528574/25e9585b-4b86-4790-b6ef-3ae4059ee1e3)
![Screenshot 2023-10-23 161045](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/11528574/3e7afa53-a19a-47c3-9555-d61059d5611e)

**Versions**
_Android Studio version:_  Android Studio Giraffe | 2022.3.1 Patch 1
_API version of the emulator:_  NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @hhasert 

Thank you for writing in with your issue.

The lesson wording has been revised to address this and make it clearer.

Hope you are enjoying the course!

Regards.
