### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by shlee4458** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#464]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**Describe the problem**
To call the overridden method in the superclass from teh subclass

a minor typo spotted in bottom 90% of the text.

**Comment by johnshea** [comment]
Hi @shlee4458 

Thank you for writing in and bringing this to our attention.

It has been corrected and the updated content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
