### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by michelm** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#465]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?authuser=0&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fauthuser%3D0%26hl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects&hl=en#6

**In which task and step of the codelab can this issue be found?**
7 (implement a relationship between classes)

**Describe the problem**
Typo: "_To call the overridden method in the superclass from **teh** subclass, you need to use the super keyword._"

**Steps to reproduce?**
n.a.

**Versions**
n.a.

**Additional information**
n.a.

**Comment by johnshea** [comment]
Hi @michelm 

Thank you for writing in and bringing this to our attention.

It has been corrected and the updated content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
