### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by gitwazza** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#467]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
4. Add Box layout

**Describe the problem**
In the code

_setContent {
    HappyBirthdayTheme {
       // A surface container using the 'background' color from the theme
        Surface(color = MaterialTheme.colors.background) {
            GreetingImage("Happy Birthday Sam!", "From Emma")
        }
    }
}_

the "MaterialTheme.colors.background" should possibly be "MaterialTheme.colorScheme.background" otherwise it appears as an "unresolved reference"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1 Patch 2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @gitwazza 

Thank you for writing in with this issue.

The content has been updated and will be republished again in the near future.

Hope you are enjoying the course.

Regards.
