### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by johari564w** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#468]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#1)

Note: For the valid ranges for the numerical data types (Int, Double, and Float), see [Numbers](https://kotlinlang.org/docs/numbers.html). For specifics on the difference between Double and Float, look at [this table](https://kotlinlang.org/docs/numbers.html#floating-point-types) comparing the two data types.

The Numbers link is not working in Variables and datatypes section of this codelab.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @johari564w 

Thank you for writing in.

Please share a screenshot of what error message you are seeing as I just tried and the link is working correctly for me.

Regards.

**Comment by johari564w** [comment]
Hi johnshea
I am thankful for your response. After reading your  response i checked again and found out the issue is not in the link but in my browser.
I am sorry for the trouble and at same time Thank You
