### ISSUE TITLE
Practice problems: Android Basics in Compose

### ISSUE THREAD

**Issue by zhouzhouzhoumiao** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#47]
**URL of codelab**
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**
in step 12

**Describe the problem**
The value in the description is incorrect. The correct value is 5000+1000
![image](https://user-images.githubusercontent.com/45782460/183875665-fe7e28ee-8f77-461f-a81a-5dfe85c9d1b9.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@zhouzhouzhoumiao 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-09-16 at 10 51 01 AM](https://user-images.githubusercontent.com/86437155/190701940-09f55036-8265-43d9-a5ed-7033d5752b96.png)
