### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by gitwazza** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#472]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
course states: "folder called drawable-nodpi"

however, the folder appears to be named: "drawable" with no "-nodpi"

**Steps to reproduce?**
1. Go to...2. Set up your app
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @gitwazza 

Thank you for writing in with your concern.
 
Android Studio might display it as "drawable" depending on your view but the "computer file system" has a " ... folder called drawable-nodpi".

Hope that helps to clarify it.

Regards.
