### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by obandu** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#473]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**In which task and step of the codelab can this issue be found?**
What is Jetpack Compose

**Describe the problem**
There seems to be a (factual) error in the text. Potential error text is highlighted in the screenshot. Also, it may not be an error

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![composetrainingerror](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7066224/c7dd3193-2d53-469e-a96f-78edac5f1be8)

**Comment by johnshea** [comment]
Hi @obandu 

Thank you for writing in and bringing this to our attention.

The lesson wording has been updated and the lesson will be republished again with the fix in the near future.

Hope you are enjoying the course.

Regards.
