### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Tuyenfr** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#474]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
[basic-android-kotlin-compose-birthday-card-app](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app)

**Describe the problem**
You put .align(alignment : Alignement.End) in the Text {} while for me it worked putting it in () atfer Text, see below :

Row (modifier = Modifier.align(alignment = Alignment.End)){
                Text(
                    text = from,
                    fontSize = 25.sp,
                    lineHeight = 50.sp,
                    modifier = Modifier
                        .padding(16.dp)
                )

**Versions**
_Android Studio version:_ Giraffe 2022.3.1 Patch 1
_API version of the emulator:_ 24

**Comment by johnshea** [comment]
Hi @Tuyenfr 

Thank you for writing in with your feedback.

There are often multiple ways to achieve the same end result.

This appears to be one of those cases.

Hope you are enjoying the course!

Regards.
