### ISSUE TITLE
Use classes and objects in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Durden20** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#475]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
Reuse superclass code in subclasses with the super keyword

**Describe the problem**
teh instead of the

**Steps to reproduce?**
1. Go to... given link
2. Click on... ctrl + F, find "teh"
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Durden20 

Thank you for writing in and bringing this to our attention.

It has been corrected and the updated content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
