### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by AhirraoShubham** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#477]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
Task -  Use classes and objects in Kotlin point number 7
Paragraph Name - Reuse superclass code in subclasses with the super keyword

**Describe the problem**
Found one spelling mistake in the above paragraph. the spelling of the is mistakenly typed **teh**

Problem: To call the overridden method in the superclass from teh subclass, you need to use the super keyword. 

It should be: To call the overridden method in the superclass from the subclass, you need to use the super keyword. 

**Steps to reproduce?**
1. Go to URL of codelab
2. Click on point number 7
3. See the error in above mentioned paragraph

Note: Please find the attached for more understanding of the issue.
![Screenshot (202)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/40315171/e25ce240-383a-47a7-9b8f-636a47c29845)

**Comment by johnshea** [comment]
Hi @AhirraoShubham 

Thank you for writing in and bringing this to our attention.

It has been corrected and the updated content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
