### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by wizzardx** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#478]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#9

**In which task and step of the codelab can this issue be found?**

At the very least in the full code, but this probably affects the earlier steps

**Describe the problem**

Labels to not center vertically in the emulated android VM. Does not match the final screen capture at the bottom of "Add greeting to the app" stage 9.

Text labels are all instead arranged around the top of the VM instead.

Following a guide over here, I managed to fix it:

https://semicolonspace.com/jetpack-compose-alignment-arrangement/

Here is my 'git diff' for the commit which fixes it:

```kotlin
@@ -42,7 +42,7 @@ fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
     // Create a column so that texts don't overlap
     Column(
         verticalArrangement = Arrangement.Center,
-        modifier = modifier
+        modifier = modifier.fillMaxSize()
     ) {
         Text(
             text = message,
```

**Steps to reproduce?**

1. Copypaste full example code from Step 10 into MainActivity.kt file
2. Run the code in the Android VM.

**Versions**
Android Studio Version: 2022.3.1 Patch 2
API version of the emulator: 34

**Additional information**

Screen capture before I made the change:

![before_change](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/1143852/c45294f2-bdcf-4e66-aa46-7b03d97b0405)

Screen capture after I made the change:

![after_change](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/1143852/f1567fb8-0ae4-4ffd-b424-b7536fd192d2)

**Comment by johnshea** [comment]
Hi @wizzardx 

Thank you for writing in concerning this issue.

The lesson has been updated and corrected to address it.

Hope you are enjoying the course!

Regards.
