### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by SabaBakidze** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#48]
**URL of codelab**
Every Codelab

**In which task and step of the codelab can this issue be found?**
Every Codelab has the issue

**Describe the problem**
Whenever you go to the next step of Codelab by pressing "Next" button the page is kept scrolled to the bottom, instead it should start from the top of the page. Every time you go to the end of one page and click "Next" button, the next page appears already to the bottom of the screen and one has to scroll back up to do the activity.

**Steps to reproduce?**
1. Go to... Any Codelab tab
2. Click on... Scroll down to the bottom and click on Next
3. See error... The next page is scrolled to the bottom

**Versions**
_Android Studio version:_ Nothing to do with Android Studio Version
_API version of the emulator:_ Nothing to do with API version of the emulator

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
I don't think it's necessary

**Comment by osuleymanova** [comment]
@SabaBakidze 
Thank you for reaching out to us and sharing your concern. So far it's an intentional behavior for a few codelabs.
