### ISSUE TITLE
Use classes and objects in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Durden20** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#480]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#9

**In which task and step of the codelab can this issue be found?**
In test solution and everywhere else this code is used.

**Describe the problem**
In main function instead of initializing smartDevice variable, shouldn't it be smartTvDevice. and Instead of using SmartDevice 
type(: class) should use SmartTvDevice type...

**Steps to reproduce?**
1. Go to... url of codelab given, copy and paste solution in kotlin playground,
    in main function paste this{
val smartTv: SmartDevice = SmartTvDevice("Android TV", "Entertainment")
    smartTv.turnOn()

    val smartLight = SmartLightDevice("Google Light", "Utility")
    smartLight.turnOn()
    
    val smartHome = SmartHome(smartTv, smartLight)
}
2. Click on... run button
3. See error... Type mismatch: inferred type is SmartDevice but SmartTvDevice was expected

**Comment by johnshea** [comment]
Hi @Durden20 

Thank you for writing in.

The lesson is showing that a variable of type SmartDevice can store an object of type SmartTvDevice or SmartLight device since they inherit from class SmartDevice.

Hope this helps.

Regards.
