### ISSUE TITLE
Jetpack Compose - @Preview annotation

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#482]
@android-dev-lxl @osuleymanova @OwenScott-GDS 

I am experiencing the below, unable to view the @Preview in the Split tab. This is the first time this has happened. As you will see in the below screenshot, @Preview annotation is showing.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/6314c921-6b92-419b-a3d1-c32048ea37e4)

Also, my other issues are not receiving a response.

**Comment by johnshea** [comment]
Hi @AR102023 

As you reposted this issue, I will be closing this one.

Please check your other post as we need additional information to help you troubleshoot this further.

Regards.

**Comment by AR102023** [comment]
Hi John,

I live in the UK and Studio Bot isn't available to me, are you able to recommend something similar I can use please?

Thank you.


________________________________
