### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by chrylis** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#483]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**In which task and step of the codelab can this issue be found?**
3. What is Jetpack Compose?
Composable function names

**Describe the problem**
"Pascal case" is named after the programming language Pascal and should be capitalized.

**Comment by johnshea** [comment]
Hi @chrylis 

Thank you for bringing this to our attention.

The lesson has been updated and will be re-published again in the near future.

Hope you are enjoying the course!

Regards.
