### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by earlsab** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#485]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-1%23codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Spelling error under the section "Reuse superclass code in subclasses with the super keyword"

> To call the overridden method in the superclass from teh subclass, ...

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/62688314/ee31ff47-62a1-4865-93a4-c8dbef110bf8)

**Comment by johnshea** [comment]
Hi @earlsab 

Thank you for writing in with this issue.

It has been corrected and the lesson will be republished again in the near future.

Hope you are enjoying the course.

Regards.
