### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by hsseek** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#49]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#3

**Describe the problem**
In the image(96792990a18affb6.png) a colon is missing after parameters.

![defining a function](https://developer.android.com/static/codelabs/basic-android-kotlin-compose-functions/img/96792990a18affb6.png)

**Comment by hsseek** [comment]
A duplicate of https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/46

**Comment by osuleymanova** [comment]
@hsseek 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-09-16 at 2 58 17 PM](https://user-images.githubusercontent.com/86437155/190810265-cc4ea354-8ed3-4f70-bf74-6b943103ffa2.png)
