### ISSUE TITLE
Android Studio ERRORS

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#490]

**Comment by johnshea** [comment]
Hi @AR102023 

Thank you for writing in.

Please provide a screenshot showing all your code including the specific import statements at the top.

I am unable to troubleshoot this issue just based on this limited screenshot.

I look forward to your reply.

Regards.

**Comment by AR102023** [comment]
Hi John,

Thank you for responding to my messages.

Regarding this particular inquiry, it happens on starting a new project on API 24. Now I have to create a new project using API 34.

I believe this to be an issue with Android Studio as it used to work in API 24 without the red writing showing.

The below is running on API 24.
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/1fd6d4f9-413b-45f9-9dc6-21015361fd23)
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/84d67c4c-1cb4-4607-8424-3938a91911c0)
The code in the above screenshots are exactly how it was when I received the message that no @Preview was available.

Currently using API 34 at the moment until I can start using API 24.

**Comment by AR102023** [comment]
@johnshea 

Issue now fixed, possibly due to an update to Android Studio
