### ISSUE TITLE
Issue with in Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Spunalien** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#491]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#4

**In which task and step of the codelab can this issue be found?**

5.4

**Describe the problem**
Step 5.4 states  -  "Before the BirthdayCardPreview() function, add a new function called GreetingText(). ..."

This how-ever creates issues with rendering.  If you place the GreetingText() function after the BirthdayCardPreview() function, there is not an issue with render.  As I am still learning, I don't understand why this would be but it is.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 

Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

_API version of the emulator:_   31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![Screenshot 2023-11-05 013935](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/51837796/98e813f6-0bc8-4688-8bd6-0bc0a8ddf560)
![Screenshot 2023-11-05 015806](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/51837796/e105bc9b-770f-4236-8fff-1c224f4aa6fc)

**Comment by johnshea** [comment]
Hi @Spunalien 

Thank you for writing in with your issue.

The issue is not where you are placing the code but where the `@Preview` statement is positioned.

The `@Preview` line should be annotating the `BirthdayCardPreview` as shown in your second screenshot.

In your first screenshot which has the error, the `@Preview` line is by itself but directly above `GreetingText` so it is trying to  render it which is not possible and shows an error. You want to move function `GreetingText` above the `@Preview` line in that case so it will annotate the `BirthdayCardPreview` instead

Hope this helps and you are enjoying the course!

Regards.

**Comment by Spunalien** [comment]
Thanks, that makes sense.
Rob

Sent from Rogers Yahoo Mail on Android 
 
  On Tue., 7 Nov. 2023 at 12:19 p.m., John ***@***.***> wrote:   


Hi @Spunalien

Thank you for writing in with your issue.

The issue is not where you are placing the code but where the @Preview statement is positioned.

The @Preview line should be annotating the BirthdayCardPreview as shown in your second screenshot.

In your first screenshot which has the error, the @Preview line is by itself but directly above GreetingText so it is trying to render it which is not possible and shows an error. You want to move function GreetingText above the @Preview line in that case so it will annotate the BirthdayCardPreview instead

Hope this helps and you are enjoying the course!

Regards.
