### ISSUE TITLE
Jetpack Compose Basics

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#492]

**Comment by johnshea** [comment]
Hi @AR102023 

Please provide the requested information so we can help you.

There is no information currently provided on this ticket.

Regards.

**Comment by AR102023** [comment]
Hi John,

If there's no text displayed it means that I've deleted the text as I'm unable to delete the text message itself.


________________________________

**Comment by johnshea** [comment]
Hi.

Thank you for the update. I will close the issue.

Regards.
