### ISSUE TITLE
Next Android Studio Update

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#493]
Hello,

I currently have Android Studio Giraffe, when should I expect to see the next Android Studio update?

And I live in the UK, when should I expect to see Android Bot?

Thank you.

**Comment by johnshea** [comment]
Hi @AR102023 

For the latest information on Android Studio, please refer to the official [Android Studio web page](https://developer.android.com/studio).

Regards.
