### ISSUE TITLE
Androids Basics with Compose Course and Solution Codes

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#495]
**Ive completed** https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#0
**AND**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#8

**So now I am completing the Practice: Compose Basics** (https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems) https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2 **Although, the solution code in the second screenshot below for both courses above does not match the solution code below in the first screenshot below.
So, what I have been trained in the courses does not match the below as you will notice the difference.** **To add, the first link below containing the solution code does not teach in the course, so what's taught in the training is different in the solution code.**

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/2c53ec6d-6fbe-4586-a76d-1edfe6dd98e0)

**Both the solution code above needs to match the below.**

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/8b3210b1-5854-491d-9794-4f8c90f912f7)

--

**Also, another issue regarding font:**

**In the solution code, it explains how to create a bold font.**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/3dd755d6-e10a-4a88-b306-34e20c61f283)
**Compared to** https://developer.android.com/jetpack/compose/text/style-text
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/bd327782-7dc5-494a-a6ce-a0ea1a063b38)

**I feel that the reason why I struggle to complete the Jetpack Compose course is because all content is different, some of the content is difficult to make sense of resulting in having to re-read. Also, some content instructs one way and another instructs differently.
Also, solution code does not match what has been trained and solution code in the course does not always fully align with what was taught.**

--

**I would very much appreciate if the Androids Basics with Compose Course would be reviewed along with solution codes. I enjoy learning and I want my learning to be a great experience.**

**Comment by johnshea** [comment]
Hi @AR102023 

Thank you for writing in and sharing your concerns with the team.

We are reviewing the lessons and will update as needed so they match.

Regarding how to create a bold font -> Both examples you share are setting the `fontWeight` argument to `FontWeight.Bold` so they are essentially the same thing just that the formatting is multi-line.

Regards.

**Comment by AR102023** [comment]
Thank you for taking onboard my feedback. Thank you John.


________________________________
