### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by JonathanCamiloDuarteGomez** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#497]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Findex%3D..%252F..android-kotlin-fundamentals%26hl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#8

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
El codigo no corre, pide HappyBirthdayTheme y pues esa funcion no esta, tampoco encontre el tema. entonces cuando se descarga no funciona.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @JonathanCamiloDuarteGomez 

Thank you for writing in with your concern.

The lesson has been revised and improved and believe this issue has been resolved.

If you are still experiencing this issue, please create a new issue and provide screenshots of the error(s) and what part of the lesson wording you are following so we can troubleshoot further.

Regards.
