### ISSUE TITLE
Typo in Codelab

### ISSUE THREAD

**Issue by Desjajja** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#499]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
Section *Reuse superclass code in subclasses with the super keyword* of the codelab

**Describe the problem**
a typo of "teh" for "the"
> To call the overridden method in the superclass from **teh** subclass...

**Steps to reproduce?**
1. Go to the Section as said
2. It is in the second paragraph

**Versions**
_Android Studio version:_  Not specified
_API version of the emulator:_  Not specified

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/58029489/3984e251-b812-4f43-8499-2c5d4798cd11)

**Comment by johnshea** [comment]
Hi @Desjajja 

Thank you for bringing this to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
