### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by shourikan** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#50]
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#4

5

Title typo "pane" should be "panel"

**Comment by osuleymanova** [comment]
@shourikan #
Thank you for reaching out to us. There is no typo: it should be "Design pane" not panel. Please follow the codelab steps for further understanding.
The ticket is closed as won't fixed.
