### ISSUE TITLE
Jetpack Compose Basics Course

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#500]
The Jetpack Compose Basics Course needs to be re-written to be beginner friendly. Mass work is needed and the solution codes do not always match the taught content and this applies to some of the solution codes for the practices.

I have been trying to complete Unit 1 for over a year and likewise for the Kotlin Basics course.

Both courses are not beginner friendly and its takes away the learning experience.

Also, it is assumed I would know how to complete the practices.

**Comment by johnshea** [comment]
Hi @AR102023 

Thank you for writing in and sharing your thoughts on the course.

We are always trying to improve the course and will take this into consideration.

Regards.
