### ISSUE TITLE
Practices and Solution Codes

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#501]
**Trying to complete this practice task** https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#3

**The first screen is the practice and the second screen is the solution code to the practice.**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/ba48216b-0694-4a83-88b7-465b5b053824)

**Its impossible to complete the practice unless im a skilled Jetpack Compose Developer, I say this because what's shown in the solution code is not mentioned anywhere in the practice. Also, the solution code does not relate to the practice and also, i've not been trained up to this practice to complete such a practice.**

**I have spent over 8 hours trying to complete and make sense of how the solution code relates. Also, the solution code to the practices prior do not align to the training received.

I have learnt that who ever writes this training material assumes that learners would already know  what to write in Android Studio.

I'm a beginner and my learning experience is not a good experience so far.**

**Comment by johnshea** [comment]
Hi @AR102023 

Thank you for writing in about this lesson and your thoughts on the presentation.

The lesson will be reviewed and updated as necessary.

You thoughts will be considered while updates and revisions are underway.

Regards.

**Comment by AR102023** [comment]
Thank you John


________________________________
