### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by alghe-global** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#503]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**
Pedometer

**Describe the problem**
Not exactly a problem per se, however it would be ideal to change

```
    val caloriesBurned = pedometerStepsToCalories(steps);
```

to

```
    val caloriesBurned = pedometerStepsToCalories(steps)
```

(notice the removal of `;` at the end of the line)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @alghe-global 

Thank you for bringing this to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
