### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by akashjain0900** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#504]
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects

HAS-A relationships: Step - 10

After describing how to create classes which can have HAS-A relationship among each other, it was not described on how to instantiate an object for that class.
This will confuse many beginners as on what parameters to pass and which class to call to create an object.

**Steps to reproduce?**
1. Go to - https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects
2. Go to - HAS-A Relationships Step 10

Screenshot
![Err](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56585965/2305550c-6fc5-4431-b0b1-4f1a6c8e5056)

**Comment by johnshea** [comment]
Hi @akashjain0900 

Thank you for writing in and sharing your concern with us.

I will share it with the team so they can review and decide how they would like to address it.

Hope you are enjoying the course!

Regards.
