### ISSUE TITLE
some Chinese words translation error

### ISSUE THREAD

**Issue by aghao** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#505]
**URL of codelab**
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-first-program?hl=zh-cn#4

**In which task and step of the codelab can this issue be found?**
in title "您的第一个Kotlin程序" 
Step 5

**Describe the problem**
there is a translation error 
"完成相同"
it should be "完全相同"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/4003426/31976d6e-e13b-4c3b-beef-216e452e2ac4)

**Comment by johnshea** [comment]
Hi @aghao 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
