### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by Lee-Price** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#508]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12

**In which task and step of the codelab can this issue be found?**
[13. Additional Practice](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12)

**Describe the problem**
clicking on Knowledge Map link returns a 404.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="927" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/75488199/b1f14302-0dcc-4feb-b4ed-3fd347ee6e39">

**Comment by johnshea** [comment]
Hi @Lee-Price 

Thank you for writing in with your concern.

I just tried the link and it loads correctly.

Perhaps there was an issue at the time that has now been resolved.

Hope you are enjoying the course.

Regards.
