### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by agwcolor** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#510]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12

**In which task and step of the codelab can this issue be found?**
[13. Additional Practice](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12)
For more practice on the Kotlin language, check out the [Kotlin Basics track](https://hyperskill.org/tracks/18) in JetBrains Academy. To jump to a specific topic, go to the [knowledge map](https://hyperskill.org/knowledge-map) to view the list of topics covered in the track.

**Describe the problem**
Link to knowledge map on JetBrains = 404 not found

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12
2. Click on... "knowledge map" link
3. See error... "404"

**Versions**
_Android Studio version:_  n/a
_API version of the emulator:_  n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @agwcolor 

Thank you for writing in with this issue.

I tried the link and can confirm that it is working correctly at this time. Perhaps it was a glitch or something was fixed on their end.

Hope you are enjoying the course!

Regards.
