### ISSUE TITLE
Text composables: Android Basics with Compose generates invalid build file

### ISSUE THREAD

**Issue by steve-scott** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#511]
Project won't build. Solution is to edit build.gradle.kts (Module :app) file and change targetSDK, compileSDK from 33 to 34.

**https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#1**

**Task 2, Step 5**

**Describe the problem**
Android studio is generating an invalid build.gradle.kts (Module :app) file.

**Steps to reproduce?**
1. Go to Task 2
2. Do steps 1-5
3. Project cannot build

**Versions**
_Android Studio version:_ 

Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 24
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

_API version of the emulator:_ 
Doesn't matter

**Additional information**

![bad-build-file](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/11650674/80d89ddf-9c0f-4bb0-832f-5285c95ad453)

When I took the Create Your First Android App course (https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1), I followed the same steps to generate the app, and it worked just fine. So I diffed the GreetingCard project from that course with the HappyBirthday project from this course. One file stood out - app/build.gradle.kts. It has different dependencies. I've attached the files from both projects (zipped in build.gradle.zip) and a screen shot of a Winmerge comparison. I added the project name to the front of the file names.

When I tried to redo the GreetingCard course, I now get the same error. I just took the GreetingCard course yesterday and it worked ok, but today trying to recreate it from scratch (using the project name GreetingCard2), I get the dependency error. So something in Android Studio is causing this dependency error.

![bad-dependencies](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/11650674/2dc66643-9c37-4a1c-96ce-d15a1d67888f)

[build.gradle .zip](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/files/13401839/build.gradle.zip)

**Comment by johnshea** [comment]
Hi @steve-scott 

Thank you for writing in with your concern.

I tried recreating this issue on the latest stable version of Android Studio (Android Studio Hedgehog | 2023.1.1 Patch 2) but was unable.

If you have time, please update to the latest stable version and see if the issue still exists. If it does, create a new issue and provide details such as your OS, Android Studio version, steps to replicate, etc.

Hope you are enjoying the course!

Regards.
