### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose 4. Update variables

### ISSUE THREAD

**Issue by Ernie1961** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#512]
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#3**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
fun main() {
    var cartTotal = 0
    cartTotal = 20
    println("Total: $cartTotal")  
}
Total: 20
it should read:

fun main() {
    var cartTotal = 0
    cartTotal = 20
    println("cartTotal: $cartTotal")  
}
CartTotal: 20   as in in the lesson 4  ' Update Varibles' according to Kotlin Playground, https://developer.android.com/training/kotlinplayground

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Ernie1961 

Thank you for writing in with your issue.

The informational text being printed at the beginning does not have to match the variable name as you wrote.

They can match if you wish but not a requirement.

Hope you are enjoying the course.

Regards.
