### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by RICHARDnig** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#513]
**URL of codelab**https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-1#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-functions

**In which task and step of the codelab can this issue be found?** step 1 code lab

**Describe the problem** no main() {

**Additional information**
![Capture3](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/151448173/d650bcb4-8a2c-49df-a0d9-e7618bcbe7de)

**Comment by johnshea** [comment]
Hi @RICHARDnig 

Thank you for writing in.

The code that is causing you an issue is a continuation from the previous step. You should not be deleting all the code and then recreating the `birthdayGreeting` function. The `main` function should still be part of your code.

Please refer back to "Step 3 - Return a value from a function".

Hope you are enjoying the course.

Regards.
