### ISSUE TITLE
Your first program: Android Basics with Compose

### ISSUE THREAD

**Issue by devjsullivan** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#514]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program#9

**In which task and step of the codelab can this issue be found?**
5. When you run the program, you see an Unresolved reference: printLine error

**Describe the problem**
printLine (with Line, not ln) is nowhere in the code for this part of the Unit. It seems like an outdated direction for error correction that has been fixed in the code portions of the lab, without updating the lab's text.

**Steps to reproduce?**
1. Read the web page linked above.
2. Notice that the page references `printLine` in step 5.
3. Realize that `printLine` is nowhere else on the page to show that it could cause the user a problem/error such as `Unresolved reference`.

**Versions**
_Android Studio version: N/A
_API version of the emulator: N/A

**Additional information**
![printLineNotInCode](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/25830676/e35f7a13-173c-4b37-b614-b6da579159ec)

**Comment by johnshea** [comment]
Hi @devjsullivan 

Thank you for writing int.

`printLine` was used to create an error that the student would need to identify as causing the problem.

It was used to help thempay attention to detail and to debug code.

Hope you are enjoying the course.

Regards.
