### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by kokodayo000** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#515]
[**URL of codelab**
](https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-first-app?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1)

**In which task and step of the codelab can this issue be found?**
third，create first android app，second step

**Describe the problem**
video missing

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
!
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/150889623/138dfebd-3f1a-4bfe-97ec-b2f19443b3a2)

**Comment by johnshea** [comment]
Hi @kokodayo000  

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
