### ISSUE TITLE
Text composables: Android Basics with Compose - incorrect name for curly braces

### ISSUE THREAD

**Issue by spokorski** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#517]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
The guide refers to curly braces `{ }` as "parentheses".  This occurs multiple times, making it seem like a genuine misunderstanding. and not a simple typo.  Since both characters are syntactically important and not interchangeable, the misnomer could lead to confusion for new users

**Steps to reproduce?**
N/A
it's part of the static guide text

**Versions**
N/A

**Additional information**
https://en.wikipedia.org/wiki/Bracket

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/14926863/fff4e04f-551d-4089-a4af-c1e44d6ff05f)

**Comment by johnshea** [comment]
Hi @spokorski 

Thank you for writing in and bringing this to our attention.

The lessons has been revised and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
