### ISSUE TITLE
Business Card app: Android Basics with Compose

### ISSUE THREAD

**Issue by SamehHabib90** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#518]
No link to download icons in the task

**Comment by johnshea** [comment]
Hi @johnshea 

Thank you for writing in regarding your issue.

The instructions state the Android logo is provided in the repo and a link is provided.

<img width="578" alt="Screenshot 2024-03-18 at 9 24 55 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/7ed122f8-7230-44d4-a529-8fe3581e89ab">

Hope this helps.

Regards.
