### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by AR102023** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#519]
**URL of codelab** https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?** https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-1#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects Pathway 4

**Describe the problem**
The course material requires re-writing to make clear what the learner has to do, for example, in the below screenshot, the training team have not explained where to insert the subclass and also, the screenshot shows that we need to write the subclass above the superclass.
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/148583693/e9c19d21-bbce-428e-99b9-9192943a0544)

This is the solution code, although what is taught in the above course does not align with the solution code.
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#9

**Comment by johnshea** [comment]
Hi @AR102023 

Thank you for writing in and providing images of the issue.

I will share with the team so they can address it as needed.

Regards.

**Comment by AR102023** [comment]
Thank you


________________________________
