### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by simonpeier** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#52]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#7

**In which task and step of the codelab can this issue be found?**
Step 8: Adopt good code practice

**Describe the problem**
In this step , one should adopt good code practices. Therefore, the Strings in the MainActivity are moved to the strings.xml file and replaced with a call to said file.

![image](https://user-images.githubusercontent.com/41295530/187657054-f7855a61-42c0-47d0-b0b7-866d4e78dab5.png)

At the end of Step 8, the user should test if the App still looks the same by running it. The app indeed shows the same text in the preview, but one never changed the Strings in the preview. IMHO, one should also have to change the Strings in the BirthdayCardPreview with a call to the strings.xml file. Otherwise it does not make sense to extract them to the strings.xml file.

**Comment by android-dev-lxl** [comment]
@simonpeier 

Thanks for the suggestion.
Fixed and to be published.

![image](https://user-images.githubusercontent.com/24260141/217698936-3a384022-85d2-4411-bdc4-6bcd1f2f4c68.png)
