### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by shivathapaa** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#520]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**
Step 7: Implement a relationship between classes
_Exactly in subheading: Reuse superclass code in subclasses with the super keyword_

**Describe the problem**
In the first sentence of the second paragraph, a minor typographical error is present.

_Mistake:_ To call the overridden method in the superclass from `teh` subclass, ...

**Steps to reproduce?**
1. Go to the codelab using the above link.
2.  Scroll down/search for the subheading, **"Reuse superclass code in subclasses with the super keyword"**
3. See the mistake in the first line of the second paragraph.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
Screenshot:
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/89457854/47c30a77-b8b0-4ccd-b639-9929c43a19ef)

**Comment by johnshea** [comment]
Hi @shivathapaa

Thank you for bringing this to our attention.

The lesson has been updated and republished.

Hope you are enjoying the course!

Regards.
