### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by adityab-shivamoon** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#525]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
7th step.
Typo found.
Screenshot attached.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/128153803/a43f7648-721f-4602-b4ef-071dc867d057)

**Comment by johnshea** [comment]
Hi @adityab-shivamoon 

Thank you for letting us know.

It has been fixed and the lesson will be republished again in the near future.

Hope you are enjoying the course.

Regards.
