### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by JeanMarcBilly** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#527]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Je pense que cette affirmation de la documentation française est fausse, et elle ne correspond pas aux exemples.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @JeanMarcBilly 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
