### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by smoothlikeyeager** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#529]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
Task 9 (Add Greeting to the App), Final Result Image

**Describe the problem**
In the final result image, the text is not vertically centered with the instructions as written. In my case, it is horizontally centered and vertically aligned to the top of the screen rather than the center.

I verified that I didn't create the problem through a mistake by copying the code from the next step and rebuilding the project and seeing the same problem.

**Steps to reproduce?**
1. Go to the code lab step #10 at https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#9
2. Copy the code here and build it.
3. Observe that the box containing "Happy Birthday Sam! From Emma" is at the top of the screen rather than vertically aligned as represented in the final image of step #9.

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1 Patch 4, Build #AI-223.8836.35.2231.11090377, built on November 13, 2023
_API version of the emulator:_ 34

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Result of current code
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/141099425/0bf9d5a8-7959-4154-9b5f-54d05e79c3fa)

Expected result from Task #9
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/141099425/41e31005-709d-4dd0-a097-daf314484f5e)

**Comment by johnshea** [comment]
Hi @smoothlikeyeager 

Thank you for writing in with your issue.

The lesson has been updated to address various issues.

If you have time, please try the lesson again and let us know if you are still experiencing an issue.

If you are, please provide your full code and an emulator screenshot so we can you troubleshoot further.

Regards.
