### ISSUE TITLE
Parameters 

### ISSUE THREAD

**Issue by lakshmi-f3** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#53]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

Default Parameters

**Describe the problem**

The default parameters must be mentioned at last in the argument list.

![Screenshot_2022-09-05-17-58-42-288_com android chrome](https://user-images.githubusercontent.com/95603350/188450648-32bf94c6-ff82-44ce-bae4-d772f24009be.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@lakshmi-f3 
Thank you for reaching out to us. 
In Kotlin that is just a guidance, not a recommended best practice. 
https://kotlinlang.org/docs/functions.html#default-arguments

> If a default parameter precedes a parameter with no default value, the default value can only be used by calling the function with [named arguments](https://kotlinlang.org/docs/functions.html#named-arguments)

Hope this helps.
