### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by devjsullivan** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#531]
**URL of codelab**
[Practice Problems: Kotlin Basics](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#8)

**In which task and step of the codelab can this issue be found?**
12. This lab is titled "Practice Problems: Kotlin Basics," but step 12 has Solution code from some other codelab maybe (?, I can't find which one), which doesn't seem fitting for the meaning of this lab. The link to this step is here: [Step 12](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11)
I'm thinking [step 11](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#10)'s **Next** button should go right to [13. Additional Practice](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#12).

**Describe the problem**
The lab has a page that is irrelevant to the lab's intended content.

**Steps to reproduce?**
1. Go to [Step 11](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#10)
2. Click on the Next button in the bottom right corner.
3. See that it takes you to a page with Solution code. Why?

**Versions**
_Android Studio version: N/A
_API version of the emulator: N/A

**Additional information**
![step12](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/25830676/a9edf45b-727c-4e32-8942-347920950163)

**Comment by johnshea** [comment]
Hi @devjsullivan 

Thank you for writing in with your issue.

The "Step 12 Solution Code" page has solutions for all the practice problems from "Step 2 Print Messages" through "Step 11 Move duplicate code into a function".

Hope this clears up the confusion.

Regards.

**Comment by devjsullivan** [comment]
I knew the solution looked familiar as if I had just written it (because I did), but I did not do enough back stepping to realize I had just done it in this codelab. So, my bad.
Confusion is cleared up, thanks!
