### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Devintion** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#533]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**
At heading "**3. Add an Image composable**", on the section under subheading "**Preview Image composable**". The numbered sentence "_In the BirthdayCardPreview() function, replace the GreetingText() function call with a GreetingImage() function call_"

**Describe the problem**
Is the **GreetingText()** function call in the **Oncreate fucntion** also replaced by a **GreetingImage()** function call?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2023-12-03](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/86307458/43555e7e-ad5c-4a17-9fa4-10508edf551e)

**Comment by johnshea** [comment]
Hi @Devintion 

Thank you for writing in with your question.

This section is strictly related to previewing the UI in Android Studio.

Later in lesson "Add Box layout", there are instructions on how to update the `onCreate()` function.

Hope you are enjoying the course!

Regards.
