### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by ocochard** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#534]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5

**In which task and step of the codelab can this issue be found?**

6. Conventions de codage

**Describe the problem**

Wrong french translation about the variable name coding style:
Article said "Les noms des variables doivent être en majuscule et commencer par une lettre minuscule."
Which mean in English that variable name must be in UPPERcase and start by a LOWERcase: There is a word inversion here.

**Comment by johnshea** [comment]
Hi @ocochard 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
