### ISSUE TITLE
Issue in Variable Declaration with Value: Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by himanshumss** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#535]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
As it is mentioned that if we are initializing value in the variable at the time of declaration, We don't need to specify the type of Variable. But when we are doing this, It is showing error. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
As no additional feedback was provided, I am closing this issue.
