### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by duenyo** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#537]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#1

**In which task and step of the codelab can this issue be found?**
Data Types

**Describe the problem**
Less of a problem, more of a lack of clarity. We are told to look at a YouTube video with 7.3k likes and asked what data type the Likes are. While the likes are undoubtedly an Int as it is said in the tutorial the way that they are expressed (7.3k) is a String, and the fact that we are told that numbers with a decimal is a Float could further add confusion. Again, nothing is strictly incorrect, but is most definitely strange and unclear. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @duenyo 

Thank for writing in with your feedback.

You are correct in what you state and that it could cause confusion for a future student.

I will share this concern with the team so they can consider it when making future updates and lesson revision.

Hope you are enjoying the course.

Regards.
