### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by rthnyke** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#539]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#2:~:text=as%20the%20input%3A-,println(2).,-Hence%20the%20output)

**the part that i have highlighted in the link above **

**Describe the problem**
small issue, but i can see that the value println(2) is actually wrong, the 2 should be within commas as println("2"). Its a small issue, no prob, but it seems a bit confusing, since the lesson focusses on variables which dont need those commas :| 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @rthnyke 

Thank you for writing in with your concern.

The code `println(2)` is correct and does not need the quotation marks as you stated. The `println` function can take an integer as an argument.

You can see this in the [Kotlin documentation for `println`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/println.html).

Hope you are enjoying the course.

Regards.

**Comment by johnshea** [comment]
Issue resolved.
