### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by doersweb** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#54]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2)**

**In which task and step of the codelab can this issue be found?**
If you navigate to Practice problem - Task Manager

**Describe the problem**
Go to UI specification of Task Manager problem, in that point 2 asks to set the fontsize to 24sp, which clearly seems off. What we want to achieve based on screenshot is a bold text.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @doersweb,

Thanks for reaching out to us and reporting your concern. The UI specification is updated:

![Screenshot 2023-01-10 at 3 59 40 PM](https://user-images.githubusercontent.com/86437155/211687438-19e1afc8-016d-4d32-8da8-38b0ad7752f9.png)
