### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Torris-Yin** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#540]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dzh-cn#1

**In which task and step of the codelab can this issue be found?**
Variables and data types

**Describe the problem**
_Name of the location is text, so it can be stored in a variable whose data type is String._
The period in this sentence should not be inside the code block, otherwise it may confuse the reader.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/40558217/d7bff72f-64be-4b32-832b-f5e319a40c1a)

**Comment by johnshea** [comment]
Hi @Torris-Yin 

Thank you for bringing this to our attention.

The lesson has been updated and it will be republished again in the near future.

Hope you are enjoying the course.

Regards.
