### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by devjsullivan** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#541]
**URL of codelab**
[Add images to your Android app](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images)

**In which task and step of the codelab can this issue be found?**
[3. Add an Image composable](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2)

**Describe the problem**

**Steps to reproduce?**
1. Go to heading: **Resources in Jetpack Compose** -> **Accessing resources**
2. Count to the fifth paragraph starting with "Android Studio displays an error that says that"
3. The second sentence is "the arguments don't match the function signature."
4.  Because this is a new sentence, the first word should be capitalized, or "**T**he arguments don't match the function signature." instead

**Versions**
_Android Studio version: N/A
_API version of the emulator: N/A

**Additional information**
![capitalizedThe](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/25830676/9e8f73e5-784e-4c98-9c83-f02d378b8770)

**Comment by johnshea** [comment]
Hi @devjsullivan 

Thank you for writing in and bringing this to our attention.

The section has been revised and republished.

Hope you are enjoying the course!

Regards.
