### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by devjsullivan** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#542]
**URL of codelab**
[Add images to your Android app](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images)

**In which task and step of the codelab can this issue be found?**
[7. Adopt good code practices](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6)

**Describe the problem**
After translating the "Happy Birthday Sam!" string to a string resource, a Note text block in the codelab says "Some Android Studio versions replace the hardcoded string with the getString() function. Please manually change the function to stringResource() in such cases."
But following this direction gives the build error: "Unresolved reference: stringResource" when using Android Studio Hedgehog | 2023.1.1, until one hovers over the red stringResource code and continues to _import_ this functionality. This last _import_ step might need to be added to the Note text block for clarity.

**Steps to reproduce?**
1. In onCreate, translate the `Happy Birthday Sam!` string to a string resource.
2. Highlight `getString` in the code that results and replace it with `stringResource`
3. After a **Build & Refresh** click in the preview window, see error `Unresolved reference: stringResource` in the Build Output window under MainActivity.kt, which is resolved after adding line `import androidx.compose.ui.res.stringResource` to the top of the MainActivity.kt file.

**Versions**
_Android Studio version: Hedgehog | 2023.1.1
_API version of the emulator: 31

**Additional information**
![stringResourceNeedsImport2](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/25830676/260287fc-12b9-460c-85da-302af6d62f49)
![buildOutputWithBox](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/25830676/c16053a8-4853-41f6-b557-3beec1c0aadf)

**Comment by johnshea** [comment]
Hi @devjsullivan 

Thank you for bring this issue with a missing import to our attention.

The lesson has been revised and will be republished again in the near future with this addition.

Regards.
