### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by yesitisme** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#545]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#6)**

**[7. Add another text element](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#6)**

**When it says to add the from parameter, it doesn't set a default value, and it says to add another Text composable with from parameter, without adding a from in the first Greeting which causes an error **

**Steps to reproduce?**
1. Follow the instructions till section 7. part 3.
2. the following will error out unless you set a default value to `from: String = ""`, or add a from argument in the first Text() 
@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    Text(
        // ...
    )
    Text(
        text = from
    )
}

**Comment by johnshea** [comment]
Hi @yesitisme 

Sorry for the confusion you experienced.

In part 6 it provides the instruction to add this additional parameter that was causing the error message from part 3.

Hope this helps clarify it.

Regards.
