### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by zimablu3** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#548]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?hl=pt-br&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#7

**In which task and step of the codelab can this issue be found?**
Task: Create your first Android application, Step: 8 (solution code)

**Describe the problem**

The surface container parameter from GreetingCardTheme was changed to "Surface(color = MaterialTheme.colors.background)", when the right one (not changed in this task) is: "Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) "

So, also the import line for fillMaxSize() is missing: "import androidx.compose.foundation.layout.fillMaxSize"

**Steps to reproduce?**
1. Go to...n/a
2. Click on...n/a
3. See error...n/a

**Versions**
_Android Studio version:_Android Studio Giraffe | 2022.3.1 Patch 3
Build #AI-223.8836.35.2231.11005911, built on October 25, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-91-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Current Desktop: Undefined
 
_API version of the emulator:_n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @zimablu3 

Thank you for writing in and bringing these to our attention.

The lesson is being updated and will be republished again in the near future with fixes.

Hope you are enjoying the course!

Regards.
