### ISSUE TITLE
Incorrect library calls

### ISSUE THREAD

**Issue by paulfilkin** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#549]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Surface(color = MaterialTheme.colors.background)

**Describe the problem**
The library used doesn;t support .colors.background
You need to use this:
Surface(color = MaterialTheme.colorScheme.background)
As a complete newbie to programming of any kind it took me a while to figure that simple thing out!

**Steps to reproduce?**
Try to follow the instructions in the course.  You will always have this error "Unresolved reference: colors"

**Comment by johnshea** [comment]
Hi @paulfilkin 

Thank you for writing in about this issue.

All references have been fixed as needed and the revised content will be republished again in the near future.

Hope you are enjoying the course!

Regards.
