### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Phanes123** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#551]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8)**

**In Align greeting to the center task of Step 9 of the codelab**

**for centering the greeting you have used verticalArrangement = Arrangement.Center this won't center the greeting vertically**

**Steps to reproduce?**
1.Before that add modifier = modifier.fillMaxHeight( ) or modifier.fillMaxSize( )...

**Versions**
_Android Studio version:_  Android Studio Hedgehog | 2023.1.1
_API version of the emulator:_  API_34

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Phanes123 

Thank you for writing in.

Please provide screenshots of all your code and a screenshot of it running on the emulator.

This will help us troubleshoot it further.

Regards.

**Comment by johnshea** [comment]
Hi @Phanes123 

As we have not received a response, if you are still experiencing a problem please create a new issue with the requested information.

Regards.
