### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by vasugupta9** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#553]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#1

**In which task and step of the codelab can this issue be found?**
Step 2 : Set up your app

**Describe the problem**
Unable to download androidparty.png image from the provided github link. Nothing happens when clicking on the download button. Tried with both Safari and Chrome browsers

**Steps to reproduce?**
1. Open the image for your birthday card app from this [link](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/res/drawable-nodpi/androidparty.png)
2. Click on download button (download raw file)
3. Nothing happens on clicking download button

**Versions**
NA
NA

**Additional information**
NA

**Comment by johnshea** [comment]
Hi @vasugupta9 

I can confirm that the link is working.

Depending on where you are located in world, links might not work as expected.

Regards.

**Comment by vasugupta9** [comment]
Hi @johnshea 

Thanks much for the reply. 

I rechecked and the link+download is also working for me now but for some reason it was not working when I reported it !

Thanks and Regards
