### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by vasugupta9** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#554]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Step 4 : Add Box Layout

**Describe the problem**
Towards the end of step4 it is mentioned 'Your setContent block should look like this code snippet'
setContent {
    HappyBirthdayTheme {
       // A surface container using the 'background' color from the theme
        Surface(color = MaterialTheme.colors.background) {
            GreetingImage("Happy Birthday Sam!", "From Emma")
        }
    }
}

However,   
1. Surface(color = MaterialTheme.colors.background) differs from the default setting which is 

Default Setting 
Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                )

2. Surface(color = MaterialTheme.colors.background) also differs from final solution code (Step 9 Get the solution code)

3. Changing code to Surface(color = MaterialTheme.colors.background) shows an error in Android Studio

**Steps to reproduce?**
1. Change code to Surface(color = MaterialTheme.colors.background) 
2. See error related to unresolved reference for 'colors'

**Versions**
Android Studio Hedgehog | 2023.1.1
API 34

**Additional information**
NA

**Comment by johnshea** [comment]
Hi @vasugupta9 

Thank you for writing in about this issue.

The lesson has been updated and republished to address it.

Hope you enjoying the course.

Regards.

**Comment by vasugupta9** [comment]
Great. Thanks !
