### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by 2e7fhchbd** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#559]
**URL of codelab**

**[What is Jetpack Compose?](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables#2)**

** I'm not able to view my work in android studio in the split part**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi.

Closing the issue as there has been no follow up.

Please reopen if you are still experiencing a problem.

Regards.
