### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by mrSir7** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#56]
**URL of codelab:** 
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images&authuser=1#3

**In which task and step of the codelab can this issue be found?**
Writing: *Image(painter = image)*

**Describe the problem**
Whenever I try to write *Image(painter = image)* it doesn't work.
It seems like android studio does not recognize the command *painter*.

The word *painter* turns red and there are 4 error codes.
*Cannot access '<init>': it is package-private in 'Image'*
*Cannot create an instance of an abstract class*
*Named arguments are not allowed for non-Kotlin functions*
*Cannot find a parameter with this name: painter*

I am very new to coding and android studio and lost - I have searched the whole internet and didn't find a solution yet.

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images&authuser=1#3

2. Follow the guidelines from the codelab, until you are asked to write the *Image(painter=image)* command.
3. See the errors

**Versions**
_Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 2 (latest version)
![Screenshot 2022-09-11 141723](https://user-images.githubusercontent.com/113246258/189528762-e80423c4-234d-4e35-86c2-18eda00c4f36.png)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Habib599** [comment]
I needed to add: import androidx.compose.foundation.Image before it worked...
