### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by sampotter123** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#560]
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
3 Build a simple app with text composables
step 9

**Describe the problem**
you write

"It is a good practice to pass the modifier attribute(s) along with the modifier from the parent composable. Update the modifier parameter in the GreetingText() as follows:"

problem is, you show nothing different than before

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @sampotter123 

Thank you for writing in with your concern.

The difference is that the code `padding(8.dp)` was moved from the inside the function `GreetingText` to  where it calls `GreetingText()` in function `onCreate`.

The padding is now being passed in from the calling function.

Hope this helps explain it.

Regards.
