### ISSUE TITLE
Your first program: Android Basics in Compose

### ISSUE THREAD

**Issue by Serge07cloud** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#562]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D2%26hl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program&authuser=2#4

**In which task and step of the codelab can this issue be found?**
This issue can be found in the compose unit 1 pathway in step 5

**Describe the problem**
In the input **function section**, the printFullName function requires two inputs. The transcription in french is not correct. It is written _Deux fonctions sont requises pour la fonction_ instead of _Deux entrées sont requises pour la fonction_

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Additional information**
<img width="890" alt="Screenshot 2024-01-02 195802" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/69323218/dd09243b-de92-4b3f-896a-9114bb0e5d95">

**Comment by johnshea** [comment]
Hi @Serge07cloud 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
