### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by davimazz** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#563]
How is this for earning when half way through you stop giving solutions? How is anyone supposed to learn when they have not idea if they are correct or not? POINTLESS

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @davimazz 

Thank you for providing your feedback on the course.

I will share your concerns with the team.

Regards.
