### ISSUE TITLE
Not related to a specific Codelab or Section, but the Training in general.

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#564]
If I leave the computer for an hour (lunch, dog walk, zoom meeting, etc.) and come back to continue where I left off, I'M LOGGED OFF EVERY TIME.

So, I continue and finish a code lab and get back to the TOC for the pathway I'm on and there's no checkmark for the step I just finished. So I have to:

1. Log in again
2. Re-select the same code lab I just completed
3. Go to the last step
4. Click done

at which point, finally, it registers my progress.

Why does this system log me out all the time?

**Comment by johnshea** [comment]
Hi @reknoZ 

Thank you for writing in regarding your issue.

I will share it with the team.

Hope you are still able to enjoy the course.

Regards.
