### ISSUE TITLE
The Image function has two required parameters, not just one

### ISSUE THREAD

**Issue by mzcode** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#565]
[URL of codelab](
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2
).

**In which task and step of the codelab can this issue be found?**
3. Add an Image composable
**Describe the problem**
adding `import androidx.compose.foundation.Image`
dont solve error as described 
[here]( https://stackoverflow.com/questions/76398994/error-while-adding-an-image-composable-function-in-android-studio
)

**Versions**
Android Studio Hedgehog | 2023.1.1

**Comment by johnshea** [comment]
Hi @mzcode 

Thank you for writing in about this issue.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
