### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by blOOfins** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#566]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#7

**In which task and step of the codelab can this issue be found?**
Step 8 Default Parameters

**Describe the problem**
The desired output is not possible with the provided main method that is given.

Desired output:
"There's a new sign-in request on Unknown OS for your Google Account user_one@gmail.com.

There's a new sign-in request on Windows for your Google Account user_two@gmail.com. 

There's a new sign-in request on Mac OS for your Google Account user_three@gmail.com. "

Main method given:

fun main() {
    val firstUserEmailId = "user_one@gmail.com"

    // The following line of code assumes that you named your parameter as emailId. 
    // If you named it differently, feel free to update the name.
    println(displayAlertMessage(emailId = firstUserEmailId))
    println()

    val secondUserOperatingSystem = "Windows"
    val secondUserEmailId = "user_two@gmail.com"

    println(displayAlertMessage(secondUserOperatingSystem, secondUserEmailId))
    println()

    val thirdUserOperatingSystem = "Mac OS"
    val thirdUserEmailId = "user_three@gmail.com"

    println(displayAlertMessage(thirdUserOperatingSystem, thirdUserEmailId))
    println()
}

displayAlertMessage:

fun displayAlertMessage(emailId: String, operatingSystem: String = "Unknown OS"): String {
    return("There's a new sign-in request on $operatingSystem for your Google Account $emailId")
}

 Since emailId is the first parameter and operatingSystem is the second, you need to pass the arguments in the same order for the remaining 2 outputs.

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#7

2. Click on... #8 default parameters
3. See error...:

"There's a new sign-in request on **Unknown OS** for your Google Account **user_one@gmail.com**

There's a new sign-in request on **user_two@gmail.com** for your Google Account **Windows**

There's a new sign-in request on **user_three@gmail.com** for your Google Account **Mac OS**"

4. Expected result: 

"There's a new sign-in request on **Unknown OS** for your Google Account **user_one@gmail.com**.

There's a new sign-in request on **Windows** for your Google Account **user_two@gmail.com**. 

There's a new sign-in request on **Mac OS** for your Google Account **user_three@gmail.com**. "

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![android kotlin bug](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/144873617/150583a1-a5f8-4124-9e83-3d29bff5f21f)

**Comment by johnshea** [comment]
Hi @blOOfins 

Thank you for writing in.

You need to reverse the parameters in your function so it matches this code...
`fun displayAlertMessage(operatingSystem: String = "Unknown OS",emailId: String): String {`
and everything will work as expected.

The code snippet provided in the practice problem has the OS as the first parameter as shown `println(displayAlertMessage(operatingSystem, emailId))` and your code is not following this.

Hope you are enjoying the course!

Regards.
