### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Kanak883** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#567]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#0**

**In which task and step of the codelab can this issue be found?**
In "
Create and use variables in Kotlin" > Before you begin 

**Describe the problem**
The image showing the screenshot of settings page, there are 2 camera cutouts.

**Steps to reproduce?**
1. Go to Create and use variables in Kotlin
2. Click on Before you begin
3. See the image of settings page

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
<img width="217" alt="Screenshot 2024-01-10 165947" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/86999149/d13c15e7-8355-402c-bfc2-dad04c319d4e">

**Comment by johnshea** [comment]
Hi @Kanak883 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
