### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by MayankKrSohanda** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#568]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#6

**In which task and step of the codelab can this issue be found?**
7. Commenting in your code

**Describe the problem**
There is an extra asterisk symbol when displaying a multi-line comment. It resembles Kotlin Documentation Comment (KDoc) style rather than a standard multi-line comment.

**Steps to reproduce?**
1. Go to Create and use variables in Kotlin
2. Click on Commenting in your code
3. Scroll till you find “This program contains single-line and multi-line comments that describe what's happening:”
4. In the sample code, there is an extra asterisk symbol in line 1.

**Versions**
_Android Studio version: NA
_API version of the emulator: NA

**Additional information**
![Create and use variables in Kotlin and 9 more pages - Personal - Microsoft​ Edge 01_10_24 19_41_00](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/71868209/8c9d890c-ec25-4d01-9451-94082e1d8038)

**Comment by johnshea** [comment]
Hi @MayankKrSohanda 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again in the near future.

Hope you are enjoying the course!

Regards.

**Comment by MayankKrSohanda** [comment]
> Hi @MayankKrSohanda
> 
> Thank you for writing in and bringing this to our attention.
> 
> The lesson has been updated and will be republished again in the near future.
> 
> Hope you are enjoying the course!
> 
> Regards.

Happy to help.
