### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by thebusybeebap** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#57]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4)

In Explore Other Data Types, Double, number 2., Your whole program should look like the below code:

Provided code solution has val used for totalTripLength instead of var
fun main() {
    val trip1: Double = 3.20
    val trip2: Double = 4.10
    val trip3: Double = 1.72
    val totalTripLength: Double = trip1 + trip2 + trip3
    println("$totalTripLength miles left to destination")
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/112837745/189784665-c8cf517c-e2e3-4086-ab54-e38999e18bba.png">

**Comment by osuleymanova** [comment]
@thebusybeebap 
Thank you for reaching out to us. The explanation why val used for totalTripLength variable instead of var is provided in the codelad:

![Screen Shot 2022-09-19 at 2 36 23 PM](https://user-images.githubusercontent.com/86437155/191124499-437e3625-8eb0-46ac-b076-f401b7807797.png)
