### ISSUE TITLE
Before you begin: Android Basics with Compose

### ISSUE THREAD

**Issue by MrLuigiBean** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#570]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-before-you-begin#0

**In which task and step of the codelab can this issue be found?**
Under the "Other training materials" heading, where the link to "Android Basics in Kotlin course" is located.

**Describe the problem**
Clicking on the link to "Android Basics in Kotlin course" will redirect to the "Android Basics with Compose" course instead of the the Kotlin course.

**Steps to reproduce?**
1. Go to the "Other training materials" section of this codelab.
2. Click on the link with the text "Android Basics in Kotlin course".
3. See the error, which is the link not redirecting to the Kotlin course.

**Versions**
_Android Studio version:_  - 
_API version of the emulator:_  -

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/84760999/64941ed6-d2ec-4261-81cb-0df2f0eb8401)

**Comment by johnshea** [comment]
Hi @MrLuigiBean 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and this issue has been resolved.

Hope you are enjoying the course.

Regards.
