### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by TaymourlankFarawilla** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#574]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#2

**In which task and step of the codelab can this issue be found?**
Notice the previous function also has another annotation, a @Preview annotation, with a parameter before the @Composable annotation. You learn more about the arguments passed to the @Preview annotation later in the course.

**Describe the problem**
the word arguments should be changed to parameters

**Steps to reproduce?**
1. Go to... 
'Build a simple app with text composables'
2. Click on... 'What's Jetback Compose?'
4. See error... at paragraph just before 'Composable function names'

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2024-01-16](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/156724990/64e32b6e-22a7-405e-85b1-ad8acd5276e5)

**Comment by johnshea** [comment]
Hi @TaymourlankFarawilla 

Thank you for writing in with this issue.

I will share it with the team so they can evaluate and decide the most appropriate action.

Hope you are enjoying the course.

Regards.
