### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by inkarus** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#579]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=ja&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4

**In which task and step of the codelab can this issue be found?**
Japanese version of the codelab pages.

**Describe the problem**
In these pages, a data type of "Double" and "Float" are explained as "小数". In general, these data type are "実数" in Japanese.  

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @inkarus 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
