### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by LuchoDiaz** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#58]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2

**In which task and step of the codelab can this issue be found?**
[3. Return a value from a function](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2)

**Describe the problem**

fun birthdayGreeting(): Unit {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}
**No main method found in project.**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/113719855/190712177-9e0eba54-2774-43a1-9318-a8427e3e41fd.png)

**Comment by osuleymanova** [comment]
@LuchoDiaz 
Thank you for reaching out to us. The main() function was defined in the step 2 "Define and call a function":

![Screen Shot 2022-09-19 at 1 26 56 PM](https://user-images.githubusercontent.com/86437155/191110555-0f9e05f8-8db7-4a74-b5fc-4b55908355d9.png)
![Screen Shot 2022-09-19 at 1 26 11 PM](https://user-images.githubusercontent.com/86437155/191110569-045dd821-eb08-49ef-9cd3-a5b37399e784.png)
