### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by mzuociling** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#580]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

My English proficiency is limited, and I am a beginner focusing on Android development. Therefore, I am unsure if there are any conceptual errors in the following text.

”You can pass multiple parameters to the annotation, as shown here.“

I noticed that in the example (@preview), it seems to be more like 'arguments' rather than 'parameters'.

**Steps to reproduce?**
1. Go to... https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-3#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables
2. Click on... Build a simple app with text composables , 3. What is Jetpack Compose?
3. See error...
![error](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154315377/373a5c11-a777-453d-a868-414534160f6c)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @mzuociling 

Thank you for bringing this to our attention.

The lesson has been updated to say "arguments".

The revised lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
