### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by jlopez0127** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#581]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**

Add Box Layout>  step one 

**Describe the problem**

painterResource(R.drawable.androidparty)
not the proper code. the correct code is (id = R.drawable.androidparty)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @jlopez0127 

Thank you for writing in with your feedback.

Can you provide a screenshot of the error message you see and also of your code?

Hopefully we will be able to help troubleshoot your issue.

Hope you are enjoying the course.

Regards.

**Comment by jlopez0127** [comment]
Hello,

I realized it was an issue on my end. That part of the code needed an R.drawable and using id= worked for me now but turns out i didn't do the code right.

I do have another question though, will there be a video tutorial. I am more of a visual learner so it's a bit difficult to Follow along when its mostly readings.

Thank you,
Julian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johnshea** [comment]
Hi @jlopez0127 

Thank you for following up and glad to learn that you were able to resolve your issue.

We are constantly re-evaluating our content so I will provide your feedback to the team regarding a video for this lesson.

Hope you are enjoying the course.

Regards.
