### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by acorchuelo** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#582]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2&hl=es-419#7

**In which task and step of the codelab can this issue be found?**
when try to change de option padding, in the example code have the expression "modifier = modifier", and that mark error

**Describe the problem**

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @acorchuelo 

If you are still having an issue, please create a new issue with the requested information so we can help you troubleshoot.

Regards.
