### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by MoeRayo** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#586]
**URL of codelab**
[Add greeting to the app](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8)

**In which task and step of the codelab can this issue be found?**
_Task_: **9 - Add greeting to the app**
_Step_: **Align greeting to the center**

**Describe the problem**
In this task, the reader is expected to make the text align vertically on the screen using ` verticalArrangement = Arrangement.Center,` within the `Column`  compose layout. However, using this parameter alone does not do anything. Instead the texts remain unchanged and stay glued to the top of the screen as if the parameter was not added at all.

**Steps to reproduce?**
1. Go to task 9
2. Follow the steps up until that point and add the ` verticalArrangement = Arrangement.Center,`  parameter to the code
3. See that the screen remains unchange and the texts do not get aligned to the center of the screen (as expected in the codelab)

**Versions**
_Android Studio version:_  Android Studio Hedgehog
_API version of the emulator:_  33.1.24

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
After adding the  ` verticalArrangement = Arrangement.Center,`, the screen remains as the below:

![Screenshot_20240128_002430](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/48064606/00532a5a-c201-439a-bbf8-7ce1df3e89cc)

However, I realised that to fix this, we need to also add this line: `modifier = modifier.fillMaxSize()`
Now the `Column` parameter will look like so:
```js
Column( verticalArrangement = Arrangement.Center,
        modifier = modifier.fillMaxSize()) {
    Text(...)
    Text(...)
}
```

Now the screen will look like this:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/48064606/047b802d-bc7f-4776-a696-f5c0e857a407)

Also, if and when this fix is made in task 9, the 10th task in this codelab - [Get code solution](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#9) will also have to be updated with the working code to match the changes in task 9 corresponding with aligning the column vertically.

Thank you

**Comment by johnshea** [comment]
Hi @MoeRayo 

Thank you for writing in with your issue.

I tried duplicating it from you description but was unable.

Please provide your full code for `MainActivity.kt` that will duplicate this issue.

Please also provide screenshots of this code running on your emulator so we can visually see the output.

Look forward to your response.

Regards.

**Comment by johnshea** [comment]
Hi @MoeRayo 

As we have not received a follow up from you, the issue will be closed at this time.

If you are still experiencing the problem, please create a new issue and provide the requested information.

Regards.
