### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by uttammanher** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#589]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4

**In which task and step of the codelab can this issue be found?**
fun main() {
    val trip1 = 3.20
    val trip2 = 4.10
    val trip3 = 1.72
    val totalTripLength = trip1 + trip2 + trip3
    println("$totalTripLength miles left to destination")
}

**Describe the problem**
Codlab tutorial says that "Run your code again to ensure that your code still compiles. The output should be the same, but now your code is simpler!" which means output should be the same. Which works fine in Kotline Playground.

But. When I slightly modify the code :
fun main() {
    val trip1 = 2.03
    val trip2 = 3.04
    val trip3 = 5.06
    val totalTrip = trip1 + trip2 + trip3
    println("Total length : $totalTrip")
    
}
The Output is 
Total length : 10.129999999999999

Which I think is incorrect. Because totalTrip variable should have been stored as a Double.

**Steps to reproduce?**
Here is the code
https://pl.kotl.in/YGF4Z0f8W

![Screenshot (43)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/29499096/464495b2-393c-4a3f-a8cb-b10726ef0e6e)

**Additional information**
Screenshot is attached.

**Comment by johnshea** [comment]
Hi @uttammanher 

Thank you for writing in.

`Double` can have multiple numbers after the decimal. It is not limited to two.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-double/

Hope this helps.

Regards.
