### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Butterlegz** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#59]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#6

**In which task and step of the codelab can this issue be found?**
2

**Describe the problem**
fontSize is not an argument of the Text function

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Butterlegz 
Thank you for reaching out to us. There is no error in the codelab content. To get more info about the arguments in the Text() function, please refer to the following URL:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Text.kt
line 91 and line 95.
You can also find the relevant info by opening the project in Android Studio:

![Screen Shot 2022-09-19 at 1 05 30 PM](https://user-images.githubusercontent.com/86437155/191108743-adf5e2aa-0a8f-41e4-9cd2-1df9593458a0.png)
