### ISSUE TITLE
Unclear or untrue statement regarding the style guidelines. [Typo?]

### ISSUE THREAD

**Issue by AntysIQ** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#595]
### URL of codelab
[5 - Create and use functions in Kotlin](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2)

### In which task and step of the codelab can this issue be found?**
(3.) Return a value from a function - In the line 6f

### Describe the problem
Just a little typo?
- "A single space is placed [after]() the [_return type_]() [and before]() the [opening curly brace.]()"

This would result in a double space after the _return type_,
like in this example with "Int" as the _return type_:
```
fun main():Int  {
    'Code Here'
}
```

### Steps to reproduce?
1. Go to line 6 in URL of codelab
2. Read
3. Think

### Versions
_Android Studio version:_ X
_API version of the emulator:_ X

### Additional information
> **Statement:**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/100484970/faae3791-dd42-4031-9156-2348b1e5f048)

> **The expected style:**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/100484970/39b2ff15-0413-4b4a-b70e-4966e199c9c9)

**Comment by johnshea** [comment]
Hi @AntysIQ 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and with be republished again with the fix in the near future.

Hope you are enjoying the course!

Regards.
