### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by emanvidmaker** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#598]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator#1

# **In which task and step of the codelab can this issue be found?**

in video [Run your first app on the Android Emulator code-along](https://youtu.be/HyOejjpVFtQ) At 1:06  
(See Screenshots)

# **Describe the problem**
Devise manager is not located in the menu shown on the tutorial on newer versions install. its on the right side of the panel (this took me a while to figure it out)

# Screenshots
## Tutorial shows:
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16447282/80fe1b04-4fe0-475b-9385-48f746faaccb)

## My fresh install:
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16447282/0adb3f06-2c78-4906-b41b-acea2ca834f5)
## Correct location:
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16447282/bcc6e89e-51a8-4efd-99e4-a8132458db1e)

**Comment by johnshea** [comment]
Hi @emanvidmaker 

Thank you for writing in with your concern.

You have the "New UI (Beta)" setting enabled which is causing this discrepancy.

If you turn off this option, it will be as described in the lesson.

Hope you are enjoying the course!

Regards.
