### ISSUE TITLE
Your first program: Android Basics in Compose

### ISSUE THREAD

**Issue by VikingRock** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#6]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program#6)

Heading style - [7. Kotlin style guide]

Line height property is not big enough so that lower tails of 'g' and 'y' are cut

**Steps to reproduce?**
1. Open webpage at the defined URL

**Versions**
Chrome on Mac

**Comment by osuleymanova** [comment]
@VikingRock 
Thank you for reaching out to us. It's intentional.
