### ISSUE TITLE
Add function error

### ISSUE THREAD

**Issue by irinaalexandran** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#60]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

Practice Problems: Kotlin Basics
task 7 : [Implement basic math operations](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#6)

**Describe the problem**
add function is not working in kotlin playground

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/113902892/191005146-53a44b39-c009-4511-8187-ce4c1af00919.png)

**Comment by osuleymanova** [comment]
@irinaalexandran 
Thank you for reaching out to us and providing the screenshot. The error occurred as add() function was not defined as requested. Please refer to the screenshot below:

![Screen Shot 2022-09-19 at 10 40 33 AM](https://user-images.githubusercontent.com/86437155/191080177-ec95f42d-7185-43a3-bff7-0448306c190c.png)
