### ISSUE TITLE
Replace GreetingText() with GreetingImage()

### ISSUE THREAD

**Issue by tamiromara** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#600]
**URL of codelab**
[https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#5](url)

**In which task and step of the codelab can this issue be found?**
Adding Images to your Android App.
Part 6 : Align and arrange Text.
Scroll down to where it reads "**Your turn!**"

**Describe the problem**
It's just a typo. The line currently reads:

> Your turn! In the MainActivity.kt file, scroll to where the GreetingText() function is called and notice the padding attribute.

It should read instead:
Your turn! In the MainActivity.kt file, scroll to where the **GreetingImage()** function is called and notice the padding attribute.

**Steps to reproduce?**
Not applicable

**Versions**
Not applicable

**Additional information**
<img width="971" alt="Screenshot 2024-02-14 at 2 57 14 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/5858257/49226a9d-f3b6-493b-9d95-7ddf56c705f8">

**Comment by johnshea** [comment]
Hi @tamiromara 

Thank you for writing in with your concern.

The wording in the lesson is correct.

The student needs to scroll to where the `GreetingText()` function is called. You are correct that it is *in* the `GreetingImage()` function though.

Hope this helps clarify it.

Regards.
