### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ZoranGrozdanic** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#609]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
When you try to run it or view it in the Design view.

**Describe the problem**
If you want the GreetingText with it's Text-s inside the Column widget to appear in the middle of the screen, you have to change the code in the Column widget and replace: "modifier = Modifier," with "modifier = Modifier.fillMaxSize()" in the arguments section. (Row:52 in my code)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Hedgehog 2023.1.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ZoranGrozdanic 

Thank you for writing in with your issue.

As you did not provide any screenshots, I am unable to review what you coded.

Please review https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/599 as it sounds like it could be the same issue you are experiencing.

If not and you still have a problem, please provide screenshots of UI and all your code in `MainActivity.kt` so we can troubleshoot further.

Hope you are enjoying the course!

Regards.
