### ISSUE TITLE
Minor Grammar Mistake in Text Composables

### ISSUE THREAD

**Issue by peakDuringSeason** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#611]
**URL of codelab**
[https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables)

**In which task and step of the codelab can this issue be found?**
Step: Arrange the text elements in a column

**Describe the problem**
There is a missing space after a full stop punctuation mark in the instruction text!

> "to the child element in the composables.That means you"

**Steps to reproduce?**
1. Open given codelab
2. Find "Arrange the text elements in a column" step
3. See error!

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/160190167/4ac570b8-9bf8-4ffe-9746-bcdd9c641fe1)

**Comment by johnshea** [comment]
Hi @peakDuringSeason 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again with the fix in the near future.

Hope you are enjoying the course!

Regards.
