### ISSUE TITLE
Text composables: Android Basics with Compose /  missing modifier.fillMaxHeight() under Column

### ISSUE THREAD

**Issue by bamIV** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#613]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables&hl=en#8)**

**In which task and step of the codelab can this issue be found?**
[Build a simple app with text composables](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables&hl=en)

**Describe the problem**
The screenshot at the end of the task shows the text created in the exercise vertically centred on screen of the device.
The code in the exercise and the following task [10. Get the solution code](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables&hl=en#9) do not actually accomplish this.

The correct code would include: 
    Column(
        verticalArrangement = Arrangement.Center,
        modifier = modifier.fillMaxHeight() // <-- fillMaxHeight() has to be added to resemble the screenshot correctly.
    )

**Comment by android-dev-lxl** [comment]
@bamIV 
Thank you for reaching out. You do not need `fillMaxHeight()` modifier for the column.
The `fillMaxSize()` modifier is already applied on the `Surface` container.


```
Surface(
    modifier = Modifier.fillMaxSize(),
    color = MaterialTheme.colorScheme.background
) {
       //....
}
```
<img width="336" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/24260141/9ae29ac4-a395-4b56-a85b-51f747ab43f0">


Could you please send us your screenshot with error and the code snippet?

**Comment by johnshea** [comment]
Hi @bamIV 

As we have not received a follow up from you, the issue will be closed at this time.

If you are still experiencing the problem, please create a new issue and provide the requested information.

Regards.
