### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by boswelja** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#617]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**

Step 12

**Describe the problem**

The solution for "Move duplicate code into a function" should use named parameters.

**Additional information**

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/15526339/97676fa8-6c70-413c-8f10-c6fa689ec56a)

**Comment by johnshea** [comment]
Hi @boswelja 

Thank you for your feedback.

I will share it with the team so they can evaluate and revise as needed.

Regards.
