### ISSUE TITLE
Business Card app: Android Basics with Compose

### ISSUE THREAD

**Issue by boswelja** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#618]
**URL of codelab**
https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-3

**In which task and step of the codelab can this issue be found?**
Codelab 6

**Describe the problem**

It seems like the goal of this pathway is to build a birthday card app, but the codelab where you'd build that segment is actually describing a business card app.

This doesn't seem right?

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/15526339/2903bb24-7bc6-42ce-b674-50745efcd996)

**Comment by johnshea** [comment]
Hi @boswelja 

Thank you for your bringing this to our attention.

I will share it with the team so they can evaluate and revise as needed.

Regards.
