### ISSUE TITLE
Your first program: Android Basics in Compose

### ISSUE THREAD

**Issue by fulgurio** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#619]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?hl=fr#4)

**In which task and step of the codelab can this issue be found?**
Step 5 "Composantes d'une fonction", on "Entrées d'une fonction" subpart.

**Describe the problem**
Mistake on translation :
your mean "Deux **entrées** sont requises pour la fonction, l'une pour le prénom et l'autre pour le nom de famille" in "Dans l'exemple suivant, la fonction s'appelle printFullName. Deux _fonctions_ sont requises pour la fonction, l'une pour le prénom et l'autre pour le nom de famille" sentence

**Comment by johnshea** [comment]
Hi @fulgurio  

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
