### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by DreamingDroid** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#621]
URL of codelab(https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#5)

Tutorial Name : 'Add images to your Android app'

Under Section : 'Align and arrange the Text' , in Point Number 1
"Your turn! In the MainActivity.kt file, scroll to where the GreetingText() function is called and notice the padding attribute.".

The function in the above line should be 'GreetingImage()' and not 'GreetingText()'

<img width="584" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/30039616/ea571915-7266-42e8-bffa-440a195aedf3">

**Comment by johnshea** [comment]
Hi @DreamingDroid 

Thank you for writing in with your concern.

The wording in the lesson is correct.

The student needs to scroll to where the GreetingText() function is called. You are correct that it is in the GreetingImage() function though.

Hope this helps clarify it.

Regards.
