### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ajay29592** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#626]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#7)**

**In which task and step of the codelab can this issue be found?**
in step 8 i found a typo error.

**Describe the problem**
there is a typo error in step 8 first hint section . it should be change the alignment parameter rather than chain the alignment parameter

**Steps to reproduce?**
1. Go to link 
2. Click on step 8 
3. See error in hint section 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/17155584/ea176e99-0485-4037-a03e-f3d10d92dac6)

**Comment by RudraOp9** [comment]
@ajay29592 dear there's no typo in the statement by saying chain , it means situate the text layout according to parent modifier layout.
