### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by seringl** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#629]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
Add images to your android app, step 3, and an image composable

**Describe the problem**
After adding the background image I kept receiving the error "Render problem" and it wouldn't display the image on either the design preview or the emulator.

**Steps to reproduce?**
1. Follow the steps in the codelab

**Versions**
_Android Studio version:_
Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 21, 2024
Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    ide.experimental.ui=true

_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
By changing "image" to "img1" it works fine.
![2024-03-17 01-24-55 204](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16721484/f7fd5ac4-6656-4a6c-ae08-f7ffb3dec067)
![2024-03-17 01-23-37 203](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/16721484/d2f3e3f8-a2d9-4dfc-9b26-55dd2d150b4c)

**Comment by RudraOp9** [comment]
@seringl as seen in the first image , the compose is still rendering in the preview , please let the render happen , then send the screenshot again , if the the preview is out of date then kindly rerun the configuration or preview.

**Comment by MainActivityKt** [comment]
I have the exact same issue. As you can see, the build is complete but the preview is lost because of the rendering issue. It happens right after I add the `Image` composable, and call the `GreetingImage` function in preview.

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/76739907/475f9fdc-a908-4356-ba15-09ce66f4ccb1)

**Comment by johnshea** [comment]
Hi @seringl 

Thank you for writing about your issue.

Have you tried complete closing Android Studio and then reopening to see if this resolves the issue?

I have  seen this error and it was an issue with Android Studio and not the actual code.

Regards.
