### ISSUE TITLE
Writing mistakes at the codelab "Add images: Android Basics with Compose"

### ISSUE THREAD

**Issue by EnzoTrulenque** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#631]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3#2

**In which task and step of the codelab can this issue be found?**
Task: 3. Add an Image composable 
Step: Acessing resources

**Describe the problem**

In this step is presented a list of actions, being the fourth one this:
4. Click Import in the popup to add the import for androidx.compose.ui.res.painterResource.

Then, outside of the numbered list, there is this text, and the first mistake happens here. After the comma, preceded by the word resource, there is no space
The painterResource() function loads a drawable image **resource,and** takes resource ID (R.drawable.androidparty in this case) as an argument.

Then, coming back for the list, it should present the fifth item, but it is listed as the third one:
**3.** After the call to the painterResource() function, add an Image composable and then pass in the image as a named argument for the painter.

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3#2
2. Click on Add an Image composable  in the top left
3. See error at the step Acessing resources after the third action

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/91288685/f2a8bc8d-2053-484f-ad1f-09b71e72fa78)

**Comment by johnshea** [comment]
Hi @EnzoTrulenque .

Thank you for writing in and bringing this to our attention.

It has been corrected and the lesson will be republished again in the near future with the fix.

Hope you are enjoying the course!

Regards.
