### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by MrTyre2** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#632]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5)

**In which task and step of the codelab can this issue be found?**
6. Coding conventions

**Describe the problem**
In the french version of the text, we read "Les noms des variables doivent être en majuscule et commencer par une lettre minuscule." 
In english we read "Variable names should be in camel case and start with a lowercase letter."
This has not the same meaning : the french text should either be 
"Les noms des variables doivent être en minuscules." or 
"Les noms des variables doivent être en camel-case et commencer par une lettre minuscule.

Otherwise it says that variable name should start with a lowercase letter and the rest should be in uppercase (like var sOMEVAR, which is nonsense :p)

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#5
2. See error on first item of first list

Thanks for fixing this :)

**Comment by johnshea** [comment]
Hi @MrTyre2 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
