### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by gediz** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#633]
**URL of codelab**
[Build a simple app with text composables](https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables#8)

**In which task and step of the codelab can this issue be found?**
9. Add greeting to the app

**Describe the problem**
Column is not aligned vertically to the parent. It's top begins from top of the parent, expected behavior was it had even space to the top and the bottom.

**Steps to reproduce?**
1. Just follow the steps explained in the codelab and implement them as instructed.

**Versions**
_Android Studio version:_ Android Studio Iguana | 2023.2.1 Patch 1
_API version of the emulator:_ 31 (Emulating on Pixel 8 Pro)

**Additional information**

![alignment_problem](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/5806838/d0c747cd-e9f5-4ea6-935e-286e367f3275)

Code: [HappyBirthday/app/src/main/java/com/example/happybirthday/MainActivity.kt at main · gediz/HappyBirthday](https://github.com/gediz/HappyBirthday/blob/main/app/src/main/java/com/example/happybirthday/MainActivity.kt)

**Comment by gediz** [comment]
Similar with #384

**Comment by johnshea** [comment]
Hi @gediz 

Thank you for writing in.

The preview and emulator you are showing do not match your code.

Your code shows the names Bob and Alice but your images are showing Sam and Emma.

Please re-run your code and if you still have an problem create a new issue.

Hope you are enjoying the course!

Regards.

**Comment by gediz** [comment]
> Hi @gediz
> 
> Thank you for writing in.
> 
> The preview and emulator you are showing do not match your code.
> 
> Your code shows the names Bob and Alice but your images are showing Sam and Emma.
> 
> Please re-run your code and if you still have an problem create a new issue.
> 
> Hope you are enjoying the course!
> 
> Regards.

Hi @johnshea,

It was merely a difference on strings. I've tried with a clean build too but couldn't see the expected result. That's why I've shared the full project link in the repo. Anyways, thanks for your answer.

**Comment by johnshea** [comment]
Hi @gediz 

I created the same emulator "Pixel 8 Pro API 31" and I am running the same version and patch for Android Studio.

I cloned your repo and ran without issue. I did not change anything in your project.

The text is centered as it should be.
<img width="1193" alt="Screenshot 2024-04-01 at 12 07 40 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/79c1b1e6-4d96-4057-bad6-c000302e74b0">



Please try cloning your own repo to a new folder and rerunning to see if it works or has this issue again.

I look forward to your response.

Regards.
