### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by The-Lost-Lucifer** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#635]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3F_gl%3D1*1kds47n*_up*MQ..%26gclid%3DCjwKCAjwnv-vBhBdEiwABCYQA2gHzTyY-PkPqFajGKfWDBXmTdMiZG3Lka3y7Zv2O3lYsrX9Aoy7oxoCc3kQAvD_BwE%26gclsrc%3Daw.ds%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app&_gl=1*1kds47n*_up*MQ..&gclid=CjwKCAjwnv-vBhBdEiwABCYQA2gHzTyY-PkPqFajGKfWDBXmTdMiZG3Lka3y7Zv2O3lYsrX9Aoy7oxoCc3kQAvD_BwE&gclsrc=aw.ds#4

**CHANGE THE BACKGROUND COLOR**
2.  Choose Surround with Container.

**Describing the problem**
So, i tried to follow the steps, but now i find there's error still, and the background of the text with "surround with container" is not changed!

**Comment by johnshea** [comment]
Hi @The-Lost-Lucifer 

Thank you for reporting your issue but we are unable to help you troubleshoot as none of the requested information was provided.

If you are still experiencing your problem, please create a new issue and provide all requested information and screenshots so we can assist you further.

Regards
