### ISSUE TITLE
Practice Problems: Kotlin Basics

### ISSUE THREAD

**Issue by Balaguru1992** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#646]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

**In which task and step of the codelab can this issue be found?**
Implement basic math operations
Step 3

**Describe the problem**

fun subtract(firstNumber: Int, secondNumber: Int): Int {
    return firstNumber - secondNumber
}
It's wrong.
Answer is

fun subtract(firstNumber: Int, thirdNumber: Int): Int {
    return firstNumber - thirdNumber
}

![Screenshot_20240409_004738](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/166439449/bd7b20e9-c45f-4211-a0bc-81d71eb02e99)

**Comment by johnshea** [comment]
Hi @Balaguru1992 

Thank you for writing in.

The code as written is correct. The names of the function parameters do not need to match the name of the variables in the code.

Try the solution as written to confirm it works correctly.

Hope you are enjoying the course.

Regards.
