### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by robinsust** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#649]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Inconsistency:

 Greeting("Android")
&
 Greeting("Meghan")

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @robinsust 

Thank you for writing in with your concern.

The team will looking into it.

Hope you are enjoying the course!

Regards.
