### ISSUE TITLE
Column needs to be fillMaxHeight

### ISSUE THREAD

**Issue by richard-jones** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#657]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#8

**In which task and step of the codelab can this issue be found?**
Align greeting to the center: step 1

**Describe the problem**

```
verticalArrangement = Arrangement.Center,
modifier = modifier
```

does not cause the text to be arranged in the centre of the emulator screen, it appears at the top.

Instead

```
verticalArrangement = Arrangement.Center,
modifier = modifier.fillMaxHeight()
```

Is required

**Steps to reproduce?**
Just follow the codelab

**Versions**
_Android Studio version:_ Iguana 2023.2.1 Patch 2
_API version of the emulator:_ 34

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @richard-jones 

Thank you for writing in with your feedback.

Please confirm that the Surface has the modifier as detailed in the lesson

```
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    GreetingText(message = "Happy Birthday Sam!", from = "From Emma")
                }
```

If it does and you are still experiencing a problem, please create a new issue and provide your complete `MainActivity.kt` file so we can help troubleshoot further.

I look forward to your response.

Hope you are enjoying the course!

Regards.
