### ISSUE TITLE
Word error(I suppose)Create and use functions in Kotlin

### ISSUE THREAD

**Issue by Divy2143** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#659]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4

**In which task and step of the codelab can this issue be found?**

Create and use functions in Kotlin->5th module->Functions with multiple parameter

Previously, you added a parameter to change the greeting based on the name. However, you can also define more than one parameter for a function, even parameters of different data types. In this section, you'll modify the greeting so that it also changes based on the **dog's** age.

**Describe the problem**
Word error, there shouldn't be **dog's** age there.

**Additional information**
![KotlinDocError](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154802103/9a6289ba-5782-4abb-86cd-c5ae9059ff10)

**Comment by johnshea** [comment]
Hi @Divy2143 

Thank you for writing in with your feedback.

I will share it with the team so it can be addressed.

Hope you are enjoying the course!

Regards.
