### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by harri35** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#66]
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#10

**In which task and step of the codelab can this issue be found?**
At step 10 

**Describe the problem**
There are no other branches in the repo than the main one - https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app
The example shoes a /starter remote branch also

**Comment by osuleymanova** [comment]
@harri35 
Thank you for contacting us and sharing your concern.
This example is common to all codelabs. The main purpose of it is to show how to work with repositories if there is more than one branch.
