### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by sonukryadav** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#662]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#1

**In which task and step of the codelab can this issue be found?**
In the, Note section and when we hover the vertical more icon then their content

**Describe the problem**

In Note section in the UI some texts are  not visible because of white color or opacity is zero which looks like the content are missing.

Also there is color mismatch when we hover the vertical-more icon.

All this UI challenges are happening when i sign in and switch to dark mode only in light mode its working fine.
![s1](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/51019159/75b0f8eb-080e-47f0-9136-0ce33957a5f4)
![s2](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/51019159/35d089ad-de46-4ba5-bd8d-2e31ac5e0eb8)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sonukryadav** [comment]
After going forward with the documentation issue is same or other Note sections in different parts.

**Comment by johnshea** [comment]
Hi @sonukryadav 

Thank you for writing in.

I reviewed what you are wrote but I am not able to recreate this problem.

You are mentioning dark mode but your screenshot appears to be light mode which is confusing.

Can you please provide detailed step-by-step instructions with screenshots, so we can try recreate it exactly as you are doing.

Thank you in advance for your help.

Regards.

**Comment by johnshea** [comment]
As no additional follow up was provided, the issue will be closed.

If you are still experiencing this issue and have the time, please create a new issue and provide all the required information so we can evaluate it.

Regards.
