### ISSUE TITLE
Error en la respuesta

### ISSUE THREAD

**Issue by Kanopola** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#665]
¡Hola a todos!

En este Curso de Programación en Kotlin encontré que, en el área llamada "Código de solución", en la respuesta al tema "Implementación de operaciones matemáticas básicas", pusieron una respuesta errónea. También hice la prueba con el "Playground de Kotlin" en una ventana incognita por si la página estaba usando algunas cookies o lo que sea, pero el resultado es el mismo.

Cuando modifico el código y pongo los parámetros de la resta como van, entonces sí ofrece el resultado esperado.

Les dejo las capturas de pantalla correspondientes para que corroboren.

¡Saludos!

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

Hello everyone!

In this Kotlin Programming Course I found that, in the area called "Solution code", in the answer to the topic "Implementation of basic mathematical operations", they put an incorrect answer. I also tested with the "Kotlin Playground" in an incognito window in case the page was using some cookies or whatever, but the result is the same.

When I modify the code and put the subtraction parameters as they are, then it does offer the expected result.

I leave you the corresponding screenshots for you to corroborate.

Greetings!

![Screenshot_9](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56226178/42404fd9-60a7-48d3-aa78-6f4470534ffe)
![Screenshot_10](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56226178/8752eebf-b892-49d0-a946-661911475a2b)

**Comment by johnshea** [comment]
Hi @Kanopola 

Thank you for writing in.

The parameter names do not have to match the variable names.

It is fine that the second  parameter name in the `subtract` function is named `secondNumber`.

If you are saying the solution code produces an incorrect result, please create a new issue and provide the code you are running and screenshot detailing what is incorrect.

Hope you are enjoying the course!

Regards.

John

**Comment by Kanopola** [comment]
> Hi @Kanopola
> 
> Thank you for writing in.
> 
> The parameter names do not have to match the variable names.
> 
> It is fine that the second parameter name in the `subtract` function is named `secondNumber`.
> 
> If you are saying the solution code produces an incorrect result, please create a new issue and provide the code you are running and screenshot detailing what is incorrect.
> 
> Hope you are enjoying the course!
> 
> Regards.
> 
> John

Hello!

I have edited the first photo that contains the error in "Playground" so that you understand it better, since the previous one did not show the result.

In the second photo I made the corresponding corrections so that it gives the expected result.

Greetings!

*-*-*-*-*-*-*-*-*-

¡Hola!

He editado la primera foto que contiene el error en "Playground" para que lo entiendas mejor, ya que, la anterior no mostraba el resultado.

En la segunda foto hice las correcciones que correspondían para que dé el resultado esperado.

¡Saludos!

**Comment by Kanopola** [comment]
> Hi @Kanopola
> 
> Thank you for writing in.
> 
> The parameter names do not have to match the variable names.
> 
> It is fine that the second parameter name in the `subtract` function is named `secondNumber`.
> 
> If you are saying the solution code produces an incorrect result, please create a new issue and provide the code you are running and screenshot detailing what is incorrect.
> 
> Hope you are enjoying the course!
> 
> Regards.
> 
> John

Well, I understand that parameter names have nothing to do with variable names and I agree with that; However, in terms of clarity and effectiveness, these ambiguities can lead to confusion or errors, especially for someone new to reviewing the code.

I believe that it is essential to maintain a high standard of quality in software development.

Greetings!

--------------------------

Bueno, entiendo que los nombres de los parámetros no tienen que ver nada con los nombres de las variables y estoy de acuerdo en ello; Sin embargo, en términos de claridad y efectividad, estas embigüedades pueden llevar a confusiones o errores, especialmente para alguien nuevo revisando el código.

Creo que es fundamental mantener un alto estándar de calidad en el desarrollo de software.

¡Saludos!
