### ISSUE TITLE
Sugerenccia sobre una respuesta

### ISSUE THREAD

**Issue by Kanopola** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#666]
¡Hola a todos!

En este Curso de Programación en Kotlin encontré que, en el área llamada "Código de solución", en la respuesta al tema "Comparación de dos números", pusieron las preguntas sin el signo de interrogación al final. #AndroidBasics

Les dejo las capturas de pantalla correspondientes para que corroboren.

¡Saludos!

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

Hello everyone!
![Screenshot_12](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56226178/d0f4f64c-e555-4f85-b6fb-2adc850e5afa)

In this Kotlin Programming Course I found that, in the area called "Solution code", in the answer to the topic "Comparison of two numbers", they put the questions without the question mark at the end.

I leave you the corresponding screenshots for you to corroborate.

Greetings!
![Screenshot_11](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/56226178/3d20e772-e1be-4acb-9db0-6db51e7a7651)

**Comment by johnshea** [comment]
Hi @Kanopola 

Thank you for writing in with this observation.

I will share it with the team so they may consider it for a revision.

Hope you are enjoying the course!

Regards.
