### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Darkry7** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#669]
---- Hay algún cambio en la biblioteca verticalArrangement , no me funciono como debería.

@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    Column(
        verticalArrangement = Arrangement.Center,
        modifier = modifier
    ) {
        // ...
    }
}

---- Esto no me centro el texto, tuve que asignarle todo el espacio vertical disponible. Con Modifier.fillMaxHeight():

@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    Column(
        verticalArrangement = Arrangement.Center,
        modifier = Modifier.fillMaxHeight()
    ) {
        // ...
    }
}

Es algo minúsculo, pero seria bueno actualizar estos pequeños detalles. Alguien empezado se puede frustrar, o si es algo intencional, no e dicho nada.

**Comment by johnshea** [comment]
Hi @Darkry7 

Thank you for writing in.

Pleasd confirm that you have the correct modifiers being passed to the function calling `GreetingText`.

I would need to see your code to confirm but believe you are missing it.

Regards.

**Comment by Darkry7** [comment]
Hola Jhon

Gracias por contestar.

Este es el código:

package com.example.happybirthday

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.happybirthday.ui.theme.HappyBirthdayTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HappyBirthdayTheme {
                // A surface container using the 'background' color
from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    GreetingText(
                        message = "Happy brithday Ronald",
                        from = "From Deiby",
                        modifier = Modifier.padding(8.dp),
                        )
                }
            }
        }
    }
}

@Composable
fun GreetingText(message: String, from: String, modifier: Modifier = Modifier) {
    Column (
        verticalArrangement = Arrangement.Center,
        modifier = Modifier.fillMaxHeight(),
        ) {
        Text(
            text = message,
            fontSize = 100.sp,
            lineHeight = 116.sp,
            textAlign = TextAlign.Center
        )
        Text(
            text = from,
            fontSize = 36.sp,
            modifier = Modifier
                .padding(16.dp)
                .align(Alignment.End)
        )
    }
}

@Preview(showBackground = true)
@Composable
fun BirthdayCardPreview() {
    HappyBirthdayTheme {
        GreetingText(message = "Happy brithday Ronald", from = "From Deiby")
    }
}


Saludos.
