### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by ashbel123** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#67]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#1

**In which task and step of the codelab can this issue be found?**
In the second task of the codelab so-called "Compose article", in the Resources section

**Describe the problem**
the link that has been given to import the image in the resources section is not working.
It directs to the link:  https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/main/Unit%201/Pathway%203/ComposeArticle/app/src/main/res/drawable-nodpi/bg_compose_background.png

and the problem is it displays that ''this site can't be reached.''

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

Please provide the correct link for the resources.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ashbel123 
Thank you for contacting us. We couldn't replicate the issue as the link provided is working as expected:
https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/main/Unit%201/Pathway%203/ComposeArticle/app/src/main/res/drawable-nodpi/bg_compose_background.png 
Please feel free to re-open the ticket if you still face the issue.
