### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by D3xt3r000** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#670]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#5

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
When i add padding to project 
modifier = modifier.padding(24.dp)
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.layout.padding

i get error Unresolved reference: GreetingCardTheme

**Comment by johnshea** [comment]
Hi @D3xt3r000 

Thank you for writing in.

Please provide your file `MainActivity.kt` and also a screenshot so we can help troubleshoot it further.

Regards.

**Comment by D3xt3r000** [comment]
Hi,
I didn't use
"Make sure to use Optimize Imports to alphabetize the new imports."
After that program runs correct :)

You can close this Issue #670
Regards

czw., 25 kwi 2024 o 16:17 John Shea ***@***.***> napisał(a):

**Comment by johnshea** [comment]
Hi @D3xt3r000 

Glad you were able to figure out your issue.

Hope you are enjoying the course!

Regards.
