### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by ehsung2019** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#671]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#7

**In which task and step of the codelab can this issue be found?**
when i used '.align(alignment = Alignment.CenterHorizontally)', from name is at the start not center 

**Describe the problem**
when i used '.align(alignment = Alignment.CenterHorizontally)', from name is at the start not center

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Koala | 2024.1.1 Canary 5
Build #AI-241.14494.240.2411.11700778, built on April 11, 2024
Runtime version: 17.0.10+0--11679475 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true

_API version of the emulator:_ 
android 11.0 ("r") | x86

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ehsung2019 

Thank you for writing in.

Please share your complete `MainActivity.kt` file so we can help you troubleshoot further.

Regards.

**Comment by johnshea** [comment]
Hi @ehsung2019 

Please try again on a stable version of Android Studio.

If you still have an issue, create a new issue and provided the requested information.

Regards.
