### ISSUE TITLE
This requires a `@UiContext Context`, and it's not clear if `LocalContext.current` is guaranteed to be a `@UiContext`, although I suspect it should be.

### ISSUE THREAD

**Issue by Dramaga11** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#673]
This requires a `@UiContext Context`, and it's not clear if `LocalContext.current` is guaranteed to be a `@UiContext`, although I suspect it should be.

_Originally posted by @alexvanyo in https://github.com/google/accompanist/pull/1576#discussion_r1162039996_

**Comment by johnshea** [comment]
Hi.

Thank you for writing in but this issue does not relate to the course.

Regards.
