### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by EttoNekko** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#677]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3F_gl%3D1*uq7cav*_up*MQ..%26gclid%3DEAIaIQobChMInLfqz5j0hQMVOSZ7Bx3rOQPkEAAYASAAEgKtPfD_BwE%26gclsrc%3Daw.ds%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images&_gl=1*uq7cav*_up*MQ..&gclid=EAIaIQobChMInLfqz5j0hQMVOSZ7Bx3rOQPkEAAYASAAEgKtPfD_BwE&gclsrc=aw.ds#6

**In which task and step of the codelab can this issue be found?**
Task 7, step 6 and 9

**Describe the problem**
perhaps because I set the dark theme in the main course page, when I go to the codelab page, the theme for its page is still light, but                                 the code block and some text follow dark theme, hence the white text in white background?

**Additional information**
![downloadsec](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/100702053/4d337dcc-90a3-4aff-9743-63db30305432)

**Comment by johnshea** [comment]
Hi @EttoNekko 

Thank you for writing in and providing the steps on how to reproduce it.

It has been shared with the relevant team so it can be addressed.

Hope you are enjoying the course!

Regareds
