### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by fraguada** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#684]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
5

**Describe the problem**
I am trying to follow the step of surrounding a Text with a Surface container, but I get an error:
<img width="698" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/1014562/1888a59a-e86a-4d67-b63f-1607f3f8a466">

This is the code in the codelab:

```
@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
   Surface(color = Color.Cyan) {
       Text(
           text = "Hi, my name is $name!",
           modifier = modifier
       )
   }
}
```

**Steps to reproduce?**
1. Follow the "Create your first Android app" codelab through step 5.

**Versions**
_Android Studio version:_  Android Studio Jellyfish | 2023.3.1 / Build #AI-233.14808.21.2331.11709847, built on April 12, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by johnshea** [comment]
Hi @fraguada 

Glad you were able to figure it out.

Regards.
