### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by malithtennakoon** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#688]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#3

**In which task and step of the codelab can this issue be found?**
Introduction to programming in Kotlin in the active 5 (Create and use functions in Kotlin)

**Describe the problem**
The text is in white and it's not readable.  
Exact Para is 
"Note: Although you often find them used interchangeably, a parameter and an argument aren't the same thing. When you define a function, you define the parameters to be passed to it when it is called. When you call a function, you pass arguments for the parameters. Parameters are the variables accessible to the function, such as a name variable, while arguments are the actual values you pass, such as the "Rover" string." 
Here the word name and Rover are highlighted in white and it's not readble.

**Additional information**

![Screenshot 2024-05-10 at 2 07 05 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/47022680/7acbb467-9cb8-4e8b-ade4-4534b5111853)

**Comment by johnshea** [comment]
Hi @johnshea 

Thank you for writing in regarding this issue.

Try turning off "Dark Mode" from the top menu bar.

This is a temporary fix until it is fixed properly.

The appropriate team has already been notified.

Hope you are enjoying the course.

Regards.
