### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by croworc** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#69]
**URL of codelab**
  https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#2

**In which task and step of the codelab can this issue be found?**
Task 3 "Return a value from a function", Step "Return a String from birthdayGreeting()"

**Describe the problem**
Sub-step 2.: wrongly named variable. Inadvertently used the function's name. Currently reads:
  "You can only return one string from a function, not two, so you'll first create a variable for each: birthdayGreeting and ageGreeting."

But should read: "... a variable for each: nameGreeting and ageGreeting."

**Comment by osuleymanova** [comment]
@croworc 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-10-17 at 5 03 02 PM](https://user-images.githubusercontent.com/86437155/196305748-b7787f30-00f6-458d-b146-b1fe605c2859.png)
