### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by crysaro** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#690]
**In which task and step of the codelab can this issue be found?**
In step #5 

"UpsideDownCake" was not listed in the "Release Name" column. but instead it is "API 34"

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1 Patch 2

**Comment by johnshea** [comment]
Hi @crysaro 

Thank you for writing in and providing this feedback.

I will share it with the team.

Hope you are enjoying the course!

Regards.
