### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by LEARNERAPURBA** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#692]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#6)**

**Update the text**

**@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    GreetingCardTheme {
        Greeting("Meghan")
    }
} by changing the name here it is not changing.. the value of name parameter need to be changed in the onCreate method of the main function**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Koala | 2024.1.1 Nightly 2024-05-08
Build #AI-241.15989.150.2412.11814831, built on May 8, 2024

_API version of the emulator:_ 31-ext11

**Additional information**
Correct code
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            Application0Theme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    Greeting(
                        name = "urban",
                        modifier = Modifier.padding(innerPadding)
                    )
                }
            }
        }
    }
}

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Surface(color = Color.White) {
        Text(
            text = "Hi, my name is $name!",
            modifier = modifier.padding(48.dp)
        )
    }
}

@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    Application0Theme {
        Greeting("Android")
    }
}

**Comment by johnshea** [comment]
Hi @LEARNERAPURBA 

Thank you for writing in.

Changing the name in the `GreetingPreview` composable will just change the name shown in the preview in Android Studio. This will not change the name when run on the emulator.

To change the name shown in the emulator, you need to change the name in the `onCreate` function as you noted.

Hope you are enjoying the course!

Regards.
