### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose - Much struggle to see some parts of the Note

### ISSUE THREAD

**Issue by SamuelWakoli** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#695]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#1

**In which task and step of the codelab can this issue be found?**
The **Note** at the end of **Data Types**  

**Describe the problem**
The parts that were intended to be highlighted are not fully visible.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/97802502/1dd6caf3-4b52-4bc2-b2b1-0db1d35ca50d)

**Comment by SamuelWakoli** [comment]
Am using Dark Theme for the Android Developers website

**Comment by johnshea** [comment]
Hi @SamuelWakoli 

Thank you for writing in.

This is a known issue regarding the Dark Theme. If possible, please turn if off for now.

The responsible team is aware of the issue.

Regards.

**Comment by SamuelWakoli** [comment]
That's great!
Thank you @johnshea
