### ISSUE TITLE
Text composables: Android Basics in Compose (Readability Issue in the example image)

### ISSUE THREAD

**Issue by michaelssim** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#7]
**URL of codelab:** https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables

**Section:** 4. What is Jetpack Compose

**Issue:** It's difficult to see the difference between annotation without parameters and annotation previewing background. There's not enough contrast to see what exactly is the difference (i.e., when using light theme for Android Studio, the `showBackground = true` doesn't seem to have had any effect due to light background).
![android-compose-1](https://user-images.githubusercontent.com/81500505/166416676-5080b12e-6d5b-4824-ac79-6b91f75174cf.png)

**Suggested solution**: I decided to mess with my color schemes to learn what `showBackground` was exactly referring to.

![android-compose-2](https://user-images.githubusercontent.com/81500505/166416922-889566ab-7b08-4366-985d-f3232edcdda0.png)

![android-compose-3](https://user-images.githubusercontent.com/81500505/166416931-30368001-b5f3-42ab-b52a-22cc2a494979.png)

As you can see, it's super easy to understand in dark theme since there's no confusion at all for the learner.

Another solution is to actually darken the preview background to something less similar to white so that developers who prefer light theme will not run into this color issue.

Hope this helps. Thanks for creating these awesome tutorials by the way. You guys are the best.

**Comment by osuleymanova** [comment]
@michaelssim 
Thank you for reaching out to us. We really appreciate your feedback!
