### ISSUE TITLE
Your first program: Android Basics with Compose

### ISSUE THREAD

**Issue by Julius306** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#701]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-program?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-program#2

**In which task and step of the codelab can this issue be found?**
All

**Describe the problem**
The button to go back a page contains a wrong translation in the German version.
It says "Zurücksetzen" which would translate to "Reset" but it should be something like "Zurück" which means "Back".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
![Screenshot 2024-05-22 112042](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/69146115/fca27f61-2756-4cec-89a1-f4c5d3090464)

**Comment by johnshea** [comment]
Hi @Julius306 

Thank you for writing in and bringing this issue to our attention.

The team responsible for translations had been informed so they can address it as needed.

Hope you are enjoying the course!

Regards.
