### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by joeyc773** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#712]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
Change the background color (5), Step 9. 

**Describe the problem**
Text function is returning following error "@Composable invocations can only happen from the context of a @Composable function"

```
@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Surface(color = Color.Red) {
        Text(
            text = "Hi, my name is $name!",
            modifier = modifier
        )
    }
}
```

I've copied the script from the codelab directly to see if it was something I had done wrong but it still doesn't work. 

**Steps to reproduce?**
Follow codelab up to this point. 

**Versions**
_Android Studio version:_ 2023.3.1.19-windows
_API version of the emulator:_ Pixel 3a API 34 (unsure where to find version, this is all I can see)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @joeyc773 

Thank you for writing in!

Please share your full MainActivity.kt file so we can try to duplicate your exact issue.

Regards.

**Comment by johnshea** [comment]
Hi @joeyc773 

As you have not responded to my follow up, I will be closing this issue.

If you are still experiencing this issue, please create a new ticket and provide the requested information.

Regards.
