### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by InsanlyCrazysuperhulk** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#719]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
fun main() {
    birthdayGreeting()
}

fun birthdayGreeting() {
    println("Happy Birthday, Rover!")
    println("You are now 5 years old!")
}

**Comment by johnshea** [comment]
Hi @InsanlyCrazysuperhulk 

Thank you for writing in.

Are you having a problem? I am not seeing anything mentioned.

Regards.
