### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by dcrookston** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#724]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1

**In which task and step of the codelab can this issue be found?**
Task 2: Create a project using the template

Step 9: Click Split on the top right of Android Studio, this allows you to view both code and design. You can also click Code to view code only or click Design to view design only.

**Describe the problem**
The "Split" button isn't where the tutorial says it should be.

**Steps to reproduce?**
Just follow the tutorial.

**Versions**
_Android Studio version:_ I have no idea, look at the date of this bug report, look at the current studio version for that date, and figure it out yourself.  You're the one who wants me to use your dumb proprietary language, if you can't even get the tutorial right I'm sure as hell not going to do your homework for you.
_API version of the emulator:_ How the fuck would I even find this?  I literally downloaded the IDE ten minutes ago, I can't get through the tutorial without running into problems, and now you want to know what API version I'm using?  Yesus Freaking Cristos

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @dcrookston 

Thank you for writing in.

Attached is a screenshot of Android Studio Jellyfish (the latest stable version) showing the "Split" button in the top right corner.

<img width="901" alt="Screenshot 2024-06-11 at 2 32 03 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/7107817/f2e54c51-d663-4559-8746-c21f981ba02e">

If you are still having issues, please create a new GitHub issue with the requested information so we can help you further.

Hope you are enjoying the course!

Regards.
