### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Yoshikidyoshiki** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#726]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2

**In which task and step of the codelab can this issue be found?**

the second "third" step of accessing resources.

**Describe the problem**
Numbering is just a little bit confusing. 

![Screenshot 2024-06-08 141904](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/171932845/8633b1a9-2404-43f4-bdfc-73c5cf602780)

**Comment by johnshea** [comment]
Hi @Yoshikidyoshiki 

Thank you for writing in about this isue.

It has been corrected and the updated lesson will be republished again in the near future.

Hope you are enjoying the course!

Regrds.
