### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by jferriday** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#729]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3F_gl%3D1*axwhdv*_up*MQ..%26gclid%3DCj0KCQjwltKxBhDMARIsAG8KnqUdq6x8Lvqm4OGFoUkJ1C7VH_YWE974EG9A_yoJ8uwMA1fj4DbqjQAaAiwaEALw_wcB%26gclsrc%3Daw.ds%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app&_gl=1*axwhdv*_up*MQ..&gclid=Cj0KCQjwltKxBhDMARIsAG8KnqUdq6x8Lvqm4OGFoUkJ1C7VH_YWE974EG9A_yoJ8uwMA1fj4DbqjQAaAiwaEALw_wcB&gclsrc=aw.ds#1

**In which task and step of the codelab can this issue be found?**
Task 2- New Project step

**Describe the problem**
The documentation asks the user to create a new 'Empty Activity' project, but by doing this, the project will be setup without Compose, making the next step confusing since the code examples don't match up.

This should be changed to specify 'Empty Compose Activity' as it is written in the current versionsof Android Studio

**Steps to reproduce?**
1. Go to [Create your first Android app](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3F_gl%3D1*axwhdv*_up*MQ..%26gclid%3DCj0KCQjwltKxBhDMARIsAG8KnqUdq6x8Lvqm4OGFoUkJ1C7VH_YWE974EG9A_yoJ8uwMA1fj4DbqjQAaAiwaEALw_wcB%26gclsrc%3Daw.ds%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app&_gl=1*1izomka*_up*MQ..&gclid=Cj0KCQjwltKxBhDMARIsAG8KnqUdq6x8Lvqm4OGFoUkJ1C7VH_YWE974EG9A_yoJ8uwMA1fj4DbqjQAaAiwaEALw_wcB&gclsrc=aw.ds)

3. Click on step 2 - create the project using a template
4. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
<img width="600" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/70819699/b539df14-a34c-4489-ba7f-2d81e90d7917">

**Comment by johnshea** [comment]
Hi @jferriday 

Thank you for writing in.

Please install the latest stable version of Android Studio and try again.

If there is still an issue, please provide all the requested information so we can investigate further.

Hope you are enjoying the course!

Regards.
