### ISSUE TITLE
Run your first app: Android Basics with Compose

### ISSUE THREAD

**Issue by Lamouresparus** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#731]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-emulator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-emulator&hl=en#2

**In which task and step of the codelab can this issue be found?**
- Task 3: Run your app on the Android Emulator
  - Step 6

**Describe the problem**

There is no red warning in the screenshot image above the sentence:
"Note: If you see the red warning about using an image with Google APIs like in the screenshot above, you can disregard it for now."

**Additional information**
<img width="796" alt="Screenshot 2024-06-18 at 10 40 41" src="https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/34775925/751ae067-d024-4a50-9f40-12a50993e518">

**Comment by johnshea** [comment]
Hi @Lamouresparus 

Thank you for writing in and bringing this to our attention.

It has been corrected and the updated lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.

**Comment by Lamouresparus** [comment]
Yes I am. Thank you
