### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by danilomsilva** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#77]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-classes-and-objects?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-classes-and-objects#6

**In which task and step of the codelab can this issue be found?**

-> Use classes and objects in Kotlin - Step 7 ( Implement a relationship between classes )

**Describe the problem**
-> The topic describes:
In the main() function, use the var keyword to define a SmartDevice variable of **SmartTvDevice** type that instantiates a SmartTvDevice object that takes an "Android TV" argument and an "Entertainment" argument

But if I am understanding correctly the explanation from the beginning, it should be:

In the main() function, use the var keyword to define a SmartDevice variable of **SmartDevice** type that instantiates a SmartTvDevice object that takes an "Android TV" argument and an "Entertainment" argument

**Steps to reproduce?**
1. Go to the URL provided above
2. Click on step number 4 ( Use classes and objects in Kotlin ) then Take codelab. Click on step number 7 from the left navigation and scroll down to Override superclass methods from subclasses and then item 4.
3. See an error in the text: **In the main() function, use the var keyword to define a SmartDevice variable of SmartTvDevice type that instantiates a SmartTvDevice object that takes an "Android TV" argument and an "Entertainment" argument:**

**Additional information**
It seems there's confusion with the used terms on this page. The description on item 4 says "variable of **SmartTvDevice**" but then in the code snippet below it, the type is named **SmartDevice**.

**Comment by osuleymanova** [comment]
Hello @danilomsilva,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-01-17 at 1 55 57 PM](https://user-images.githubusercontent.com/86437155/213021391-28b2846b-bac3-4514-8e5b-3c3bfe0f4094.png)
