### ISSUE TITLE
Business Card app: Update wireframes

### ISSUE THREAD

**Issue by AdamWiernicki** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#78]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-business-card?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-business-card#1

**Describe the problem**
In Business Card task the UI schema is not compatible with the screenshot from the previous page in this task. *watch the alignment of contact section there on the bottom.

**Comment by android-dev-lxl** [comment]
@AdamWiernicki 
Thanks for the suggestion.
Fixed and to be published.


<img width="469" alt="image" src="https://user-images.githubusercontent.com/24260141/217652558-15dd206a-1211-4578-aecb-ba343ede04c1.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/24260141/217652595-d01d65d3-b9c0-49cc-bb1a-476d1320f9ff.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/24260141/217652640-e9bd0bf0-02bc-4272-907e-307da4235934.png">
