### ISSUE TITLE
Text composables: Android Basics in Compose

### ISSUE THREAD

**Issue by ManojSoo** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#3

**In which task and step of the codelab can this issue be found?**
Notice the composable functions in code

**Describe the problem**
In codelab Its BirthdayCardTheme. In Android Studio its HappyBirthdayTheme

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/28492443/168118285-a4960283-1048-4790-82c2-84d6589d6263.png)
![image](https://user-images.githubusercontent.com/28492443/168118430-708f3afe-3e22-4d98-b120-c603d8f6763a.png)

![image](https://user-images.githubusercontent.com/28492443/168118366-e4b1e96d-a13c-4a26-a052-59a559a7132e.png)

**Comment by osuleymanova** [comment]
@ManojSoo 
Thank you for reaching out to us and reporting this issue. It is fixed and will be published soon:
![Screen Shot 2022-05-16 at 11 43 22 AM](https://user-images.githubusercontent.com/86437155/168661015-7002d9b6-5541-45e0-a34d-9aafbc08023a.png)
Happy coding!
