### ISSUE TITLE
Connect your Android device: Android Basics with Compose

### ISSUE THREAD

**Issue by rhzs** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#88]
**URL of codelab**
URL https://developer.android.com/codelabs/basic-android-kotlin-compose-connect-device?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-connect-device#2

![3a5910f5cf07382f](https://user-images.githubusercontent.com/5300674/196015543-72fa5968-1c6e-44fd-bfb1-562808b2385f.png)

In the above tutorial screenshot, there is a highlighted red box `Google USB Driver`. But in reality, I couldn't find such option. 

<img width="989" alt="Screen Shot 2022-10-16 at 09 45 40" src="https://user-images.githubusercontent.com/5300674/196015513-a1615304-c380-4800-865a-b1119ff7f8a8.png">

**Comment by osuleymanova** [comment]
@rhzs 
Thank you for contacting us. In case you are using Mac OS, so it doesn’t require the Google Android USB Drivers to be installed. They are readily available and no extra work is needed to make them work. Just connect your device to Mac and it will be detected automatically and you can start transferring Media and other files to and from Mac to Android device.
