### ISSUE TITLE
Functions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by tehami94** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#89]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-functions#4

**In which task and step of the codelab can this issue be found?**
In the last image there is error.
https://developer.android.com/static/codelabs/basic-android-kotlin-compose-functions/img/45ad1199b078b4aa.png

**Describe the problem**
 String and Int are type whereas name and age are parameters but in the image "Int" is pointed as a parameter.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![codelab](https://user-images.githubusercontent.com/93815993/196058676-f93d8409-0948-4eba-9275-22c543105118.png)

**Comment by osuleymanova** [comment]
@tehami94 
Thank you for reaching out to us and sharing your concern. The arrows were omitted in the parameter list, so they won't be confusing anymore:

![Screen Shot 2022-10-17 at 4 53 22 PM](https://user-images.githubusercontent.com/86437155/196305279-faefe3d7-936c-4fa8-af51-950baad66ab8.png)
