### ISSUE TITLE
Text composables: Android Basics in Compose

### ISSUE THREAD

**Issue by pajatopmr** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#9]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#4

**In which task and step of the codelab can this issue be found?**
Build a simple app with text composables
Step 5. Design pane in Android Studio

**Describe the problem**
The code generated by BumbleBee in ActivityMain.kt uses "Happy Birthday Theme" but the preview code snippet in Step 5 uses "BirthdayCardTheme".  These should be consistent.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Chipmunk 2021.2.1
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@pajatopmr 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The image is updated and will be published soon:
![Screen Shot 2022-05-16 at 12 39 48 PM](https://user-images.githubusercontent.com/86437155/168669656-57db7802-5801-4bb7-832f-82c90236e71d.png)
