### ISSUE TITLE
Before you begin: Android Basics with Compose

### ISSUE THREAD

**Issue by TheReptileMP** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#923]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-before-you-begin?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-before-you-begin#0)**

**The problem is found when clicking the codelab link to learn to program using view**

**When you click to see the course on Android basics in Kotlin with the previous UI (Views), the codelab of the current version of the course opens and does not allow access to the old version**

**Steps to reproduce?**
1. Go to... Other training materials
2. Click on... [Android Basics in Kotlin course.
](https://g.co/android/basics)
3. See error...

**Versions**
_Android Studio version:_ -
_API version of the emulator:_ - 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by kkuan2011** [comment]
Ah the Views version of the course has now been deprecated, so that redirect is working as intended. I think there is an issue with this translated page being out of date because that link was removed from the English version of this page. Thanks for flagging!
