### ISSUE TITLE
Practice: Compose Basics, 3. Task manager: UI specification image and description does not match

### ISSUE THREAD

**Issue by JurajSimasek** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#93]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#2

**In which task and step of the codelab can this issue be found?**
[TRAINING](https://developer.android.com/courses) > [ANDROID BASICS WITH COMPOSE](https://developer.android.com/courses/android-basics-compose/course) > [FIRST ANDROID APP](https://developer.android.com/courses/android-basics-compose/unit-1) > [BASIC LAYOUT](https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-3)
step 5. Practice: Compose Basics
task 3. Task manager
part UI specification

**Describe the problem**
UI Specification image does not match description below it.

In UI specification steps 2 and 3:
2. Set the first Text composable to a 24sp font size, 24dp padding top, and 8dp padding bottom.
3. Set the second Text composable to a 16sp font size.

In Image above specification text  are both texts with same fontSize. Also First one is bold and that is not specified by these steps.

**Additional information**
After folowing written steps, the result is as folowing:
![Screenshot 2022-10-18 at 20 36 43](https://user-images.githubusercontent.com/49816147/196515815-d4bb8fbb-bb4e-4e00-a2ba-6128062d594c.png)

**Comment by JurajSimasek** [comment]
Accidentally posted issue to wrong

**Comment by benfallon** [comment]
+1 -- just noticed this same thing @JurajSimasek. 

Also, to detail a bit further for the team at Google, the solution code in the TaskCompleted repository matches the UI spec _screenshot_ (bold, default textSize of 16sp), while item #2 in the UI spec _text description_ is different from both of these (no mention of bold, textSize of 24sp).
https://github.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/blob/main/Unit%201/Pathway%203/TaskCompleted/app/src/main/java/com/example/taskcompleted/MainActivity.kt

So, depending on what UI specs the Google team who made this codelab intended, in order for everything to be consistent either:
- Item #2 in the UI spec text description needs to be updated to _add_ **bold** and _remove_ 24sp, OR
- Both the UI spec screenshot and the solution code need to be updated to _remove_ **bold** and _add_ 24sp textSize

**Comment by osuleymanova** [comment]
Hello @JurajSimasek,

Thank you for reaching out to us and reporting this issue. The UI specification is updated:

![Screenshot 2023-01-17 at 11 28 04 AM](https://user-images.githubusercontent.com/86437155/212994262-fa9593bf-d820-4abf-ae93-85bb1c1672fc.png)
