### ISSUE TITLE
Variables in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by prilstas** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#930]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-variables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-variables#4)

**In which task and step of the codelab can this issue be found?**
Explore other data types

**Describe the problem**
<img width="800" alt="Снимок экрана 2024-12-02 в 6 00 41 PM" src="https://github.com/user-attachments/assets/ece1f930-cc2a-4084-9c97-c7ad0781ea1f">
There is an issue that you did not add Strings to the code

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by kkuan2011** [comment]
Hello, while the String was not explicitly defined, the String was added in the code as "Are notifications enabled? ", and then a boolean was appended to it. If you still think there's an error, you can reopen the issue.
