### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by lpeter0912** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#934]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#5

**In which task and step of the codelab can this issue be found?**

fontSize is also in red for me and it can not recognize that command 

**Describe the problem**
It maybe because I am trying to learn now in 2024 and the tutorial is out dated. I dont know I am a beginner.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
 Android Studio Ladybug | 2024.2.1 Patch 3
Build #AI-242.23339.11.2421.12700392, built on November 22, 2024
Runtime version: 21.0.3+-12282718-b509.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4072M
Cores: 24
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.edu (2024.10-2024.2-1604)

_API version of the emulator:_  35

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![{4A015C5B-C2E3-474D-94D0-3EB702627EBC}](https://github.com/user-attachments/assets/085b45b7-2e46-4cd7-ad2a-3d101e25eb6a)

**Comment by kkuan2011** [comment]
Hello! Try importing sp as well to fix the issue.

import androidx.compose.ui.unit.sp
