### ISSUE TITLE
First Android app: Android Basics with Compose

### ISSUE THREAD

**Issue by p-thack** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#940]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app#4

**In which task and step of the codelab can this issue be found?**
It is after this instruction that I have a problem --> "Delete Box and type Surface() instead."

**Describe the problem**
Changing the name of the container from "Box" to "Surface()" gives error: "Unresolved reference: Surface". Continuing on with the instruction does not fix it.

**Steps to reproduce?**
See above

**Versions**
Android Studio Ladybug | 2024.2.1 Patch 3
Build #AI-242.23339.11.2421.12700392, built on November 22, 2024
Runtime version: 21.0.3+-79915915-b509.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 12.6.7
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Registry:
  ide.experimental.ui=true

**Comment by kkuan2011** [comment]
If you add this import, it should fix it: 
import androidx.compose.material3.Surface

At that point in the codelab, the full list of imports should look something like this:

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.greetingcard.ui.theme.GreetingCardTheme
import androidx.compose.ui.graphics.Color

Hope that fixes it!
