### ISSUE TITLE
No exercise in page. Text Error

### ISSUE THREAD

**Issue by L1Xu4n** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#941]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#9

**In which task and step of the codelab can this issue be found?**
10.Compare Number

**Describe the problem**
In Chinese version, there is no any exercise
You can see it in shortcut 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/user-attachments/assets/272b63cc-caa0-4d5e-9764-8ca373a70172)

**Comment by kkuan2011** [comment]
Hello! The prompt here is asking you to create a function that meets that criteria. The English version of the codelab is the same. The solution is on step 12 of the codelab: https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-kotlin-practice-problems?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-1%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-kotlin-practice-problems#11

If there's still an issue, feel free to reopen. Thanks!
