### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by DLT1412** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#97]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
missing step guide to import `androidx.compose.foundation.Image`, can not auto import with quick import

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Duplicate of #94

**Comment by android-dev-lxl** [comment]
Duplicate of #156 
To be published
