### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by AshuraFirdaus** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#99]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#4

**In which task and step of the codelab can this issue be found?**
add images to your android app

**Describe the problem**
Android pop ups " Unresolved reference: BirthdayGreetingWithText " albeit im following the instruction

**Steps to reproduce?**
1. Go to... To make the above changes reflect in the emulator or a device, in the onCreate() function, replace the BirthdayGreetingWithText() function call with a BirthdayGreetingWithImage() function.
2. Click on... run the program 
3. See error... Unresolved reference: BirthdayGreetingWithText

**Versions**
_Android Studio version:_ 2021.2.1 patch 1
_API version of the emulator:_ 
![1](https://user-images.githubusercontent.com/70957708/198171334-76b5b370-e01c-4d37-bf04-ee3c503075e9.png)
![2](https://user-images.githubusercontent.com/70957708/198171337-ef93b290-35bd-4328-9b32-81d1494136c5.png)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@AshuraFirdaus 
Thank you for reaching out to us. 
Did you by any chance remove the `BirthdayGreetingWithText` composable function?
You need it, please refer to the solution code:

https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/blob/main/app/src/main/java/com/example/happybirthday/MainActivity.kt


<img width="688" alt="image" src="https://user-images.githubusercontent.com/24260141/213777723-d16cef3a-a39f-41f0-9d8e-c1aa77152a10.png">

**Comment by android-dev-lxl** [comment]
@AshuraFirdaus 
Thank you for reaching out to us. 

As there has been no response for the past two weeks, we are closing the issue. 
Please open a new ticket if you need further assistance.
